extends SceneTree

const CharacterInfoOverlay := preload("res://scripts/hud/character_info_overlay.gd")

var _failures: Array[String] = []


func _init() -> void:
	_verify_character_info_uses_anatomy_equipment_slots()

	if _failures.is_empty():
		print("character_info_equipment_anatomy_smoke: ok")
		quit(0)
	else:
		for failure in _failures:
			push_error(failure)
		quit(1)


func _verify_character_info_uses_anatomy_equipment_slots() -> void:
	var overlay: Object = CharacterInfoOverlay.new()
	_expect(overlay != null, "character info overlay should instantiate")
	var source := FileAccess.get_file_as_string("res://scripts/hud/character_info_overlay.gd")
	var draw_body := _function_body(source, "func draw(")
	_expect(draw_body.find("_draw_equipment_slots(") >= 0, "character info should render anatomy equipment slots")
	_expect(draw_body.find("_draw_equipment_slots_grid(") < 0, "character info should not render the fallback equipment grid")
	_expect(source.find("func _draw_equipment_anatomy_silhouette") >= 0, "anatomy equipment silhouette draw helper should remain available")
	_expect(CharacterInfoOverlay.CHARACTER_CARD_GLOW_LAYERS <= 1, "character card glow should stay within the overlay draw budget")
	_expect(CharacterInfoOverlay.CHARACTER_CARD_RING_SEGMENTS <= 12, "character card ring should stay within the tightened overlay draw budget")
	_expect(CharacterInfoOverlay.FALLBACK_SYMBOL_RING_SEGMENTS <= 8, "fallback symbols should stay within the tighter overlay draw budget")
	_expect(CharacterInfoOverlay.EQUIPMENT_BODY_RING_SEGMENTS <= 4, "equipment anatomy body ring should stay within the tightened overlay draw budget")
	_expect(CharacterInfoOverlay.EQUIPMENT_BODY_ARC_SEGMENTS <= 3, "equipment anatomy body arcs should stay within the overlay draw budget")
	_expect(CharacterInfoOverlay.EQUIPMENT_EMPTY_RING_SEGMENTS <= 3, "empty equipment slot rings should stay within the tightened overlay draw budget")
	_expect(CharacterInfoOverlay.EQUIPMENT_PLACEHOLDER_ARC_SEGMENTS <= 4, "equipment placeholder arcs should stay within the overlay draw budget")
	_expect(CharacterInfoOverlay.EQUIPMENT_ACCESSORY_RING_SEGMENTS <= 3, "equipment accessory placeholder rings should stay within the tightened overlay draw budget")
	_expect(source.find("if hovered:\n\t\t\tkey = _equipment_slot_keys[i]\n\t\t\t_draw_equipment_connector(canvas, content_rect, key, slot_center_x, slot_center_y") >= 0, "equipment connectors should be hover-only in the overlay draw budget")
	_expect(source.find("var mouse_in_equipment_rect: bool = rect.has_point(mouse_pos)") >= 0, "equipment hover hit-tests should be section-gated")
	_expect(source.find("var accessory_slot_count: int = _get_accessory_slot_count(owner)") >= 0, "equipment draw should cache accessory slot count before slot iteration")
	_expect(source.find("var _equipment_slot_accessory_numbers: Array[int] = []") >= 0, "equipment slot metadata should cache accessory slot numbers")
	_expect(source.find("_equipment_slot_accessory_numbers.append(accessory_number)") >= 0, "equipment metadata cache should precompute accessory slot numbers")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_is_equipment_slot_enabled(") < 0, "equipment anatomy draw should not parse accessory slot strings per visible slot")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("var accessory_number: int = _equipment_slot_accessory_numbers[i]") >= 0, "equipment frame cache should reuse cached accessory slot numbers")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("var enabled: bool = accessory_number <= 0 or accessory_number <= accessory_slot_count") >= 0, "equipment frame cache should use integer accessory comparisons before draw iteration")
	_expect(source.find("var can_draw_item_icon: bool = _active_item_icon_renderer != null and _active_item_icon_renderer.has_method(\"draw_icon\")") >= 0, "equipment draw should check item icon renderer capability once before slot iteration")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("if can_draw_item_icon:") >= 0, "equipment slot loop should reuse the cached item icon renderer capability")
	_expect(_function_body(source, "func _update_equipment_slot_layout(").find("var fallback_center := content_rect.get_center()") >= 0, "equipment anatomy layout should own the fallback center")
	_expect(_function_body(source, "func _update_equipment_slot_layout(").find("var slot_extent := Vector2(slot_size, slot_size)") >= 0, "equipment anatomy layout should own the slot extent vector")
	_expect(source.find("elif hovered:") >= 0, "idle empty and locked equipment slots should skip placeholder detail until hover")
	_expect(source.find("if not hovered:\n\t\treturn") >= 0, "idle equipment slot frames should skip corner accent draw")
	_expect(source.find("if not has_item and enabled:") >= 0, "idle enabled empty equipment slots should keep circular detail behind the hover gate")
	_expect(source.find("if hovered:\n\t\t\tkey = _equipment_slot_keys[i]\n\t\t\t_draw_equipment_connector(canvas, content_rect, key, slot_center_x, slot_center_y") >= 0, "equipment connectors should remain hover-gated")
	_expect(source.find("_update_equipment_slot_layout(content_rect, slot_size)") >= 0, "equipment anatomy layout should reuse cached slot rects while the panel is stable")
	_expect(source.find("_equipment_slot_rect_cache") >= 0, "equipment anatomy slot rect cache should remain wired")
	_expect(source.find("var _equipment_slot_rect_list_cache: Array[Rect2] = []") >= 0, "equipment anatomy should keep an indexed slot rect cache for draw iteration")
	_expect(source.find("func _ensure_equipment_slot_layout_cache_size(slot_count: int) -> void:") >= 0, "equipment anatomy layout caches should be sized together")
	_expect(source.find("_equipment_slot_rect_list_cache.resize(slot_count)") >= 0, "equipment anatomy layout should size the indexed slot rect cache with slot metadata")
	_expect(source.find("var _equipment_slot_icon_rect_cache: Array[Rect2] = []") >= 0, "equipment anatomy layout should cache item icon rects")
	_expect(source.find("var _equipment_slot_fallback_rect_cache: Array[Rect2] = []") >= 0, "equipment anatomy layout should cache fallback icon rects")
	_expect(source.find("var _equipment_slot_placeholder_rect_cache: Array[Rect2] = []") >= 0, "equipment anatomy layout should cache placeholder rects")
	_expect(source.find("var _equipment_slot_locked_line_a_start_cache: Array[Vector2] = []") >= 0, "equipment locked slot line start points should be cached with layout")
	_expect(source.find("var _equipment_slot_locked_line_b_end_cache: Array[Vector2] = []") >= 0, "equipment locked slot line end points should be cached with layout")
	_expect(source.find("var _equipment_slot_center_x_cache: Array[float] = []") >= 0, "equipment anatomy layout should cache slot center x values")
	_expect(source.find("var _equipment_slot_center_y_cache: Array[float] = []") >= 0, "equipment anatomy layout should cache slot center y values")
	_expect(source.find("var _equipment_slot_label_y_cache: Array[float] = []") >= 0, "equipment anatomy layout should cache label y values")
	_expect(source.find("_equipment_slot_rect_list_cache[i] = slot_rect") >= 0, "equipment anatomy layout should fill indexed slot rects next to the hover rect map")
	_expect(source.find("_equipment_slot_icon_rect_cache[i] = Rect2(slot_x + 5.0, slot_y + 5.0, slot_w - 10.0, slot_h - 10.0)") >= 0, "equipment anatomy layout should prebuild item icon rects")
	_expect(source.find("_equipment_slot_fallback_rect_cache[i] = Rect2(slot_x + 8.0, slot_y + 8.0, slot_w - 16.0, slot_h - 16.0)") >= 0, "equipment anatomy layout should prebuild fallback icon rects")
	_expect(source.find("_equipment_slot_placeholder_rect_cache[i] = Rect2(slot_x + 7.0, slot_y + 7.0, slot_w - 14.0, slot_h - 14.0)") >= 0, "equipment anatomy layout should prebuild placeholder rects")
	_expect(source.find("_equipment_slot_locked_line_a_start_cache[i] = Vector2(slot_x + 9.0, slot_y + 9.0)") >= 0, "equipment anatomy layout should prebuild locked slot line points")
	_expect(source.find("_equipment_slot_locked_line_b_end_cache[i] = Vector2(slot_x + 9.0, slot_y + slot_h - 9.0)") >= 0, "equipment anatomy layout should prebuild locked slot line endpoints")
	_expect(source.find("_equipment_slot_center_x_cache[i] = slot_x + slot_w * 0.5") >= 0, "equipment anatomy layout should precompute slot center x")
	_expect(source.find("_equipment_slot_center_y_cache[i] = slot_y + slot_h * 0.5") >= 0, "equipment anatomy layout should precompute slot center y")
	_expect(source.find("_equipment_slot_label_y_cache[i] = min(slot_y + slot_h + float(label_size) + 6.0, content_rect.end.y - 2.0)") >= 0, "equipment anatomy layout should precompute label y")
	_expect(source.find("_last_equipment_slot_rects = _equipment_slot_rect_cache") >= 0, "equipment hover/context rects should reuse the anatomy slot rect cache")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_last_equipment_slot_rects[key] = slot_rect") < 0, "equipment anatomy draw should not copy cached slot rects back into a second dictionary")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_rect: Rect2 = _equipment_slot_rect_list_cache[i]") >= 0, "equipment anatomy draw should read slot rects directly by cached index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("i < _equipment_slot_rect_list_cache.size()") < 0, "equipment anatomy draw should not bounds-check the stable slot rect cache per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("Rect2(fallback_center") < 0, "equipment anatomy draw should not allocate fallback slot rects per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_rect_cache.get(key") < 0, "equipment anatomy draw should not query the slot rect dictionary per visible slot")
	_expect(source.find("const EQUIPMENT_SLOT_FILL_ENABLED := Color(13.0 / 255.0, 18.0 / 255.0, 32.0 / 255.0, 0.92)") >= 0, "equipment slot enabled fill should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_SLOT_FILL_DISABLED := Color(13.0 / 255.0, 18.0 / 255.0, 32.0 / 255.0, 0.42)") >= 0, "equipment slot disabled fill should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_SLOT_BORDER_DISABLED := Color(85.0 / 255.0, 91.0 / 255.0, 112.0 / 255.0, 0.30)") >= 0, "equipment disabled slot border should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_SLOT_BORDER_FILLED := Color(105.0 / 255.0, 245.0 / 255.0, 170.0 / 255.0, 0.92)") >= 0, "equipment filled slot border should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_LABEL_DISABLED := Color(120.0 / 255.0, 126.0 / 255.0, 142.0 / 255.0)") >= 0, "equipment disabled label color should be cached as a shared constant")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("var fill_alpha: float") < 0, "equipment slot frames should not recreate fill colors through per-slot alpha state")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("var border_alpha: float") < 0, "equipment slot frames should not recreate border colors through per-slot alpha state")
	_expect(source.find("var _equipment_slot_fill_color_cache: Array[Color] = []") >= 0, "equipment slot fill colors should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_border_width_cache: Array[float] = []") >= 0, "equipment slot border widths should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_locked_line_color_cache: Array[Color] = []") >= 0, "equipment locked slot line colors should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_frame_cache_slot_state_hash := 0") >= 0, "equipment frame cache should keep a scalar slot state hash")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_fill_color_cache[i] = EQUIPMENT_SLOT_FILL_ENABLED if enabled else EQUIPMENT_SLOT_FILL_DISABLED") >= 0, "equipment frame cache should choose fill colors before draw iteration")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_border_width_cache[i] = 2.0 if _equipment_slot_has_item_cache[i] else 1.4") >= 0, "equipment frame cache should choose default border widths before draw iteration")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_locked_line_color_cache[i] = Color(base_color.r, base_color.g, base_color.b, 0.32)") >= 0, "equipment frame cache should choose locked slot line colors before draw iteration")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("var slot_state_hash: int = hash(slot_state)") >= 0, "equipment frame cache should include the slot state hash")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_frame_cache_matches(slot_state_hash, accessory_slot_count, slot_count)") >= 0, "equipment frame cache should skip stable slot state refreshes without string formatting")
	_expect(source.find("func _equipment_slot_frame_cache_matches(slot_state_hash: int, accessory_slot_count: int, slot_count: int) -> bool:") >= 0, "equipment frame cache should compare scalar cache keys")
	_expect(source.find("func _make_equipment_slot_frame_cache_signature(") < 0, "equipment frame cache should not keep a string-signature helper")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var border_width: float = _equipment_slot_border_width_cache[i]") >= 0, "equipment anatomy draw should read border width by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("border_width = 2.0") >= 0, "equipment anatomy draw should only override border width for hovered empty enabled slots")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_draw_equipment_slot_frame(canvas, slot_rect, _equipment_slot_fill_color_cache[i], base_color, border_color, border_width, enabled, has_item, hovered)") >= 0, "equipment anatomy draw should pass preselected fill and border width to slot frame")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("canvas.draw_rect(slot_rect, fill_color)") >= 0, "equipment slot frame helper should draw preselected fill colors")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("canvas.draw_rect(slot_rect, border_color, false, border_width)") >= 0, "equipment slot frame helper should draw preselected border widths")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("EQUIPMENT_SLOT_FILL_ENABLED if enabled") < 0, "equipment slot frame helper should not choose fill colors")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("2.0 if hovered or has_item else 1.4") < 0, "equipment slot frame helper should not choose border widths")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("Color(color.r, color.g, color.b, border_alpha)") < 0, "equipment slot frames should not allocate a border color every slot")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("var empty_center := slot_rect.get_center()") >= 0, "equipment hover empty slot detail should reuse the slot center")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("canvas.draw_circle(slot_rect.get_center()") < 0, "equipment hover empty slot detail should not recompute center for the circle")
	_expect(_function_body(source, "func _draw_equipment_slot_frame(").find("canvas.draw_arc(slot_rect.get_center()") < 0, "equipment hover empty slot detail should not recompute center for the ring")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_draw_locked_slot(canvas, i)") >= 0, "equipment locked slot draw should use the cached slot index")
	_expect(_function_body(source, "func _draw_locked_slot(").find("_equipment_slot_locked_line_a_start_cache[slot_index]") >= 0, "locked equipment slot helper should draw cached line endpoints")
	_expect(_function_body(source, "func _draw_locked_slot(").find("slot_rect.position + Vector2(9.0, 9.0)") < 0, "locked equipment slot helper should not rebuild line points while drawing")
	_expect(source.find("const EQUIPMENT_COLOR_DISABLED := Color(85.0 / 255.0, 91.0 / 255.0, 112.0 / 255.0)") >= 0, "equipment disabled color should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_COLOR_FILLED := Color(105.0 / 255.0, 245.0 / 255.0, 170.0 / 255.0)") >= 0, "equipment filled color should be cached as a shared constant")
	_expect(_function_body(source, "func _equipment_color(").find("return Color(") < 0, "equipment color lookup should return shared constants instead of allocating fresh colors")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("EQUIPMENT_LABEL_DISABLED") >= 0, "equipment frame cache should reuse the disabled label color constant")
	_expect(source.find("func _ensure_equipment_slot_metadata_cache() -> void:") >= 0, "equipment slot metadata should be cached outside the draw loop")
	_expect(source.find("var _equipment_slot_keys: Array[String] = []") >= 0, "equipment slot key metadata cache should remain wired")
	_expect(source.find("var _equipment_slot_index_cache: Dictionary = {}") >= 0, "equipment slot metadata should keep a key-to-index cache")
	_expect(source.find("_equipment_slot_index_cache[key] = _equipment_slot_keys.size()") >= 0, "equipment slot metadata should populate key-to-index cache before appending keys")
	_expect(source.find("var _equipment_slot_compact_labels: Array[String] = []") >= 0, "equipment compact slot labels should be cached outside the draw loop")
	_expect(source.find("var _equipment_slot_visible_label_cache: Array[String] = []") >= 0, "equipment visible labels should use a reusable slot label cache")
	_expect(source.find("func _refresh_equipment_slot_visible_label_cache(use_compact: bool) -> void:") >= 0, "equipment visible label cache should refresh outside the draw loop")
	_expect(source.find("var _equipment_slot_empty_colors: Array[Color] = []") >= 0, "equipment empty slot colors should be cached with slot metadata")
	_expect(source.find("var _equipment_slot_empty_border_colors: Array[Color] = []") >= 0, "equipment empty slot border colors should be cached with slot metadata")
	_expect(source.find("var _equipment_slot_item_cache: Array[Dictionary] = []") >= 0, "equipment slot items should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_has_item_cache: Array[bool] = []") >= 0, "equipment slot item state should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_enabled_cache: Array[bool] = []") >= 0, "equipment slot enabled state should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_label_color_cache: Array[Color] = []") >= 0, "equipment slot label colors should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_base_color_cache: Array[Color] = []") >= 0, "equipment slot base colors should use a reusable per-slot draw cache")
	_expect(source.find("var _equipment_slot_border_color_cache: Array[Color] = []") >= 0, "equipment slot border colors should use a reusable per-slot draw cache")
	_expect(source.find("func _refresh_equipment_slot_frame_cache(slot_state: Dictionary, accessory_slot_count: int) -> void:") >= 0, "equipment frame cache should be refreshed once before slot iteration")
	_expect(source.find("func _ensure_equipment_slot_frame_cache_size(slot_count: int) -> void:") >= 0, "equipment frame cache arrays should be sized together")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_refresh_equipment_slot_frame_cache(slot_state, accessory_slot_count)") >= 0, "equipment anatomy draw should prepare slot frame cache before the loop")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var item_data: Dictionary = _equipment_slot_item_cache[i]") >= 0, "equipment anatomy draw should read item data by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var has_item: bool = _equipment_slot_has_item_cache[i]") >= 0, "equipment anatomy draw should read has-item state by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var enabled: bool = _equipment_slot_enabled_cache[i]") >= 0, "equipment anatomy draw should read enabled state by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_label_color_cache[i]") >= 0, "equipment anatomy labels should read label colors by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var base_color: Color = _equipment_slot_base_color_cache[i]") >= 0, "equipment anatomy draw should read base color by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var border_color: Color = _equipment_slot_border_color_cache[i]") >= 0, "equipment anatomy draw should read border color by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("if hovered and enabled and not has_item:") >= 0, "equipment anatomy draw should only override cached borders for hovered empty enabled slots")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_get_equipment_item(slot_state, key)") < 0, "equipment anatomy draw should not query the slot state dictionary per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("not item_data.is_empty()") < 0, "equipment anatomy draw should not recompute has-item state per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("accessory_number <= 0 or accessory_number <= accessory_slot_count") < 0, "equipment anatomy draw should not recompute enabled state per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("TEXT_SOFT if enabled else EQUIPMENT_LABEL_DISABLED") < 0, "equipment anatomy draw should not branch label colors per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var empty_color: Color = _equipment_slot_empty_colors[i]") < 0, "equipment anatomy draw should not read empty colors in the visible slot loop")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var empty_border_color: Color = _equipment_slot_empty_border_colors[i]") < 0, "equipment anatomy draw should not read empty border colors in the visible slot loop")
	_expect(source.find("_equipment_slot_empty_colors.append(empty_color)") >= 0, "equipment metadata cache should precompute empty slot colors")
	_expect(source.find("_equipment_slot_empty_border_colors.append(Color(empty_color.r, empty_color.g, empty_color.b, 0.58))") >= 0, "equipment metadata cache should precompute idle empty slot border colors")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("EQUIPMENT_SLOT_DEFINITIONS") < 0, "equipment anatomy draw should reuse cached slot metadata instead of parsing definition dictionaries")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_label(") < 0, "equipment anatomy draw should reuse cached compact slot labels")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_color(base, has_item, enabled)") < 0, "equipment anatomy draw should not run string color matching in the slot loop")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var key := \"\"") >= 0, "equipment anatomy draw should defer slot key lookup")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var key: String = _equipment_slot_keys[i]") < 0, "equipment anatomy draw should not read slot keys unconditionally")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("if hovered:\n\t\t\tkey = _equipment_slot_keys[i]") >= 0, "equipment anatomy draw should read slot keys for hovered connector/tooltip paths")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("if key == \"\":\n\t\t\t\t\tkey = _equipment_slot_keys[i]") >= 0, "equipment anatomy fallback symbol path should read slot keys only when needed")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_base_color_cache[i] = EQUIPMENT_COLOR_DISABLED if not enabled else EQUIPMENT_COLOR_FILLED if _equipment_slot_has_item_cache[i] else _equipment_slot_empty_colors[i]") >= 0, "equipment frame cache should choose base colors from cached constants and metadata")
	_expect(_function_body(source, "func _refresh_equipment_slot_frame_cache(").find("_equipment_slot_border_color_cache[i] = EQUIPMENT_SLOT_BORDER_DISABLED if not enabled else EQUIPMENT_SLOT_BORDER_FILLED if _equipment_slot_has_item_cache[i] else _equipment_slot_empty_border_colors[i]") >= 0, "equipment frame cache should choose border colors from cached constants and metadata")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("EQUIPMENT_COLOR_DISABLED if not enabled") < 0, "equipment anatomy draw should not choose base colors per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("EQUIPMENT_SLOT_BORDER_FILLED if hovered or has_item") < 0, "equipment anatomy draw should not choose default border colors per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_x: float = slot_rect.position.x") < 0, "equipment anatomy draw should not recalculate slot x per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_w: float = slot_rect.size.x") < 0, "equipment anatomy draw should not recalculate slot width per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_icon_rect_cache[i]") >= 0, "equipment item icon draw should reuse cached icon rects")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_fallback_rect_cache[i]") >= 0, "equipment fallback icon draw should reuse cached fallback rects")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_placeholder_rect_cache[i]") >= 0, "equipment placeholder draw should reuse cached placeholder rects")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("Rect2(slot_x") < 0, "equipment anatomy draw should not allocate slot-derived rects per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("slot_rect.grow(") < 0, "equipment anatomy draw should not allocate grown rects per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_center_x: float = _equipment_slot_center_x_cache[i]") >= 0, "equipment anatomy labels should reuse cached slot center x")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_center_y: float = _equipment_slot_center_y_cache[i]") >= 0, "equipment anatomy connector centers should reuse cached slot center y")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_label_y_cache[i]") >= 0, "equipment anatomy labels should reuse cached label y")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var slot_center := Vector2(") < 0, "equipment anatomy connector centers should avoid per-hover temporary vectors")
	_expect(source.find("for i in range(_equipment_slot_keys.size()):") >= 0, "equipment loops should iterate cached slot metadata")
	_expect(source.find("_equipment_slot_center_cache") < 0, "equipment anatomy layout should not keep a parallel center cache")
	_expect(source.find("_update_equipment_silhouette_geometry(content_rect, slot_size)") >= 0, "equipment anatomy silhouette should reuse cached geometry while the panel is stable")
	_expect(source.find("var hovered_slot_index := -1") >= 0, "equipment anatomy draw should resolve hovered slot index once")
	_expect(source.find("func _find_hovered_equipment_slot_index(mouse_pos: Vector2) -> int:") >= 0, "equipment anatomy hover should use an indexed slot helper")
	_expect(source.find("hovered_slot_index = _find_hovered_equipment_slot_index(mouse_pos)") >= 0, "equipment anatomy hover should reuse cached indexed slot rects")
	_expect(source.find("_draw_equipment_anatomy_silhouette(canvas, content_rect, slot_size, hovered_slot_index >= 0)") >= 0, "equipment anatomy detail draw should be slot-hover-gated")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_find_hovered_rect_key(_equipment_slot_rect_cache") < 0, "equipment anatomy draw should not scan the slot rect dictionary for hover")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_index_cache.get(") < 0, "equipment anatomy draw should not map hovered slot keys back to indexes")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_equipment_slot_keys.find(") < 0, "equipment anatomy draw should not linearly scan slot keys for hover index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var hovered: bool = i == hovered_slot_index") >= 0, "equipment slot loop should compare hovered slot by cached index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("key == hovered_slot_key") < 0, "equipment slot loop should not compare slot keys as strings per visible slot")
	_expect(source.find("var equipment_label_size: int = 10 if slot_size >= 40.0 else 8") >= 0, "equipment anatomy label size should be resolved once before slot iteration")
	_expect(source.find("var use_compact_equipment_labels: bool = slot_size < 42.0") >= 0, "equipment anatomy compact label branch should be resolved once before slot iteration")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("_refresh_equipment_slot_visible_label_cache(use_compact_equipment_labels)") >= 0, "equipment anatomy draw should refresh visible labels before slot iteration")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var visible_label: String = _equipment_slot_visible_label_cache[i]") >= 0, "equipment slot loop should read visible labels by cached slot index")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var visible_label: String = _equipment_slot_compact_labels[i] if use_compact_equipment_labels else label") < 0, "equipment slot loop should not branch visible labels per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var visible_label: String = label if slot_size >= 42.0 else _equipment_slot_compact_labels[i]") < 0, "equipment slot loop should not recheck compact label size per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var label_size: int = 10 if slot_size >= 40.0 else 8") < 0, "equipment slot loop should not recheck label font size per visible slot")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("elif hovered:\n\t\t\tvar base: String = _equipment_slot_bases[i]") >= 0, "equipment anatomy draw should read placeholder base only for hovered empty slots")
	_expect(_function_body(source, "func _draw_equipment_slots(").find("var base: String = _equipment_slot_bases[i]\n\t\tvar slot_rect") < 0, "equipment anatomy draw should not read placeholder base for every visible slot")
	_expect(source.find("func _find_hovered_rect_key(rects: Dictionary, mouse_pos: Vector2) -> Variant:") >= 0, "shared hover key helper should remain wired")
	_expect(source.find("func _get_equipment_slot_key_at_mouse(mouse_pos: Vector2) -> String:") >= 0, "equipment context click should resolve slot keys through cached indexes first")
	_expect(_function_body(source, "func _get_equipment_slot_key_at_mouse(").find("var slot_index: int = _find_hovered_equipment_slot_index(mouse_pos)") >= 0, "equipment slot key lookup should try cached slot indexes first")
	_expect(_function_body(source, "func _try_handle_equipment_context_click(").find("var slot_key: String = _get_equipment_slot_key_at_mouse(mouse_pos)") >= 0, "equipment context click should use indexed slot key lookup")
	_expect(_function_body(source, "func _try_handle_equipment_context_click(").find("_find_hovered_rect_key(_last_equipment_slot_rects") < 0, "equipment context click should not scan the slot rect dictionary on the hot path")
	_expect(source.find("_equipment_item_display_name_cache_hash") >= 0, "equipment hover title should be hash cache guarded")
	_expect(source.find("func _equipment_item_display_name_hash(item_data: Dictionary) -> int:") >= 0, "equipment hover title should use a compact item hash")
	_expect(source.find("func _equipment_item_display_name_signature(") < 0, "equipment hover title should not build string signatures")
	_expect(source.find("_item_quality_color_cache_hash") >= 0, "equipment hover quality color should be hash cache guarded")
	_expect(source.find("func _item_quality_color_hash(item_data: Dictionary, fallback: Color) -> int:") >= 0, "equipment hover quality color should use a compact item hash")
	_expect(source.find("func _item_quality_color_signature(") < 0, "equipment hover quality color should not build string signatures")
	_expect(source.find("if show_detail:") >= 0, "equipment anatomy decorative arcs should be opt-in detail")
	_expect(source.find("if show_detail:\n\t\tcanvas.draw_colored_polygon(_equipment_silhouette_left_arm_poly") >= 0, "equipment anatomy limb polygons should be hover-detail gated")
	_expect(source.find("_equipment_silhouette_torso_poly") >= 0, "equipment anatomy silhouette polygon cache should remain wired")
	_expect(source.find("const EQUIPMENT_SILHOUETTE_BASE := Color(32.0 / 255.0, 43.0 / 255.0, 72.0 / 255.0, 0.46)") >= 0, "equipment silhouette base color should be cached as a shared constant")
	_expect(source.find("const EQUIPMENT_SILHOUETTE_LINE := Color(105.0 / 255.0, 134.0 / 255.0, 205.0 / 255.0, 0.18)") >= 0, "equipment silhouette line color should be cached as a shared constant")
	_expect(_function_body(source, "func _draw_equipment_anatomy_silhouette(").find("var base_color := Color(") < 0, "equipment silhouette draw should not recreate the base color every frame")
	_expect(_function_body(source, "func _draw_equipment_anatomy_silhouette(").find("var deep_color := Color(") < 0, "equipment silhouette draw should not recreate the deep color every frame")
	_expect(_function_body(source, "func _draw_equipment_anatomy_silhouette(").find("var line_color := Color(") < 0, "equipment silhouette draw should not recreate the line color every frame")
	_expect(_function_body(source, "func _draw_equipment_anatomy_silhouette(").find("canvas.draw_colored_polygon(_equipment_silhouette_torso_poly, EQUIPMENT_SILHOUETTE_BASE)") >= 0, "equipment silhouette torso should reuse the cached base color")
	_expect(_function_body(source, "func _draw_equipment_anatomy_silhouette(").find("canvas.draw_arc(_equipment_silhouette_head_center, slot_size * 0.43, 0.0, TAU, EQUIPMENT_BODY_RING_SEGMENTS, EQUIPMENT_SILHOUETTE_LINE, 1.0)") >= 0, "equipment silhouette detail ring should reuse the cached line color")
	_expect(source.find("const PASSIVE_INVENTORY_COLUMN_TARGET := 84.0") >= 0, "passive inventory grid density should stay within the overlay draw budget")
	_expect(source.find("runtime.get(\"inventory_items\")") >= 0, "passive inventory draw should read live runtime items before falling back to snapshot copies")
	_expect(
		source.find("var live_items_value: Variant = runtime.get(\"inventory_items\")") >= 0,
		"passive inventory draw should read the live runtime inventory as a variant"
	)
	_expect(
		_function_body(source, "func _get_passive_inventory_items(").find("if live_items_value is Array:\n\t\t\treturn live_items_value") >= 0,
		"passive inventory draw should return the live runtime array even when it is empty"
	)
	_expect(
		_function_body(source, "func _get_passive_inventory_items(").find("for item_name in equipped:") >= 0,
		"passive inventory equipped-state fallback should iterate dictionary keys without allocating keys()"
	)
	_expect(source.find("var _passive_grid_visible_index_cache: Array[int] = []") >= 0, "passive inventory grid should cache visible item indexes")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("_passive_grid_visible_index_cache.clear()") >= 0, "passive inventory layout should clear visible indexes before refill")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("_passive_grid_visible_index_cache.append(i)") >= 0, "passive inventory layout should cache visible item indexes")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("for i in _passive_grid_visible_index_cache:") >= 0, "passive inventory draw should iterate cached visible indexes")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("row * columns + col") < 0, "passive inventory draw should not recompute visible item indexes")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("for row in range(_passive_grid_visible_first_row") < 0, "passive inventory draw should not run nested visible row loops")
	_expect(source.find("var passive_cell_extent := Vector2(cell_size, cell_size)") < 0, "passive inventory draw should not keep a per-grid cell extent vector")
	_expect(source.find("var _passive_grid_cell_rect_cache: Array[Rect2] = []") >= 0, "passive inventory grid should cache visible cell rects")
	_expect(source.find("var _passive_grid_icon_rect_cache: Array[Rect2] = []") >= 0, "passive inventory grid should cache visible icon rects")
	_expect(source.find("var _passive_grid_fallback_rect_cache: Array[Rect2] = []") >= 0, "passive inventory grid should cache visible fallback rects")
	_expect(source.find("func _update_passive_inventory_grid_layout(") >= 0, "passive inventory grid should update visible layout geometry through a helper")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("var cell_x: float = start_x + float(col) * stride") >= 0, "passive inventory grid should compute cell x only when the visible layout changes")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("_passive_grid_cell_rect_cache[i] = Rect2(cell_x, row_y, cell_size, cell_size)") >= 0, "passive inventory grid layout should prebuild cell rects")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("var cell_x: float = start_x + float(col) * stride") < 0, "passive inventory draw loop should not recompute cell x")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("var cell_rect: Rect2 = _passive_grid_cell_rect_cache[i]") >= 0, "passive inventory draw loop should read cached cell rects")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("var cell_rect := Rect2(cell_x, row_y, cell_size, cell_size)") < 0, "passive inventory draw loop should avoid Rect2 construction per visible cell")
	_expect(source.find("const OVERLAY_GRID_FILL := Color(10.0 / 255.0, 14.0 / 255.0, 24.0 / 255.0, 0.55)") >= 0, "overlay grid background fill should be cached as a shared constant")
	_expect(source.find("const OVERLAY_GRID_CELL_FILL := Color(20.0 / 255.0, 25.0 / 255.0, 38.0 / 255.0, 0.96)") >= 0, "overlay grid cell fill should be cached as a shared constant")
	_expect(source.find("canvas.draw_rect(cell_rect, OVERLAY_GRID_CELL_FILL)") >= 0, "passive/perk grid cell draw should reuse the cached cell fill")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("Color(20.0 / 255.0, 25.0 / 255.0, 38.0 / 255.0, 0.96)") < 0, "passive inventory draw loop should not recreate the fixed cell fill color")
	_expect(source.find("func _prepare_passive_inventory_draw_cache(inventory_items: Array) -> Dictionary:") >= 0, "passive inventory should prepare item draw metadata and summary in one pass")
	_expect(source.find("var summary: Dictionary = _prepare_passive_inventory_draw_cache(inventory_items)") >= 0, "passive inventory draw should reuse the one-pass prepared summary")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("_get_passive_inventory_summary(inventory_items)") < 0, "passive inventory draw should not scan the full item list a second time for summary")
	_expect(source.find("func _set_passive_inventory_summary(item_count: int, equipped_count: int) -> Dictionary:") >= 0, "passive inventory summary cache should be shared by direct and draw-time calls")
	_expect(source.find("item_data[\"_draw_color\"] = color") >= 0, "passive inventory draw metadata should cache item frame colors")
	_expect(source.find("var equipped: bool = bool(item_data.get(\"equipped\", false)) or str(item_data.get(\"_equipped_slot\", \"\")) != \"\"") >= 0, "passive inventory draw metadata should compute equipped state once")
	_expect(source.find("var cached_equipped: Variant = item_data.get(\"_draw_equipped\", null)") >= 0, "passive inventory draw metadata should read cached equipped state before writing")
	_expect(source.find("if typeof(cached_equipped) != TYPE_BOOL or bool(cached_equipped) != equipped:") >= 0, "passive inventory draw metadata should only rewrite equipped state when it changes")
	_expect(source.find("item_data[\"_draw_equipped\"] = equipped") >= 0, "passive inventory draw metadata should cache equipped state")
	_expect(source.find("var _passive_inventory_equipped_cache: Array[bool] = []") >= 0, "passive inventory draw loop should keep typed equipped state")
	_expect(source.find("var equipped: bool = _passive_inventory_equipped_cache[i]") >= 0, "passive inventory draw loop should reuse cached equipped state")
	_expect(_function_body(source, "func _get_passive_inventory_summary(").find("bool(item_data.get(\"_draw_equipped\", false))") >= 0, "passive inventory summary should reuse cached equipped state")
	_expect(_function_body(source, "func _get_passive_inventory_summary(").find("if not item_data.has(\"_draw_equipped\"):") >= 0, "passive inventory summary should keep a direct-call equipped fallback")
	_expect(source.find("var _passive_inventory_item_cache: Array[Dictionary] = []") >= 0, "passive inventory draw loop should keep typed item dictionaries")
	_expect(source.find("var _passive_inventory_draw_color_cache: Array[Color] = []") >= 0, "passive inventory draw loop should keep typed item frame colors")
	_expect(source.find("var item_data: Dictionary = _passive_inventory_item_cache[i]") >= 0, "passive inventory draw loop should reuse cached item dictionaries")
	_expect(source.find("var color: Color = _passive_inventory_draw_color_cache[i]") >= 0, "passive inventory draw loop should use cached item frame colors")
	_expect(source.find("item_data[\"_draw_border_color\"] = Color(color.r, color.g, color.b, 0.48)") >= 0, "passive inventory draw metadata should cache idle border colors")
	_expect(source.find("item_data[\"_draw_active_border_color\"] = Color(color.r, color.g, color.b, 0.90)") >= 0, "passive inventory draw metadata should cache active border colors")
	_expect(source.find("var _passive_inventory_border_color_cache: Array[Color] = []") >= 0, "passive inventory draw loop should keep typed idle border colors")
	_expect(source.find("var border_color: Color = _passive_inventory_border_color_cache[i]") >= 0, "passive inventory draw loop should read cached border colors")
	_expect(source.find("canvas.draw_rect(cell_rect, border_color, false, 2.0 if hovered or equipped else 1.0)") >= 0, "passive inventory draw loop should use cached border colors")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("var row_y: float = start_y + float(row) * stride") >= 0, "passive inventory layout should compute row y once per visible row")
	_expect(source.find("_draw_passive_inventory_scrollbar(canvas, grid_rect, max_scroll)") >= 0, "passive inventory scrollbar should reuse the computed max scroll")
	_expect(source.find("const OVERLAY_SCROLLBAR_TRACK := Color(0.0, 0.0, 0.0, 0.35)") >= 0, "character info scrollbars should reuse a shared track color")
	_expect(source.find("const OVERLAY_PERK_SCROLLBAR_THUMB := Color(120.0 / 255.0, 170.0 / 255.0, 1.0, 0.72)") >= 0, "perk scrollbar should reuse a shared thumb color")
	_expect(source.find("const OVERLAY_PASSIVE_SCROLLBAR_THUMB := Color(120.0 / 255.0, 220.0 / 255.0, 170.0 / 255.0, 0.72)") >= 0, "passive inventory scrollbar should reuse a shared thumb color")
	_expect(source.find("var _perk_scrollbar_track_rect := Rect2()") >= 0, "perk scrollbar should cache its track rect")
	_expect(source.find("var _passive_scrollbar_track_rect := Rect2()") >= 0, "passive inventory scrollbar should cache its track rect")
	_expect(_function_body(source, "func _update_perk_scrollbar_layout(").find("_perk_scrollbar_track_rect = Rect2(grid_rect.end.x - 6.0, grid_rect.position.y + 4.0, 4.0, grid_rect.size.y - 8.0)") >= 0, "perk scrollbar layout should prebuild the track without temporary Vector2 objects")
	_expect(_function_body(source, "func _update_perk_scrollbar_layout(").find("_perk_scrollbar_thumb_rect = Rect2(_perk_scrollbar_track_rect.position.x, thumb_y, _perk_scrollbar_track_rect.size.x, thumb_h)") >= 0, "perk scrollbar layout should prebuild the thumb without temporary Vector2 objects")
	_expect(_function_body(source, "func _draw_scrollbar(").find("canvas.draw_rect(_perk_scrollbar_track_rect, OVERLAY_SCROLLBAR_TRACK)") >= 0, "perk scrollbar draw should reuse the cached track rect")
	_expect(_function_body(source, "func _draw_scrollbar(").find("canvas.draw_rect(_perk_scrollbar_thumb_rect, OVERLAY_PERK_SCROLLBAR_THUMB)") >= 0, "perk scrollbar draw should reuse the cached thumb rect")
	_expect(_function_body(source, "func _update_passive_inventory_scrollbar_layout(").find("_passive_scrollbar_track_rect = Rect2(grid_rect.end.x - 6.0, grid_rect.position.y + 4.0, 4.0, grid_rect.size.y - 8.0)") >= 0, "passive inventory scrollbar layout should prebuild the track without temporary Vector2 objects")
	_expect(_function_body(source, "func _update_passive_inventory_scrollbar_layout(").find("_passive_scrollbar_thumb_rect = Rect2(_passive_scrollbar_track_rect.position.x, thumb_y, _passive_scrollbar_track_rect.size.x, thumb_h)") >= 0, "passive inventory scrollbar layout should prebuild the thumb without temporary Vector2 objects")
	_expect(_function_body(source, "func _draw_passive_inventory_scrollbar(").find("canvas.draw_rect(_passive_scrollbar_track_rect, OVERLAY_SCROLLBAR_TRACK)") >= 0, "passive inventory scrollbar draw should reuse the cached track rect")
	_expect(_function_body(source, "func _draw_passive_inventory_scrollbar(").find("canvas.draw_rect(_passive_scrollbar_thumb_rect, OVERLAY_PASSIVE_SCROLLBAR_THUMB)") >= 0, "passive inventory scrollbar draw should reuse the cached thumb rect")
	_expect(source.find("const OVERLAY_EQUIPPED_BADGE_FILL := Color(70.0 / 255.0, 160.0 / 255.0, 1.0, 0.92)") >= 0, "equipped badge should reuse a shared fill color")
	_expect(source.find("var _passive_grid_badge_rect_cache: Array[Rect2] = []") >= 0, "passive inventory should cache equipped badge rects with the grid layout")
	_expect(_function_body(source, "func _update_passive_inventory_grid_layout(").find("_passive_grid_badge_rect_cache[i] = Rect2(cell_x + cell_size - 18.0, row_y + cell_size - 14.0, 16.0, 12.0)") >= 0, "passive inventory layout should prebuild equipped badge rects")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("_draw_equipped_badge(canvas, _passive_grid_badge_rect_cache[i], _passive_grid_badge_center_x_cache[i], _passive_grid_badge_center_y_cache[i], font)") >= 0, "passive inventory draw should reuse cached equipped badge geometry")
	_expect(_function_body(source, "func _draw_equipped_badge(").find("var badge_rect := Rect2(cell_rect.end.x - 18.0, cell_rect.end.y - 14.0, 16.0, 12.0)") < 0, "equipped badge should not rebuild its rect inside the draw helper")
	_expect(_function_body(source, "func _draw_equipped_badge(").find("canvas.draw_rect(badge_rect, OVERLAY_EQUIPPED_BADGE_FILL)") >= 0, "equipped badge should reuse the fixed badge fill color")
	_expect(source.find("var can_draw_passive_item_icon: bool = _active_item_icon_renderer != null and _active_item_icon_renderer.has_method(\"draw_icon\")") >= 0, "passive inventory should check icon renderer capability once before visible item iteration")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("if can_draw_passive_item_icon:") >= 0, "passive inventory draw loop should reuse the cached item icon renderer capability")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("var icon_rect := Rect2(cell_x + 5.0, row_y + 5.0, cell_size - 10.0, cell_size - 10.0)") < 0, "passive inventory icon rects should not be rebuilt inside the draw loop")
	_expect(source.find("_active_item_icon_renderer.draw_icon(canvas, _passive_grid_icon_rect_cache[i], item_data, 1.0, visuals)") >= 0, "passive inventory icon draw should reuse cached icon rects")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("var fallback_rect := Rect2(cell_x + 9.0, row_y + 9.0, cell_size - 18.0, cell_size - 18.0)") < 0, "passive inventory fallback rects should not be rebuilt inside the draw loop")
	_expect(source.find("_draw_fallback_symbol(canvas, _passive_grid_fallback_rect_cache[i], color, str(item_data.get(\"name\", \"\")))") >= 0, "passive inventory fallback draw should reuse cached fallback rects")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("cell_rect.grow(") < 0, "passive inventory draw loop should not allocate grown rects per visible cell")
	_expect(source.find("var mouse_in_passive_grid_rect: bool = grid_rect.has_point(mouse_pos)") >= 0, "passive inventory hover hit-tests should be section-gated")
	_expect(source.find("var hovered_passive_index := -1") >= 0, "passive inventory should resolve hovered item index once")
	_expect(source.find("hovered_passive_index = _get_hovered_grid_index(mouse_pos, _last_passive_grid_start.x, _last_passive_grid_start.y, _last_passive_grid_cell_size, _last_passive_grid_stride, columns, inventory_items.size())") >= 0, "passive inventory hover should use cached grid index math")
	_expect(source.find("var hovered: bool = i == hovered_passive_index") >= 0, "passive inventory draw loop should reuse the hovered item index")
	_expect(source.find("var index: int = _get_cached_grid_hover_index(") >= 0, "passive inventory context click should reuse cached grid index math")
	_expect(_function_body(source, "func _draw_passive_inventory(").find("_last_passive_inventory_item_rects[i] = cell_rect") < 0, "passive inventory draw should not rebuild rect dictionaries after grid hover metrics are cached")
	_expect(_function_body(source, "func _draw_perk_grid(").find("_last_perk_item_rects[i] = cell_rect") < 0, "perk grid draw should not rebuild rect dictionaries after grid hover metrics are cached")
	_expect(source.find("_passive_item_body_cache_hash") >= 0, "passive item tooltip body should be hash cache guarded")
	_expect(source.find("func _passive_item_body_hash(item_data: Dictionary) -> int:") >= 0, "passive item tooltip body should use a compact item hash")
	_expect(source.find("func _passive_item_body_signature(") < 0, "passive item tooltip body should not build string signatures")
	_expect(source.find("_passive_item_frame_color_cache") >= 0, "passive inventory frame colors should be cache guarded")
	_expect(source.find("func _passive_item_frame_color_hash(item_data: Dictionary) -> int:") >= 0, "passive inventory frame colors should use a compact item hash")
	_expect(source.find("func _passive_item_frame_color_signature(") < 0, "passive inventory frame colors should not build string signatures")
	_expect(source.find("func _get_string_fallback(data: Dictionary, key: String, fallback_key: String") >= 0, "hot tooltip fallback strings should use a lazy helper")
	_expect(source.find("var _perk_grid_cell_rect_cache: Array[Rect2] = []") >= 0, "perk grid should cache visible cell rects")
	_expect(source.find("var _perk_grid_visible_index_cache: Array[int] = []") >= 0, "perk grid should cache visible perk indexes")
	_expect(source.find("var _perk_grid_icon_rect_cache: Array[Rect2] = []") >= 0, "perk grid should cache visible icon rects")
	_expect(source.find("func _update_perk_grid_layout(") >= 0, "perk grid should update visible layout geometry through a helper")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("_perk_grid_visible_index_cache.clear()") >= 0, "perk grid layout should clear visible indexes before refill")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("_perk_grid_visible_index_cache.append(i)") >= 0, "perk grid layout should cache visible perk indexes")
	_expect(_function_body(source, "func _draw_perk_grid(").find("for i in _perk_grid_visible_index_cache:") >= 0, "perk grid draw should iterate cached visible indexes")
	_expect(_function_body(source, "func _draw_perk_grid(").find("row * columns + col") < 0, "perk grid draw should not recompute visible perk indexes")
	_expect(_function_body(source, "func _draw_perk_grid(").find("for row in range(_perk_grid_visible_first_row") < 0, "perk grid draw should not run nested visible row loops")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("_perk_grid_visible_first_row = max(0, int(ceil((scroll - cell_size) / stride)))") >= 0, "perk grid layout should compute the first visible row")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("_perk_grid_visible_last_row = min(rows - 1, int(floor((scroll + grid_rect.size.y) / stride)))") >= 0, "perk grid layout should compute the last visible row")
	_expect(source.find("var perk_cell_extent := Vector2(cell_size, cell_size)") < 0, "perk grid draw should not keep a per-grid cell extent vector")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("var perk_icon_w: float = cell_size - 10.0") >= 0, "perk grid layout should cache icon width as a scalar")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("var perk_icon_h: float = cell_size - 17.0") >= 0, "perk grid layout should cache icon height as a scalar")
	_expect(_function_body(source, "func _update_perk_grid_layout(").find("_perk_grid_icon_rect_cache[i] = Rect2(cell_x + 5.0, row_y + 4.0, perk_icon_w, perk_icon_h)") >= 0, "perk grid layout should prebuild icon rects")
	_expect(_function_body(source, "func _draw_perk_grid(").find("var icon_rect := Rect2(cell_x + 5.0, row_y + 4.0, perk_icon_w, perk_icon_h)") < 0, "perk grid icon rects should not be rebuilt inside the draw loop")
	_expect(_function_body(source, "func _draw_perk_grid(").find("cell_rect.position + perk_icon_offset") < 0, "perk grid icon rect should not allocate a temporary offset Vector2")
	_expect(_function_body(source, "func _draw_perk_grid(").find("Color(20.0 / 255.0, 25.0 / 255.0, 38.0 / 255.0, 0.96)") < 0, "perk grid draw loop should not recreate the fixed cell fill color")
	_expect(source.find("data[\"_draw_border_color\"] = Color(draw_color.r, draw_color.g, draw_color.b, 0.48)") >= 0, "perk grid draw metadata should cache idle border colors")
	_expect(source.find("data[\"_draw_hover_border_color\"] = Color(draw_color.r, draw_color.g, draw_color.b, 0.92)") >= 0, "perk grid draw metadata should cache hover border colors")
	_expect(source.find("var _acquired_perk_border_color_cache: Array[Color] = []") >= 0, "perk grid draw loop should keep typed idle border colors")
	_expect(source.find("var border_color: Color = _acquired_perk_border_color_cache[i]") >= 0, "perk grid draw loop should read cached border colors")
	_expect(source.find("canvas.draw_rect(cell_rect, border_color, false, 2.0 if hovered else 1.0)") >= 0, "perk grid draw loop should use cached border colors")
	_expect(source.find("var can_draw_perk_icon: bool = icon_renderer != null and icon_renderer.has_method(\"draw_icon\")") >= 0, "perk grid should check icon renderer capability once before visible perk iteration")
	_expect(_function_body(source, "func _draw_perk_grid(").find("if not can_draw_perk_icon or not bool(icon_renderer.draw_icon(canvas, perk_id, _perk_grid_icon_rect_cache[i], 1.0, true)):") >= 0, "perk grid draw loop should reuse the cached icon renderer capability")
	_expect(source.find("_draw_scrollbar(canvas, grid_rect, max_perk_scroll)") >= 0, "perk scrollbar should reuse the computed max scroll")
	_expect(source.find("var mouse_in_perk_grid_rect: bool = grid_rect.has_point(mouse_pos)") >= 0, "perk hover hit-tests should be section-gated")
	_expect(source.find("var hovered_perk_index := -1") >= 0, "perk grid should resolve hovered perk index once")
	_expect(source.find("hovered_perk_index = _get_hovered_grid_index(mouse_pos, _last_perk_grid_start.x, _last_perk_grid_start.y, _last_perk_grid_cell_size, _last_perk_grid_stride, columns, acquired.size())") >= 0, "perk grid hover should use cached grid index math")
	_expect(source.find("var hovered: bool = i == hovered_perk_index") >= 0, "perk grid draw loop should reuse the hovered perk index")
	_expect(source.find("func _get_hovered_grid_index(") >= 0, "grid hover index helper should remain wired")
	_expect(source.find("_prewarm_passive_inventory_assets(owner, registry, module_getter)") >= 0, "passive inventory item icons should be prewarmed before the TAB overlay opens")


func _function_body(source: String, signature: String) -> String:
	var start := source.find(signature)
	if start < 0:
		return ""
	var next_func := source.find("\nfunc ", start + signature.length())
	if next_func < 0:
		return source.substr(start)
	return source.substr(start, next_func - start)


func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)
