extends SceneTree

const RuntimePerkRuntimeStateAccess := preload("res://scripts/characters/runtime_perk_runtime_state_access.gd")

var _failures: Array[String] = []


func _init() -> void:
	_verify_accessors()
	_verify_source_contract()

	if _failures.is_empty():
		print("runtime_perk_runtime_state_access_smoke: ok")
		quit(0)
		return
	for failure in _failures:
		push_error(failure)
	quit(1)


func _verify_accessors() -> void:
	var object_value := RefCounted.new()
	var payload_helper := FakePayloadHelper.new()
	var dict_value := {"value": 1}
	var array_value := ["a"]
	var state := FakeRuntimeState.new({
		"object_value": object_value,
		"payload_helper": payload_helper,
		"active_payload": {"active": true},
		"inactive_payload": {"active": false},
		"helper_payload": {"active": false},
		"dict_value": dict_value,
		"array_value": array_value,
		"int_value": 7,
		"float_value": 0.35,
		"bool_value": true,
		"string_value": "ready",
		"string_from_int": 12,
		"wrong_object": {"not": "object"},
		"wrong_dict": object_value,
		"wrong_array": {"not": "array"},
	})

	_expect(RuntimePerkRuntimeStateAccess.get_object(state, "object_value") == object_value, "object accessor should return object properties")
	_expect(RuntimePerkRuntimeStateAccess.get_object(state, "missing") == null, "object accessor should reject missing properties")
	_expect(RuntimePerkRuntimeStateAccess.get_object(state, "wrong_object") == null, "object accessor should reject non-object properties")
	_expect(RuntimePerkRuntimeStateAccess.get_object(null, "object_value") == null, "object accessor should reject null runtime state")
	_expect(RuntimePerkRuntimeStateAccess.get_dict(state, "dict_value") == dict_value, "dict accessor should return dictionary properties")
	_expect(RuntimePerkRuntimeStateAccess.get_dict(state, "wrong_dict").is_empty(), "dict accessor should reject non-dictionary properties")
	_expect(RuntimePerkRuntimeStateAccess.get_dict(null, "dict_value").is_empty(), "dict accessor should reject null runtime state")
	_expect(RuntimePerkRuntimeStateAccess.get_array(state, "array_value") == array_value, "array accessor should return array properties")
	_expect(RuntimePerkRuntimeStateAccess.get_array(state, "wrong_array").is_empty(), "array accessor should reject non-array properties")
	_expect(RuntimePerkRuntimeStateAccess.get_array(null, "array_value").is_empty(), "array accessor should reject null runtime state")
	_expect(RuntimePerkRuntimeStateAccess.get_int(state, "int_value") == 7, "int accessor should cast runtime-state properties")
	_expect(RuntimePerkRuntimeStateAccess.get_int(state, "missing_int") == 0, "int accessor should default missing properties to zero")
	_expect(RuntimePerkRuntimeStateAccess.get_int(null, "int_value") == 0, "int accessor should default null runtime state to zero")
	_expect(absf(RuntimePerkRuntimeStateAccess.get_float(state, "float_value") - 0.35) < 0.001, "float accessor should cast runtime-state properties")
	_expect(RuntimePerkRuntimeStateAccess.get_float(null, "float_value") == 0.0, "float accessor should default null runtime state to zero")
	_expect(absf(RuntimePerkRuntimeStateAccess.get_float(null, "float_value", 1.25) - 1.25) < 0.001, "float accessor should preserve explicit null-state fallbacks")
	_expect(absf(RuntimePerkRuntimeStateAccess.get_float(state, "missing_float", 1.5) - 1.5) < 0.001, "float accessor should preserve explicit missing-property fallbacks")
	_expect(RuntimePerkRuntimeStateAccess.get_bool(state, "bool_value"), "bool accessor should cast runtime-state properties")
	_expect(not RuntimePerkRuntimeStateAccess.get_bool(state, "missing_bool"), "bool accessor should default missing properties to false")
	_expect(not RuntimePerkRuntimeStateAccess.get_bool(null, "bool_value"), "bool accessor should default null runtime state to false")
	_expect(RuntimePerkRuntimeStateAccess.get_string(state, "string_value") == "ready", "string accessor should return runtime-state text")
	_expect(RuntimePerkRuntimeStateAccess.get_string(state, "string_from_int") == "12", "string accessor should preserve str() casting behavior")
	_expect(RuntimePerkRuntimeStateAccess.get_string(state, "missing_string") == "", "string accessor should default missing properties to empty text")
	_expect(RuntimePerkRuntimeStateAccess.get_string(null, "string_value") == "", "string accessor should default null runtime state to empty text")
	_expect(RuntimePerkRuntimeStateAccess.is_payload_active(state, "active_payload"), "payload active query should accept active payload flags")
	_expect(not RuntimePerkRuntimeStateAccess.is_payload_active(state, "inactive_payload"), "payload active query should reject inactive payload flags")
	_expect(not RuntimePerkRuntimeStateAccess.is_payload_active(null, "active_payload"), "payload active query should reject null runtime state")
	_expect(RuntimePerkRuntimeStateAccess.is_payload_active(state, "helper_payload", "payload_helper"), "payload active query should prefer helper is_active results")

	var callback := RuntimePerkRuntimeStateAccess.build_callable(state, "_callback_value")
	_expect(callback.is_valid(), "callable builder should return valid runtime-state methods")
	_expect(str(callback.call()) == "ok", "callable builder should bind the runtime-state receiver")
	_expect(not RuntimePerkRuntimeStateAccess.build_callable(state, "_missing").is_valid(), "callable builder should reject missing methods")
	_expect(not RuntimePerkRuntimeStateAccess.build_callable(null, "_callback_value").is_valid(), "callable builder should reject null runtime state")
	var fallback := Callable(self, "_fallback_value")
	_expect(str(RuntimePerkRuntimeStateAccess.build_callable(state, "_missing", fallback).call()) == "fallback", "callable builder should return fallback for missing methods")
	_expect(str(RuntimePerkRuntimeStateAccess.build_callable(null, "_callback_value", fallback).call()) == "fallback", "callable builder should return fallback for null runtime state")
	var method_dict: Dictionary = RuntimePerkRuntimeStateAccess.call_dict(state, "_dict_value")
	_expect(int(_get_dict(method_dict.get("nested", {})).get("value", 0)) == 2, "dict method caller should return dictionary payloads")
	_get_dict(method_dict.get("nested", {}))["value"] = 99
	_expect(int(_get_dict(state.method_dict.get("nested", {})).get("value", 0)) == 2, "dict method caller should deep-copy dictionary payloads by default")
	_expect(RuntimePerkRuntimeStateAccess.call_dict(state, "_missing_dict").is_empty(), "dict method caller should reject missing methods")
	_expect(RuntimePerkRuntimeStateAccess.call_dict(null, "_dict_value").is_empty(), "dict method caller should reject null sources")
	_expect(RuntimePerkRuntimeStateAccess.call_object(state, "_object_value") == object_value, "object method caller should return object payloads")
	_expect(RuntimePerkRuntimeStateAccess.call_object(state, "_missing_object") == null, "object method caller should reject missing methods")
	_expect(RuntimePerkRuntimeStateAccess.call_object(null, "_object_value", [], object_value) == object_value, "object method caller should preserve explicit fallbacks")
	_expect(RuntimePerkRuntimeStateAccess.call_string(state, "_string_value") == "method-ready", "string method caller should cast method results")
	_expect(RuntimePerkRuntimeStateAccess.call_string(null, "_string_value") == "", "string method caller should reject null sources")
	_expect(RuntimePerkRuntimeStateAccess.call_string(null, "_string_value", [], "fallback-text") == "fallback-text", "string method caller should preserve explicit fallbacks")
	_expect(RuntimePerkRuntimeStateAccess.call_int(state, "_int_value") == 8, "int method caller should cast method results")
	_expect(RuntimePerkRuntimeStateAccess.call_int(null, "_int_value") == 0, "int method caller should reject null sources")
	_expect(RuntimePerkRuntimeStateAccess.call_int(null, "_int_value", [], 12) == 12, "int method caller should preserve explicit fallbacks")
	_expect(absf(RuntimePerkRuntimeStateAccess.call_float(state, "_float_value") - 0.42) < 0.001, "float method caller should cast method results")
	_expect(absf(RuntimePerkRuntimeStateAccess.call_float(null, "_float_value", [], 1.0) - 1.0) < 0.001, "float method caller should preserve explicit fallbacks")
	_expect(RuntimePerkRuntimeStateAccess.call_bool(state, "_bool_value"), "bool method caller should cast method results")
	_expect(not RuntimePerkRuntimeStateAccess.call_bool(null, "_bool_value"), "bool method caller should reject null sources")
	_expect(RuntimePerkRuntimeStateAccess.call_bool(null, "_bool_value", [], true), "bool method caller should preserve explicit fallbacks")


func _verify_source_contract() -> void:
	var instant_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_instant_choice_flow.gd")
	var snapshot_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_snapshot_builder.gd")
	var starpoint_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_starpoint_absorption.gd")
	var collection_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_starpoint_collection_flow.gd")
	var gold_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_gold_award_flow.gd")
	var gold_awards_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_gold_awards.gd")
	var flight_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_active_unlock_flight.gd")
	var showcase_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_unlock_showcase.gd")
	var effective_levels_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_effective_levels.gd")
	var level_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_level_side_effects.gd")
	var opening_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_opening.gd")
	var choice_layout_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_layout.gd")
	var selection_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_selection.gd")
	var feedback_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_feedback.gd")
	var dynamic_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_dynamic_effects.gd")
	var open_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_open_flow.gd")
	var completion_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_completion.gd")
	var finish_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_finish_flow.gd")
	var standard_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_standard_path.gd")
	var apply_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_apply_flow.gd")
	var unlock_apply_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_unlock_choice_apply.gd")
	var showcase_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_unlock_showcase_flow.gd")
	var debug_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_debug_grants.gd")
	var swap_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_unlock_swap_flow.gd")
	var swap_layout_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_unlock_swap_layout.gd")
	var confirm_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_confirm_flow.gd")
	var update_flow_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_update_flow.gd")
	var gamepad_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_gamepad_navigation.gd")
	var choice_audio_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_choice_audio.gd")
	var effective_query_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_effective_stat_query_surface.gd")
	var owner_sync_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_owner_sync_flow.gd")
	var skill_pause_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_skill_cooldown_pause.gd")
	var resume_safety_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_resume_safety.gd")
	var reset_source := FileAccess.get_file_as_string("res://scripts/characters/runtime_perk_reset_state.gd")
	_expect(instant_source.find("RuntimePerkRuntimeStateAccess") >= 0, "instant choice flow should preload runtime-state access helper")
	_expect(snapshot_source.find("RuntimePerkRuntimeStateAccess") >= 0, "snapshot builder should preload runtime-state access helper")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess") >= 0, "starpoint absorption should preload runtime-state access helper")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess") >= 0, "starpoint collection flow should preload runtime-state access helper")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess") >= 0, "gold award flow should preload runtime-state access helper")
	_expect(gold_awards_source.find("RuntimePerkRuntimeStateAccess") >= 0, "gold award payload helper should preload runtime-state access helper")
	_expect(flight_source.find("RuntimePerkRuntimeStateAccess") >= 0, "active unlock flight should preload runtime-state access helper")
	_expect(showcase_source.find("RuntimePerkRuntimeStateAccess") >= 0, "unlock showcase should preload runtime-state access helper")
	_expect(effective_levels_source.find("RuntimePerkRuntimeStateAccess") >= 0, "effective levels should preload runtime-state access helper")
	_expect(level_source.find("RuntimePerkRuntimeStateAccess") >= 0, "level side effects should preload runtime-state access helper")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice opening should preload runtime-state access helper")
	_expect(choice_layout_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice layout should preload runtime-state access helper")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice selection should preload runtime-state access helper")
	_expect(feedback_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice feedback should preload runtime-state access helper")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess") >= 0, "dynamic effects should preload runtime-state access helper")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice open flow should preload runtime-state access helper")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice completion should preload runtime-state access helper")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice finish flow should preload runtime-state access helper")
	_expect(standard_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice standard path should preload runtime-state access helper")
	_expect(apply_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice apply flow should preload runtime-state access helper")
	_expect(unlock_apply_source.find("RuntimePerkRuntimeStateAccess") >= 0, "unlock choice apply should preload runtime-state access helper")
	_expect(showcase_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "unlock showcase flow should preload runtime-state access helper")
	_expect(debug_source.find("RuntimePerkRuntimeStateAccess") >= 0, "debug grants should preload runtime-state access helper")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "unlock swap flow should preload runtime-state access helper")
	_expect(swap_layout_source.find("RuntimePerkRuntimeStateAccess") >= 0, "unlock swap layout should preload runtime-state access helper")
	_expect(confirm_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice confirm flow should preload runtime-state access helper")
	_expect(update_flow_source.find("RuntimePerkRuntimeStateAccess") >= 0, "update flow should preload runtime-state access helper")
	_expect(gamepad_source.find("RuntimePerkRuntimeStateAccess") >= 0, "gamepad navigation should preload runtime-state access helper")
	_expect(choice_audio_source.find("RuntimePerkRuntimeStateAccess") >= 0, "choice audio should preload runtime-state access helper")
	_expect(effective_query_source.find("RuntimePerkRuntimeStateAccess") >= 0, "effective stat query surface should preload runtime-state access helper")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess") >= 0, "owner sync flow should preload runtime-state access helper")
	_expect(skill_pause_source.find("RuntimePerkRuntimeStateAccess") >= 0, "skill cooldown pause should preload runtime-state access helper")
	_expect(resume_safety_source.find("RuntimePerkRuntimeStateAccess") >= 0, "resume safety should preload runtime-state access helper")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess") >= 0, "reset state should preload runtime-state access helper")
	_expect(instant_source.find("func _get_runtime_state_object(") < 0, "instant choice flow should not keep local object accessor")
	_expect(instant_source.find("func _get_runtime_state_dict(") < 0, "instant choice flow should not keep local dict accessor")
	_expect(instant_source.find("func _build_runtime_state_get_instance(") < 0, "instant choice flow should not keep local runtime-state callable builder")
	_expect(snapshot_source.find("func _get_runtime_state_object(") < 0, "snapshot builder should not keep local object accessor")
	_expect(snapshot_source.find("func _call_dict(") < 0, "snapshot builder should not keep local object-method dict caller")
	_expect(snapshot_source.find("func _call_int(") < 0, "snapshot builder should not keep local object-method int caller")
	_expect(snapshot_source.find("func _call_bool(") < 0, "snapshot builder should not keep local object-method bool caller")
	_expect(starpoint_source.find("func _get_runtime_state_object(") < 0, "starpoint absorption should not keep local object accessor")
	_expect(starpoint_source.find("func _get_runtime_state_starpoint_absorption(") < 0, "starpoint absorption should not keep a local runtime-state facade accessor")
	_expect(starpoint_source.find("func _call_bool(") < 0, "starpoint absorption should not keep local object-method bool caller")
	_expect(starpoint_source.find("runtime_state.get(") < 0, "starpoint absorption should not read runtime-state properties directly")
	_expect(collection_source.find("func _get_runtime_state_object(") < 0, "starpoint collection flow should not keep local object accessor")
	_expect(collection_source.find("runtime_state.get(") < 0, "starpoint collection flow should not read runtime-state properties directly")
	_expect(gold_source.find("func _get_runtime_state_object(") < 0, "gold award flow should not keep local object accessor")
	_expect(gold_source.find("runtime_state.get(") < 0, "gold award flow should not read runtime-state properties directly")
	_expect(gold_source.find("func _get_gold_from_perks(") < 0, "gold award flow should not keep a local stored-gold accessor")
	_expect(gold_source.find("func _is_viper_ignition_aura_active(") < 0, "gold award flow should not keep a local Ignition Aura accessor")
	_expect(gold_source.find("func _get_instance_from_runtime_state(") < 0, "gold award flow should not keep local runtime-state get-instance caller")
	_expect(gold_awards_source.find("runtime_state.get(") < 0, "gold award payload helper should not read runtime-state properties directly")
	_expect(flight_source.find("func _get_runtime_state_dict(") < 0, "active unlock flight should not keep local dict accessor")
	_expect(flight_source.find("runtime_state.get(") < 0, "active unlock flight should not read runtime-state properties directly")
	_expect(showcase_source.find("func _get_runtime_state_dict(") < 0, "unlock showcase should not keep local dict accessor")
	_expect(showcase_source.find("runtime_state.get(") < 0, "unlock showcase should not read runtime-state properties directly")
	_expect(effective_levels_source.find("runtime_state.get(") < 0, "effective levels should not read runtime-state properties directly")
	_expect(level_source.find("func _get_runtime_state_object(") < 0, "level side effects should not keep local object accessor")
	_expect(level_source.find("func _build_runtime_state_callable(") < 0, "level side effects should not keep local callable builder")
	_expect(opening_source.find("func _get_runtime_state_object(") < 0, "choice opening should not keep local object accessor")
	_expect(opening_source.find("runtime_state.get(") < 0, "choice opening should not read runtime-state properties directly")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.call_bool(runtime_state, \"has_pending_unlock_swap\")") >= 0, "choice opening should use shared object-method bool caller for pending-swap checks")
	_expect(opening_source.find("func _has_runtime_pending_swap(") < 0, "choice opening should not keep local pending-swap facade logic")
	_expect(choice_layout_source.find("runtime_state.get(") < 0, "choice layout should not read runtime-state properties directly")
	_expect(selection_source.find("func _get_runtime_state_object(") < 0, "choice selection should not keep local object accessor")
	_expect(selection_source.find("runtime_state.get(") < 0, "choice selection should not read runtime-state properties directly")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.is_payload_active(runtime_state, \"choice_flight_effect\", \"_active_unlock_flight\")") >= 0, "choice selection should use shared flight payload active query")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.is_payload_active(runtime_state, \"unlock_showcase\", \"_unlock_showcase_controller\")") >= 0, "choice selection should use shared showcase payload active query")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.call_bool(runtime_state, \"has_pending_unlock_swap\")") >= 0, "choice selection should use shared object-method bool caller for pending-swap checks")
	_expect(selection_source.find("func _has_runtime_pending_swap(") < 0, "choice selection should not keep local pending-swap facade logic")
	_expect(selection_source.find("func _is_runtime_payload_active(") < 0, "choice selection should not keep local payload active facade logic")
	_expect(feedback_source.find("runtime_state.get(") < 0, "choice feedback should not read runtime-state properties directly")
	_expect(feedback_source.find("RuntimePerkRuntimeStateAccess.call_bool(runtime_state, \"has_pending_unlock_swap\")") >= 0, "choice feedback should use shared object-method bool caller for pending-swap checks")
	_expect(feedback_source.find("func _has_pending_unlock_swap_from_runtime_state(") < 0, "choice feedback should not keep a local pending-swap method caller")
	_expect(dynamic_source.find("func _get_runtime_state_object(") < 0, "dynamic effects should not keep local object accessor")
	_expect(open_flow_source.find("func _get_runtime_state_object(") < 0, "choice open flow should not keep local object accessor")
	_expect(open_flow_source.find("runtime_state.get(") < 0, "choice open flow should not read runtime-state properties directly")
	_expect(completion_source.find("runtime_state.get(") < 0, "choice completion should not read runtime-state properties directly")
	_expect(finish_flow_source.find("func _get_runtime_state_object(") < 0, "choice finish flow should not keep local object accessor")
	_expect(finish_flow_source.find("func _get_runtime_state_dict(") < 0, "choice finish flow should not keep local runtime-state dict accessor")
	_expect(finish_flow_source.find("runtime_state.get(") < 0, "choice finish flow should not read runtime-state properties directly")
	_expect(standard_source.find("runtime_state.get(") < 0, "choice standard path should not read runtime-state properties directly")
	_expect(apply_flow_source.find("func _get_runtime_state_object(") < 0, "choice apply flow should not keep local object accessor")
	_expect(apply_flow_source.find("func _get_runtime_state_dict(") < 0, "choice apply flow should not keep local runtime-state dict accessor")
	_expect(apply_flow_source.find("func _get_runtime_state_int(") < 0, "choice apply flow should not keep local runtime-state int accessor")
	_expect(unlock_apply_source.find("func _get_runtime_state_object(") < 0, "unlock choice apply should not keep local object accessor")
	_expect(unlock_apply_source.find("func _get_runtime_state_dict(") < 0, "unlock choice apply should not keep local runtime-state dict accessor")
	_expect(showcase_flow_source.find("func _get_runtime_state_object(") < 0, "unlock showcase flow should not keep local object accessor")
	_expect(showcase_flow_source.find("func _get_runtime_state_dict(") < 0, "unlock showcase flow should not keep local runtime-state dict accessor")
	_expect(debug_source.find("func _get_runtime_state_object(") < 0, "debug grants should not keep local object accessor")
	_expect(debug_source.find("func _get_runtime_state_dict(") < 0, "debug grants should not keep local runtime-state dict accessor")
	_expect(debug_source.find("runtime_state.get(") < 0, "debug grants should not read runtime-state properties directly")
	_expect(swap_flow_source.find("func _get_runtime_state_object(") < 0, "unlock swap flow should not keep local object accessor")
	_expect(swap_flow_source.find("func _get_runtime_state_dict(") < 0, "unlock swap flow should not keep local runtime-state dict accessor")
	_expect(swap_flow_source.find("func _get_runtime_state_int(") < 0, "unlock swap flow should not keep local runtime-state int accessor")
	_expect(swap_flow_source.find("func _get_runtime_state_float(") < 0, "unlock swap flow should not keep local runtime-state float accessor")
	_expect(swap_flow_source.find("runtime_state.get(") < 0, "unlock swap flow should not read runtime-state properties directly")
	_expect(confirm_flow_source.find("func _get_runtime_state_object(") < 0, "choice confirm flow should not keep local object accessor")
	_expect(confirm_flow_source.find("func _get_runtime_state_dict(") < 0, "choice confirm flow should not keep local runtime-state dict accessor")
	_expect(confirm_flow_source.find("func _get_runtime_state_array(") < 0, "choice confirm flow should not keep local runtime-state array accessor")
	_expect(confirm_flow_source.find("func _get_runtime_state_int(") < 0, "choice confirm flow should not keep local runtime-state int accessor")
	_expect(update_flow_source.find("func _get_runtime_state_object(") < 0, "update flow should not keep local object accessor")
	_expect(update_flow_source.find("func _get_runtime_state_dict(") < 0, "update flow should not keep local runtime-state dict accessor")
	_expect(update_flow_source.find("func _get_runtime_state_array(") < 0, "update flow should not keep local runtime-state array accessor")
	_expect(update_flow_source.find("func _get_runtime_state_int(") < 0, "update flow should not keep local runtime-state int accessor")
	_expect(update_flow_source.find("func _get_runtime_state_float(") < 0, "update flow should not keep local runtime-state float accessor")
	_expect(update_flow_source.find("func _get_runtime_state_bool(") < 0, "update flow should not keep local runtime-state bool accessor")
	_expect(update_flow_source.find("func _get_runtime_state_string(") < 0, "update flow should not keep local runtime-state string accessor")
	_expect(update_flow_source.find("func _get_array(") < 0, "update flow should not keep a dead local array wrapper after shared accessor migration")
	_expect(update_flow_source.find("func _get_dict(") < 0, "update flow should not keep a dead local dict wrapper after shared accessor migration")
	_expect(gamepad_source.find("func _get_runtime_state_int(") < 0, "gamepad navigation should not keep local runtime-state int accessor")
	_expect(choice_audio_source.find("func _build_runtime_state_get_instance(") < 0, "choice audio should not keep local get-instance callback builder")
	_expect(swap_flow_source.find("func _build_runtime_state_sync_owner(") < 0, "unlock swap flow should not keep local sync-owner callback builder")
	_expect(swap_layout_source.find("runtime_state.get(") < 0, "unlock swap layout should not read runtime-state properties directly")
	_expect(swap_layout_source.find("func _get_runtime_pending_swap(") < 0, "unlock swap layout should not keep a local pending-swap accessor")
	_expect(effective_query_source.find("func _build_runtime_state_get_instance(") < 0, "effective stat query surface should not keep local get-instance callback builder")
	_expect(effective_query_source.find("func _get_state_object(") < 0, "effective stat query surface should not keep local runtime-state object accessor")
	_expect(effective_query_source.find("runtime_state.get(") < 0, "effective stat query surface should not read runtime-state properties directly")
	_expect(owner_sync_source.find("func _build_runtime_state_get_instance(") < 0, "owner sync flow should not keep local get-instance callback builder")
	_expect(owner_sync_source.find("func _get_state_dict(") < 0, "owner sync flow should not keep local runtime-state dict accessor")
	_expect(owner_sync_source.find("func _get_state_int(") < 0, "owner sync flow should not keep local runtime-state int accessor")
	_expect(owner_sync_source.find("func _get_state_bool(") < 0, "owner sync flow should not keep local runtime-state bool accessor")
	_expect(owner_sync_source.find("func _get_state_object(") < 0, "owner sync flow should not keep local runtime-state object accessor")
	_expect(owner_sync_source.find("func _call_state_dict(") < 0, "owner sync flow should not keep local runtime-state dict method caller")
	_expect(owner_sync_source.find("func _call_state_int(") < 0, "owner sync flow should not keep local runtime-state int method caller")
	_expect(owner_sync_source.find("func _call_state_float(") < 0, "owner sync flow should not keep local runtime-state float method caller")
	_expect(owner_sync_source.find("func _call_state_bool(") < 0, "owner sync flow should not keep local runtime-state bool method caller")
	_expect(owner_sync_source.find("func _call_state_value(") < 0, "owner sync flow should not keep local runtime-state generic method caller")
	_expect(skill_pause_source.find("func _get_state_object(") < 0, "skill cooldown pause should not keep local runtime-state object accessor")
	_expect(resume_safety_source.find("func _get_state_object(") < 0, "resume safety should not keep local runtime-state object accessor")
	_expect(reset_source.find("func _get_state_object(") < 0, "reset state should not keep local runtime-state object accessor")
	_expect(reset_source.find("func _get_state_dict(") < 0, "reset state should not keep local runtime-state dict accessor")
	_expect(reset_source.find("runtime_state.get(") < 0, "reset state should not read runtime-state properties directly")
	_expect(instant_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_get_instance\")") >= 0, "instant choice flow should use shared get-instance callable builder")
	_expect(instant_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_apply_dimension_gate\")") >= 0, "instant choice flow should use shared spawn-intro callable builder")
	_expect(instant_source.find("Callable(runtime_state, \"") < 0, "instant choice flow should not build runtime-state callbacks directly")
	_expect(snapshot_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_deferred_instants\")") >= 0, "snapshot builder should use shared helper for deferred instants")
	_expect(snapshot_source.find("RuntimePerkRuntimeStateAccess.call_dict(state, \"get_effective_runtime_skill_levels\")") >= 0, "snapshot builder should use shared object-method dict caller")
	_expect(snapshot_source.find("RuntimePerkRuntimeStateAccess.call_int(state, \"get_viper_ignition_aura_level_bonus\")") >= 0, "snapshot builder should use shared object-method int caller")
	_expect(snapshot_source.find("RuntimePerkRuntimeStateAccess.call_bool(deferred_instants, \"has_pending_dimension_gate\")") >= 0, "snapshot builder should use shared object-method bool caller")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_starpoint_absorption\")") >= 0, "starpoint absorption should use shared helper for its runtime-state facade")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "starpoint absorption should use shared pending-choice lookup")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"starpoint_for_skills\")") >= 0, "starpoint absorption should use shared starpoint lookup")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess.call_bool(helper, \"is_active\")") >= 0, "starpoint absorption should use shared object-method bool caller")
	_expect(starpoint_source.find("RuntimePerkRuntimeStateAccess.call_dict(") >= 0 and starpoint_source.find("build_layout_state_from_runtime_state") >= 0, "starpoint absorption should use shared object-method dict caller for flight layout")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_choice_feedback\")") >= 0, "starpoint collection flow should use shared helper for feedback lookup")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"starpoint_for_skills\")") >= 0, "starpoint collection flow should use shared starpoint lookup")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "starpoint collection flow should use shared pending-choice lookup")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "starpoint collection flow should use shared choice-active lookup")
	_expect(collection_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and collection_source.find("\"open_next_choice\"") >= 0, "starpoint collection flow should use shared callback builder")
	_expect(collection_source.find("Callable(runtime_state, \"") < 0, "starpoint collection flow should not build runtime-state callbacks directly")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_sync_owner\")") >= 0, "gold award flow should use shared sync-owner callable builder")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"gold_from_perks\")") >= 0, "gold award flow should use shared stored-gold lookup")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"item_gold_gain_multiplier\")") >= 0, "gold award flow should use shared item-gold multiplier lookup")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"viper_ignition_aura_active\")") >= 0, "gold award flow should use shared Ignition Aura lookup")
	_expect(gold_source.find("RuntimePerkRuntimeStateAccess.call_object(runtime_state, \"_get_instance\", [registry, \"smasher_combo_state\"]") >= 0, "gold award flow should use shared object-method caller for combo-state lookup")
	_expect(gold_awards_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"gold_from_perks\")") >= 0, "gold award payload helper should use shared stored-gold lookup")
	_expect(gold_awards_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"item_gold_gain_multiplier\")") >= 0, "gold award payload helper should use shared item-gold multiplier lookup")
	_expect(gold_awards_source.find("RuntimePerkRuntimeStateAccess.get_string(runtime_state, \"feedback_text\")") >= 0, "gold award payload helper should use shared feedback text lookup")
	_expect(gold_awards_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "gold award payload helper should use shared feedback timer lookup")
	_expect(flight_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"choice_flight_effect\")") >= 0, "active unlock flight should use shared helper for effect active query")
	_expect(showcase_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"unlock_showcase\")") >= 0, "unlock showcase should use shared helper for active query")
	_expect(effective_levels_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"viper_ignition_aura_active\")") >= 0, "effective levels should use shared Viper active lookup")
	_expect(effective_levels_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"viper_ignition_aura_owner_sync_dirty\")") >= 0, "effective levels should use shared Viper dirty lookup")
	_expect(effective_levels_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"item_perk_level_bonus\")") >= 0, "effective levels should use shared item bonus lookup")
	_expect(level_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_refresh_mythic_runtime_perk_consumers\")") >= 0, "level side effects should use shared mythic-refresh callable builder")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "choice opening should use shared choice-active lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice opening should use shared pending-choice lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"selected_index\")") >= 0, "choice opening should use shared selected-index lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"gamepad_choice_horizontal_latch\")") >= 0, "choice opening should use shared gamepad latch lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"animation_time\")") >= 0, "choice opening should use shared animation-time lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice opening should use shared current-choice lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"current_choice_context\")") >= 0, "choice opening should use shared choice-context lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"current_perk_slot_status\")") >= 0, "choice opening should use shared perk-slot-status lookup")
	_expect(opening_source.find("RuntimePerkRuntimeStateAccess.call_bool(runtime_state, \"has_pending_unlock_swap\")") >= 0, "choice opening should use shared pending-swap method caller")
	_expect(choice_layout_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice layout should use shared current-choice lookup")
	_expect(choice_layout_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"animation_time\")") >= 0, "choice layout should use shared animation-time lookup")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "choice selection should use shared choice-active lookup")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice selection should use shared current-choice lookup")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"selected_index\")") >= 0, "choice selection should use shared selected-index lookup")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.is_payload_active(runtime_state, \"choice_flight_effect\", \"_active_unlock_flight\")") >= 0, "choice selection should use shared flight payload active query")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.is_payload_active(runtime_state, \"unlock_showcase\", \"_unlock_showcase_controller\")") >= 0, "choice selection should use shared showcase payload active query")
	_expect(selection_source.find("RuntimePerkRuntimeStateAccess.call_bool(runtime_state, \"has_pending_unlock_swap\")") >= 0, "choice selection should use shared pending-swap method caller")
	_expect(feedback_source.find("RuntimePerkRuntimeStateAccess.get_string(runtime_state, \"feedback_text\")") >= 0, "choice feedback should use shared feedback text lookup")
	_expect(feedback_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "choice feedback should use shared feedback timer lookup")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_effective_levels\")") >= 0, "dynamic effects should use shared effective-level helper lookup")
	_expect(dynamic_source.find("runtime_state.get(") < 0, "dynamic effects should not read runtime-state properties directly")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and dynamic_source.find("\"_sync_runtime_perk_owner_effects\"") >= 0, "dynamic effects should use shared callback builder")
	_expect(dynamic_source.find("Callable(runtime_state, \"") < 0, "dynamic effects should not build runtime-state callbacks directly")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"viper_ignition_aura_active\")") >= 0, "dynamic effects should use shared Viper active lookup")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"viper_ignition_aura_owner_sync_dirty\")") >= 0, "dynamic effects should use shared Viper dirty lookup")
	_expect(dynamic_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"item_perk_level_bonus\")") >= 0, "dynamic effects should use shared item bonus lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_active_unlock_flight\")") >= 0, "choice open flow should use shared active-unlock helper lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and open_flow_source.find("\"_apply_choice_opening_update\"") >= 0, "choice open flow should use shared callback builder")
	_expect(open_flow_source.find("Callable(runtime_state, \"") < 0, "choice open flow should not build runtime-state callbacks directly")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"choice_flight_effect\")") >= 0, "choice open flow should use shared flight-effect lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"runtime_skill_levels\")") >= 0, "choice open flow should use shared runtime-level lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice open flow should use shared pending-choice lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice open flow should use shared current-choice lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"current_choice_context\")") >= 0, "choice open flow should use shared choice-context lookup")
	_expect(open_flow_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "choice open flow should use shared feedback timer lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"selected_choice_sequence\")") >= 0, "choice completion should use shared selected-choice sequence lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice completion should use shared pending-choice lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice completion should use shared current-choice lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"animation_time\")") >= 0, "choice completion should use shared animation-time lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "choice completion should use shared feedback timer lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "choice completion should use shared choice-active lookup")
	_expect(completion_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"current_choice_context\")") >= 0, "choice completion should use shared current-context lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"runtime_skill_levels\")") >= 0, "choice finish flow should use shared runtime-level lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"current_choice_context\")") >= 0, "choice finish flow should use shared current context lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "choice finish flow should use shared feedback timer lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice finish flow should use shared pending-choice lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"selected_choice_sequence\")") >= 0, "choice finish flow should use shared selected-choice sequence lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "choice finish flow should use shared choice-active lookup")
	_expect(finish_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and finish_flow_source.find("\"open_next_choice\"") >= 0, "choice finish flow should use shared callback builder")
	_expect(finish_flow_source.find("Callable(runtime_state, \"") < 0, "choice finish flow should not build runtime-state callbacks directly")
	_expect(standard_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice standard path should use shared pending-choice lookup")
	_expect(standard_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"starpoint_for_skills\")") >= 0, "choice standard path should use shared starpoint lookup")
	_expect(apply_flow_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_choice_dispatch\")") >= 0, "choice apply flow should use shared dispatch helper lookup")
	_expect(apply_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "choice apply flow should use shared pending-skill count lookup")
	_expect(apply_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and apply_flow_source.find("\"_apply_choice_feedback_result\"") >= 0, "choice apply flow should use shared callback builder")
	_expect(apply_flow_source.find("Callable(runtime_state, \"") < 0, "choice apply flow should not build runtime-state callbacks directly")
	_expect(unlock_apply_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_unlock_swap_flow\")") >= 0, "unlock choice apply should use shared unlock-swap helper lookup")
	_expect(unlock_apply_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and unlock_apply_source.find("\"_apply_unlock_swap_state_update\"") >= 0, "unlock choice apply should use shared callback builder")
	_expect(unlock_apply_source.find("Callable(runtime_state, \"") < 0, "unlock choice apply should not build runtime-state callbacks directly")
	_expect(showcase_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"unlock_showcase\")") >= 0, "unlock showcase flow should use shared showcase-state lookup")
	_expect(showcase_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and showcase_flow_source.find("\"_finish_successful_choice\"") >= 0, "unlock showcase flow should use shared callback builder")
	_expect(showcase_flow_source.find("Callable(runtime_state, \"") < 0, "unlock showcase flow should not build runtime-state callbacks directly")
	_expect(debug_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"runtime_skill_levels\")") >= 0, "debug grants should use shared runtime-level lookup")
	_expect(debug_source.find("RuntimePerkRuntimeStateAccess.get_string(runtime_state, \"last_selected_id\")") >= 0, "debug grants should use shared last-selected fallback lookup")
	_expect(debug_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and debug_source.find("\"_apply_choice_feedback_result\"") >= 0, "debug grants should use shared callback builder")
	_expect(debug_source.find("Callable(runtime_state, \"") < 0, "debug grants should not build runtime-state callbacks directly")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"pending_unlock_swap\")") >= 0, "unlock swap flow should use shared pending-swap lookup")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"unlock_swap_selected_index\")") >= 0, "unlock swap flow should use shared selected-index lookup")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"gamepad_unlock_swap_horizontal_latch\")") >= 0, "unlock swap flow should use shared gamepad latch lookup")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "unlock swap flow should use shared feedback timer lookup")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, field_name)") >= 0, "unlock swap flow should clear dictionary fields through shared accessor")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.call_object(runtime_state, \"_get_catalog\"") >= 0, "unlock swap flow should use shared catalog method caller")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.call_string(runtime_state, \"_get_character_type\"") >= 0, "unlock swap flow should use shared character-type method caller")
	_expect(swap_flow_source.find("func _get_catalog_from_runtime_state(") < 0, "unlock swap flow should not keep local catalog method caller")
	_expect(swap_flow_source.find("func _get_character_type_from_runtime_state(") < 0, "unlock swap flow should not keep local character-type method caller")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and swap_flow_source.find("\"_apply_unlock_swap_state_update\"") >= 0, "unlock swap flow should use shared callback builder")
	_expect(swap_flow_source.find("Callable(runtime_state, \"") < 0, "unlock swap flow should not build runtime-state callbacks directly")
	_expect(swap_layout_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"pending_unlock_swap\")") >= 0, "unlock swap layout should use shared pending-swap lookup")
	_expect(confirm_flow_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"current_choices\")") >= 0, "choice confirm flow should use shared current-choice lookup")
	_expect(confirm_flow_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"selected_index\")") >= 0, "choice confirm flow should use shared selected-index lookup")
	_expect(confirm_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and confirm_flow_source.find("\"_finish_or_open_unlock_showcase\"") >= 0, "choice confirm flow should use shared callback builder")
	_expect(confirm_flow_source.find("Callable(runtime_state, \"") < 0, "choice confirm flow should not build runtime-state callbacks directly")
	_expect(update_flow_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, \"particles\")") >= 0, "update flow should use shared particles lookup")
	_expect(update_flow_source.find("RuntimePerkRuntimeStateAccess.get_string(runtime_state, \"feedback_text\")") >= 0, "update flow should use shared feedback text lookup")
	_expect(update_flow_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "update flow should use shared choice-active lookup")
	_expect(update_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0 and update_flow_source.find("\"is_choice_flight_active\"") >= 0, "update flow should use shared callback builder for active branch queries")
	_expect(update_flow_source.find("Callable(runtime_state, \"") < 0, "update flow should not build runtime-state callbacks directly")
	_expect(gamepad_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, latch_property)") >= 0, "gamepad navigation should use shared latch lookup")
	_expect(choice_audio_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_get_instance\")") >= 0, "choice audio should use shared get-instance callback builder")
	_expect(swap_flow_source.find("RuntimePerkRuntimeStateAccess.build_callable(runtime_state, \"_sync_owner\")") >= 0, "unlock swap flow should use shared sync-owner callback builder")
	_expect(effective_query_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0, "effective stat query surface should use shared get-instance callback builder")
	_expect(effective_query_source.find("RuntimePerkRuntimeStateAccess.call_float(effective_levels, method_name, args, fallback)") >= 0, "effective stat query surface should use shared float method caller")
	_expect(effective_query_source.find("effective_levels.callv(") < 0, "effective stat query surface should not keep direct effective-level callv")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.build_callable(") >= 0, "owner sync flow should use shared get-instance callback builder")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_owner_projection\")") >= 0, "owner sync flow should use shared owner-projection lookup")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"runtime_skill_levels\")") >= 0, "owner sync flow should use shared runtime-level lookup")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.call_dict(runtime_state, \"get_effective_runtime_skill_levels\")") >= 0, "owner sync flow should use shared effective-level method caller")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.call_int(runtime_state, \"get_accessory_slot_bonus\")") >= 0, "owner sync flow should use shared accessory-slot method caller")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.call_float(runtime_state, \"get_player_paddle_size_multiplier\")") >= 0, "owner sync flow should use shared paddle-size multiplier caller")
	_expect(owner_sync_source.find("RuntimePerkRuntimeStateAccess.call_float(") >= 0 and owner_sync_source.find("\"get_player_skill_cooldown_multiplier\"") >= 0, "owner sync flow should use shared cooldown multiplier caller")
	_expect(skill_pause_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_skill_cooldown_pause\")") >= 0, "skill cooldown pause should use shared helper lookup")
	_expect(resume_safety_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_resume_safety\")") >= 0, "resume safety should use shared helper lookup")
	_expect(resume_safety_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_dynamic_effects\")") >= 0, "resume safety should use shared dynamic-effects lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_skill_cooldown_pause\")") >= 0, "reset state should use shared cooldown helper lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_object(runtime_state, \"_resume_safety\")") >= 0, "reset state should use shared resume-safety lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, \"choice_flight_effect\")") >= 0, "reset state should use shared flight payload lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_int(runtime_state, \"pending_skill_choices\")") >= 0, "reset state should use shared pending-choice lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_bool(runtime_state, \"choice_active\")") >= 0, "reset state should use shared choice-active lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_float(runtime_state, \"feedback_timer\")") >= 0, "reset state should use shared feedback timer lookup")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_array(runtime_state, field_name)") >= 0, "reset state should clear array fields through shared accessor")
	_expect(reset_source.find("RuntimePerkRuntimeStateAccess.get_dict(runtime_state, field_name)") >= 0, "reset state should clear dictionary fields through shared accessor")


func _fallback_value() -> String:
	return "fallback"


func _get_dict(value: Variant) -> Dictionary:
	if value is Dictionary:
		return value
	return {}


func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)


class FakeRuntimeState:
	extends RefCounted

	var data: Dictionary = {}
	var method_dict := {"nested": {"value": 2}}

	func _init(source: Dictionary) -> void:
		data = source

	func _get(property: StringName) -> Variant:
		return data.get(str(property), null)

	func _callback_value() -> String:
		return "ok"

	func _dict_value() -> Dictionary:
		return method_dict

	func _object_value() -> Object:
		return data.get("object_value", null)

	func _string_value() -> String:
		return "method-ready"

	func _int_value() -> int:
		return 8

	func _float_value() -> float:
		return 0.42

	func _bool_value() -> bool:
		return true


class FakePayloadHelper:
	extends RefCounted

	func is_active(_payload: Dictionary) -> bool:
		return true
