extends RefCounted

const BLACKSMITH_PLAYER_IDLE_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_idle_back_autosprite_v3_custom_4x2_160_clean.png"
const BLACKSMITH_PLAYER_WALK_LEFT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_sprint_dash_left_25deg_custom_v3_selected_mirror_from_right_4x2_160_clean.png"
const BLACKSMITH_PLAYER_WALK_RIGHT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_sprint_dash_right_25deg_custom_v3_selected_4x2_160_clean.png"
const BLACKSMITH_PLAYER_DASH_LEFT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_dash_slide_tackle_rear_left_hold_v4_mirror_from_right_4x2_160_clean.png"
const BLACKSMITH_PLAYER_DASH_RIGHT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_dash_slide_tackle_rear_right_hold_v4_4x2_160_clean.png"
const BLACKSMITH_PLAYER_ATTACK_LEFT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_attack_left_shield_bash_autosprite_v2_16f_4x4_160_clean.png"
const BLACKSMITH_PLAYER_ATTACK_RIGHT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_attack_right_hammer_smash_autosprite_v4_16f_4x4_160_clean.png"
const BLACKSMITH_PLAYER_THOR_SHIELD_DEPLOY_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_thor_shield_overhead_autosprite_v3_hybrid_4x4_160_clean.png"
const BLACKSMITH_THOR_SHIELD_STRETCH_TEXTURE_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_thor_shield_stretch_imagegen_v1.png"
const BLACKSMITH_PLAYER_VICTORY_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_victory_rear_autosprite_v1_49f_7x7_160_clean.png"
const BLACKSMITH_PLAYER_DEFEAT_SHEET_PATH := "res://assets/sprites/characters/blacksmith/blacksmith_defeat_rear_autosprite_v1_49f_7x7_160_clean.png"
