extends RefCounted

const DEFAULT_VALUES: Dictionary = {
	"ball_pos": Vector2.ZERO,
	"ball_pos_prev": Vector2.ZERO,
	"ball_interp_reset_requested": false,
	"ball_interp_last_physics_usec": 0,
	"ball_render_interpolation_enabled": true,
	"ball_vel": Vector2.ZERO,
	"ball_active": false,
	"skip_ball_motion_step": false,
	"ball_impact_boost": 1.0,
	"stage3_kuromi_ball_hidden": false,
	"ball_boost_decay_rate": 0.975,
	"ball_min_boost": 0.70,
	"rally_speed_cap_bonus": 0.0,
	"player_collision_cooldown": 0.0,
	"boss_collision_cooldown": 0.0,
	"vertical_bounce_count": 0,
	"ball_spin_strength": 0.0,
	"ball_spin_direction": 0,
	"drive_ball_active": false,
	"drive_hit_boss": false,
	"drive_speed_increase": 0.0,
	"drive_text_timer_frames": 0.0,
	"smasher_wheel_speed_cap": 0.0,
	"gameplay_frame_counter": 0,
	"ball_visual_type": "energy",
	"boost_charging_active": false,
	"poisoned_ball_overlay_active": false,
	"viper_knockback_overlay_active": false,
	"bomb_ball_loaded": false,
	"player_pos": Vector2.ZERO,
	"player_speed": 0.0,
	"player_paddle_width": 155.0,
	"player_paddle_height": 50.0,
	"player_paddle_scale": 1.0,
	"player_paddle_visual_scale_override": -1.0,
	"runtime_paddle_base_width": 155.0,
	"runtime_paddle_base_height": 50.0,
	"runtime_paddle_scale": 1.0,
	"optimus_energy_initialized": false,
	"optimus_energy_ratio": 1.0,
	"optimus_paddle_scale": 1.0,
	"optimus_speed_multiplier": 1.0,
	"optimus_charge_active": false,
	"optimus_charge_hold_seconds": 0.0,
	"optimus_charge_hold_ratio": 0.0,
	"optimus_charge_lock_seconds": 0.0,
	"optimus_charge_movement_locked": false,
	"boss_pos": Vector2.ZERO,
	"boss_pos_prev": Vector2.ZERO,
	"boss_paddle_width": 100.0,
	"boss_hitbox_height": 40.0,
	"boss_interp_last_physics_usec": 0,
	"boss_render_interpolation_enabled": true,
	"boss_vel": 0.0,
	"boss_max_health": 0,
	"boss_current_health": 0,
	"boss_health_damage_units": 0,
	"boss_last_damage_source": "",
	"boss_defeated_by_health": false,
	"current_stage": 1,
	"selected_character_type": "smasher",
	"ai_mode": "champion",
	"starting_dash_tokens": 1,
	"arena_mode_enabled": false,
	"weather_type": "",
	"weather_event_active": false,
	"weather_event_context": {},
	"selected_character_id": "ufo_player",
	"selected_runtime_character_id": "smasher",
	"selected_character_name": "스매셔",
	"active_item_slots": [],
	"equipment_slots": {},
	"passive_item_inventory": [],
	"passive_item_slots": {},
	"equipped_passive_items": {},
	"mythic_item_state": {},
	"baal_boots_equipped": false,
	"baal_boots_active": false,
	"baal_boots_context": {},
	"megingjord_equipped": false,
	"sage_ring_equipped": false,
	"sage_ring_active": false,
	"sage_ring_count": 0,
	"sage_ring_perk_level_bonus": 0,
	"sage_ring_speed_penalty_pct": 0.0,
	"sage_ring_body_penalty_pct": 0.0,
	"sage_ring_speed_multiplier": 1.0,
	"transcendent_crown_equipped": false,
	"transcendent_crown_skill_bonus": 0,
	"transcendent_crown_context": {},
	"smasher_skill_icon_textures": {},
	"viper_skill_icon_textures": {},
	"commando_skill_icon_textures": {},
	"special_gauge": 0.0,
	"special_gauge_max": 500.0,
	"battle_textures": {},
	"player_customization_overlays_enabled": true,
	"player_customization_debug_overlay_enabled": false,
	"player_customization_overlay_slots": {},
	"player_customization_overlay_textures": {},
	"runtime_perk_levels": {},
	"runtime_perk_pending_choices": 0,
	"runtime_perk_starpoints": 0,
	"runtime_perk_gold": 0,
	"runtime_perk_choice_active": false,
	"lingpet_id": "",
	"active_lingpet_id": "",
	"current_lingpet_id": "",
	"lingpet_state": "none",
	"ringpet_state": "none",
	"lingpet_hatch_hits": 0,
	"ringpet_hatch_hits": 0,
	"lingpet_hatch_required_hits": 3,
	"ringpet_hatch_required_hits": 3,
	"lingpet_egg_pos": Vector2.ZERO,
	"lingpet_companion_pos": Vector2.ZERO,
	"ringpet_companion_pos": Vector2.ZERO,
	"lingpet_companion_contact_count": 0,
	"ringpet_companion_contact_count": 0,
	"lingpet_companion_last_contact_pos": Vector2.ZERO,
	"ringpet_companion_last_contact_pos": Vector2.ZERO,
	"lingpet_companion_hit_cooldown": 0.0,
	"ringpet_companion_hit_cooldown": 0.0,
	"lingpet_skill_id": "",
	"ringpet_skill_id": "",
	"lingpet_active_skill_id": "",
	"ringpet_active_skill_id": "",
	"lingpet_active_skill_level": 0,
	"ringpet_active_skill_level": 0,
	"lingpet_active_skill_max_level": 0,
	"ringpet_active_skill_max_level": 0,
	"lingpet_skill_name": "",
	"ringpet_skill_name": "",
	"lingpet_skill_cooldown": 0.0,
	"ringpet_skill_cooldown": 0.0,
	"lingpet_skill_cooldown_duration": 40.0,
	"ringpet_skill_cooldown_duration": 40.0,
	"lingpet_skill_ready": false,
	"ringpet_skill_ready": false,
	"lingpet_skill_last_gain": 0.0,
	"ringpet_skill_last_gain": 0.0,
	"lingpet_skill_trigger_count": 0,
	"ringpet_skill_trigger_count": 0,
	"lingpet_passive_skill_id": "",
	"ringpet_passive_skill_id": "",
	"lingpet_passive_skill_level": 0,
	"ringpet_passive_skill_level": 0,
	"lingpet_passive_skill_max_level": 0,
	"ringpet_passive_skill_max_level": 0,
	"lingpet_passive_skill_name": "",
	"ringpet_passive_skill_name": "",
	"lingpet_passive_skill_description": "",
	"ringpet_passive_skill_description": "",
	"lingpet_passive_skill_icon_path": "",
	"ringpet_passive_skill_icon_path": "",
	"lingpet_effect_text": "",
	"lingpet_owned_pet_ids": [],
	"owned_lingpet_ids": [],
	"owned_ringpet_ids": [],
	"lingpet_collection": {},
	"ringpet_collection": {},
	"owned_lingpets": {},
	"owned_ringpets": {},
	"lingpet_loadouts": {},
	"ringpet_loadouts": {},
	"owned_lingpet_loadouts": {},
	"owned_ringpet_loadouts": {},
	"runtime_accessory_slot_bonus": 0,
	"item_perk_level_bonus": 0,
	"commando_firearm_boss_damage_units_total": 0,
	"commando_firearm_last_damage_units": 0,
	"commando_firearm_last_damage_source": "",
	"commando_bowling_trap_guard_armed": false,
	"commando_bowling_trap_guard_source": "",
	"commando_bowling_trap_guard_knockback_power": 0.0,
	"commando_bowling_trap_guard_stun_frames": 0.0,
	"commando_bowling_trap_guard_restore_speed": 0.0,
	"commando_suicide_drone_ball_boost_active": false,
	"commando_suicide_drone_ball_restore_speed": 0.0,
	"commando_suicide_drone_ball_boosted_speed": 0.0,
}

var values: Dictionary = {}


func _init() -> void:
	reset()


func reset() -> void:
	values.clear()
	for key in DEFAULT_VALUES.keys():
		values[key] = _copy_default(DEFAULT_VALUES[key])


func has_key(key: String) -> bool:
	return DEFAULT_VALUES.has(key)


func get_value(key: String) -> Variant:
	if values.has(key):
		return values[key]
	if DEFAULT_VALUES.has(key):
		return _copy_default(DEFAULT_VALUES[key])
	return null


func set_value(key: String, value: Variant) -> void:
	if DEFAULT_VALUES.has(key):
		values[key] = value


func _copy_default(value: Variant) -> Variant:
	if value is Array:
		var array_value: Array = value
		return array_value.duplicate(true)
	if value is Dictionary:
		var dictionary_value: Dictionary = value
		return dictionary_value.duplicate(true)
	return value
