extends RefCounted

const MODULE_GROUPS := {
	"battle_startup": [
		"battle_scene_config",
		"battle_scene_bootstrap",
		"battle_scene_lifecycle",
		"battle_view_layout",
		"battle_scene_update_driver",
		"battle_scene_update_prewarm_driver",
	],
	"item_runtime": [
		"active_item_runtime",
		"mythic_item_runtime",
		"treasure_hunt_runtime",
	],
	"update_runtime": [
		"battle_frame_flow_controller",
		"battle_frame_flow_deps_builder",
		"battle_scene_actor_update_driver",
		"battle_scene_actor_update_result_applier",
		"battle_scene_player_control_config_builder",
		"battle_scene_item_update_driver",
		"battle_scene_skill_tooltip_driver",
		"battle_scene_runtime_perk_update_driver",
		"battle_scene_scoreboard_update_driver",
		"battle_scene_match_event_driver",
		"battle_scene_boss_health_flow",
		"battle_scene_effects_update_driver",
		"battle_scene_effects_update_result_applier",
		"battle_scene_match_flow_driver",
		"battle_scene_match_reset_result_applier",
		"battle_update_context",
		"serve_flow_controller",
		"boss_ai_state",
		"stage2_boss_skill_state",
		"stage3_boss_skill_state",
		"stage4_map_state",
		"stage4_temple_destruction_event",
		"stage4_moon_event",
		"stage4_bird_event",
		"stage4_brazier_monk_event",
		"stage4_ponk_skill_state",
		"stage5_hongryun_state",
		"stage5_hongryun_fire_machine_event",
		"round_flow_state",
		"match_flow_controller",
		"match_score_event_controller",
		"match_scoreboard_flow_controller",
		"match_round_restart_controller",
		"match_reset_controller",
		"scoreboard_state",
	],
	"ball_runtime": [
		"battle_scene_ball_update_driver",
		"ball_update_controller",
		"ball_update_context",
		"ball_scene_bridge",
		"ball_round_controller",
		"ball_renderer",
		"ball_motion_stepper",
		"ball_physics",
		"ball_effects",
		"ball_intensity",
		"ball_round_state",
		"ball_spin_state",
		"paddle_bounce_state",
		"wall_bounce_controller",
		"paddle_bounce_controller",
		"status_effect_state",
		"laurel_leaf_shield_state",
		"player_movement_state",
		"round_flow_state",
		"smasher_dash_state",
		"orb_hud_state",
		"impact_effects",
		"weather_event_state",
		"runtime_perk_state",
		"actor_animation_state",
		"battle_feedback_state",
	],
	"draw_runtime": [
		"battle_scene_drawer",
		"battle_playfield_scene_drawer",
		"battle_draw_context",
		"stage_runtime_router",
		"stage1_actor_renderer",
		"stage1_pillar_scene_drawer",
		"stage2_actor_renderer",
		"stage2_pillar_background",
		"stage2_pillar_scene_drawer",
		"stage2_boss_skill_hud_renderer",
		"stage3_actor_renderer",
		"stage3_pillar_scene_drawer",
		"stage3_boss_skill_hud_renderer",
		"stage4_actor_renderer",
		"stage4_pillar_scene_drawer",
		"stage4_pillar_background",
		"stage4_ponk_skill_state",
		"stage4_ponk_boss_skill_hud_renderer",
		"stage4_ponk_gauge_hud_renderer",
		"stage5_pillar_scene_drawer",
		"stage5_hongryun_boss_skill_hud_renderer",
		"stage1_pillar_ui_renderer",
		"active_item_hud_renderer",
		"runtime_perk_icon_renderer",
		"runtime_perk_debug_picker",
		"ball_effects_renderer",
		"smasher_skill_feedback_renderer",
		"smasher_skill_orb_renderer",
		"skill_cutin_overlay_host",
		"lingpet_acquire_cutin_overlay_host",
		"lingpet_guardian_enhance_choice_overlay_host",
		"scoreboard_renderer",
		"serve_wait_indicator_renderer",
		"battle_feedback_state",
		"battle_effects_update_controller",
		"impact_effects",
		"impact_effects_renderer",
	],
}


func get_module_group(group_name: String) -> Array:
	return MODULE_GROUPS.get(group_name, []).duplicate()
