# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['pingfighter.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('*.png', '.'), 
        ('*.ttf', '.'), 
        ('*.txt', '.'), 
        ('*.json', '.'), 
        ('*.jpeg', '.'), 
        ('items', 'items'), 
        ('sounds', 'sounds'), 
        ('scenes', 'scenes'),
        ('core', 'core'),
        ('game_logic', 'game_logic'),
        ('entities', 'entities'),
        ('ai', 'ai'),
        ('managers', 'managers'),
        ('network', 'network'),
        ('ui', 'ui'),
        ('config', 'config'),
        ('localization', 'localization'),
        ('achievement', 'achievement'),
        ('replay', 'replay')
    ],
    hiddenimports=[
        'core.events',
        'core.global_manager',
        'core.error_boundary',
        'game_logic.collision',
        'game_logic.physics',
        'game_logic.round_manager',
        'game_logic.stage_features',
        'game_logic.special_items',
        'game_logic.perfect_timing',
        'game_logic.power_smashing',
        'game_logic.special_abilities',
        'game_logic.balance_manager',
        'entities.ball',
        'entities.paddle',
        'entities.entity',
        'ai.boss_ai',
        'ai.boss_skills',
        'ai.ai_difficulty',
        'ai.ml_boss_ai',
        'managers.sound_manager',
        'managers.effects_manager',
        'managers.resource_manager',
        'network.network_manager',
        'network.network_protocol',
        'network.network_connection',
        'ui.menu_system',
        'ui.settings_ui',
        'ui.academy_ui',
        'ui.achievement_ui',
        'ui.network_ui',
        'config.balance_config',
        'config.settings_system',
        'achievement.achievement_manager',
        'achievement.achievement_definitions',
        'replay.replay_manager',
        'replay.replay_viewer'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'test', 'tests'],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PingFighter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 'ball.icns' 필요시
)

app = BUNDLE(
    exe,
    name='PingFighter.app',
    icon=None,  # 'ball.icns' 필요시
    bundle_identifier='com.pingfighter.game',
    info_plist={
        'CFBundleName': 'PingFighter',
        'CFBundleDisplayName': 'PingFighter',
        'CFBundleGetInfoString': "PingFighter - Arcade Pong Game",
        'CFBundleIdentifier': "com.pingfighter.game",
        'CFBundleVersion': "2.0.0",
        'CFBundleShortVersionString': "2.0.0",
        'NSHumanReadableCopyright': "Copyright © 2025 PingFighter. All rights reserved.",
        'NSHighResolutionCapable': True,
    }
)