# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['pingfighter.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('*.png', '.'),
        ('*.ttf', '.'),
        ('*.txt', '.'),
        ('*.json', '.'),
        ('*.jpeg', '.'),
        ('*.py', '.'),
        ('items/*.png', 'items'),
        ('items/legendary/*.png', 'items/legendary'),
        ('items', 'items'),
        ('sounds', 'sounds'),
        ('scenes', 'scenes'),
        ('ui', 'ui'),
        ('backgrounds', 'backgrounds'),
        ('config', 'config'),
        ('core', 'core'),
        ('events', 'events'),
        ('game_logic', 'game_logic'),
        ('game_mechanics', 'game_mechanics'),
        ('item_effects', 'item_effects'),
        ('managers', 'managers'),
        ('rendering', 'rendering'),
        ('utils', 'utils'),
        ('fonts', 'fonts'),
        ('achievement', 'achievement'),
        ('ai', 'ai'),
        ('modes', 'modes'),
        ('stages', 'stages'),
        ('skills', 'skills'),
    ],
    hiddenimports=[
        'pygame',
        'items',
        'gacha',
        'academy',
        'opening',
        'skill',
        'trade_point_system',
        'pixel_font_manager',
        'effects_manager',
        'legendary_items',
        'item_effects.devil_dice',
        'item_effects.technical_vest',
        'item_effects.bluetooth_ring',
        'item_effects.fuel_pouch',
        'item_effects.dowsing_pendulum',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PingFighter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
app = BUNDLE(
    exe,
    name='PingFighter.app',
    icon=None,
    bundle_identifier=None,
)
