extends RefCounted

const ActiveItemCatalog := preload("res://scripts/items/active_item_catalog.gd")
const ProjectResourceLoader := preload("res://scripts/resources/project_resource_loader.gd")
const ActiveItemHudSlotIconRenderer := preload("res://scripts/hud/active_item_hud_slot_icon_renderer.gd")
const CharacterInfoOverlayActiveItemPresenter := preload("res://scripts/hud/character_info_overlay_active_item_presenter.gd")
const CharacterInfoOverlayEquipmentDrawer := preload("res://scripts/hud/character_info_overlay_equipment_drawer.gd")
const CharacterInfoOverlayEquipmentGeometry := preload("res://scripts/hud/character_info_overlay_equipment_geometry.gd")
const CharacterInfoOverlayFormatter := preload("res://scripts/hud/character_info_overlay_formatter.gd")
const CharacterInfoOverlayFramePresenter := preload("res://scripts/hud/character_info_overlay_frame_presenter.gd")
const CharacterInfoOverlayHoverGeometry := preload("res://scripts/hud/character_info_overlay_hover_geometry.gd")
const CharacterInfoOverlayInputHandler := preload("res://scripts/hud/character_info_overlay_input_handler.gd")
const CharacterInfoOverlayLayout := preload("res://scripts/hud/character_info_overlay_layout.gd")
const CharacterInfoOverlayLifecycle := preload("res://scripts/hud/character_info_overlay_lifecycle.gd")
const CharacterInfoOverlayLingpetPresenter := preload("res://scripts/hud/character_info_overlay_lingpet_presenter.gd")
const CharacterInfoOverlayLingpetTextureLoader := preload("res://scripts/hud/character_info_overlay_lingpet_texture_loader.gd")
const CharacterInfoOverlayOwnerState := preload("res://scripts/hud/character_info_overlay_owner_state.gd")
const CharacterInfoOverlayPassiveInventoryDrawer := preload("res://scripts/hud/character_info_overlay_passive_inventory_drawer.gd")
const CharacterInfoOverlayPassiveItemPresenter := preload("res://scripts/hud/character_info_overlay_passive_item_presenter.gd")
const CharacterInfoOverlayPerkPresenter := preload("res://scripts/hud/character_info_overlay_perk_presenter.gd")
const CharacterInfoOverlayPrewarmPresenter := preload("res://scripts/hud/character_info_overlay_prewarm_presenter.gd")
const CharacterInfoOverlaySkillSlotPresenter := preload("res://scripts/hud/character_info_overlay_skill_slot_presenter.gd")
const CharacterInfoOverlayStatsPresenter := preload("res://scripts/hud/character_info_overlay_stats_presenter.gd")
const CharacterInfoOverlayStaticData := preload("res://scripts/hud/character_info_overlay_static_data.gd")
const CharacterInfoOverlayTextLineCache := preload("res://scripts/hud/character_info_overlay_text_line_cache.gd")
const CharacterInfoOverlayTextWidthCache := preload("res://scripts/hud/character_info_overlay_text_width_cache.gd")
const CharacterInfoOverlayTextureDrawer := preload("res://scripts/hud/character_info_overlay_texture_drawer.gd")
const CharacterInfoOverlayTooltipPresenter := preload("res://scripts/hud/character_info_overlay_tooltip_presenter.gd")
const CharacterInfoOverlayValueUtils := preload("res://scripts/hud/character_info_overlay_value_utils.gd")
const PlayerCharacterRuntime := preload("res://scripts/characters/player_character_runtime.gd")
const LanguageSettings := preload("res://scripts/core/language_settings.gd")
const LINGPET_SPEED_DISPLAY_PX_PER_POINT := 60.0

const SPECIAL_GAUGE_MAX := 500.0
const PLAYER_BASE_PADDLE_WIDTH := 155.0
# Glassmorphism pass: the main frame is a frosted translucent pane over the
# (paused) battle scene; sections are slightly darker glass wells. Alpha values
# are the felt-QA levers — raise them if battle noise hurts text readability.
const PANEL_COLOR := Color(0.40, 0.54, 0.70, 0.18)
const PANEL_BORDER := Color(0.62, 0.80, 0.98, 0.85)
const SECTION_COLOR := Color(0.10, 0.17, 0.27, 0.62)
const SECTION_BORDER := Color(0.55, 0.73, 0.92, 0.55)
const TEXT_DIM := Color(178.0 / 255.0, 188.0 / 255.0, 210.0 / 255.0)
const TEXT_SOFT := Color(210.0 / 255.0, 220.0 / 255.0, 235.0 / 255.0)
const ACCENT_BLUE := Color(0.0, 205.0 / 255.0, 1.0)
const ACCENT_GOLD := Color(1.0, 215.0 / 255.0, 85.0 / 255.0)
const STAT_BUFF_COLOR := Color(105.0 / 255.0, 245.0 / 255.0, 170.0 / 255.0)
const STAT_DEBUFF_COLOR := Color(1.0, 95.0 / 255.0, 95.0 / 255.0)
const OVERLAY_GRID_FILL := Color(10.0 / 255.0, 14.0 / 255.0, 24.0 / 255.0, 0.55)
const OVERLAY_GRID_CELL_FILL := Color(20.0 / 255.0, 25.0 / 255.0, 38.0 / 255.0, 0.96)
const OVERLAY_GRID_EMPTY_TEXT := Color(125.0 / 255.0, 132.0 / 255.0, 150.0 / 255.0)
const OVERLAY_SLOT_FILL := Color(12.0 / 255.0, 17.0 / 255.0, 29.0 / 255.0, 0.96)
# Editorial chrome (pause-menu visual language shared into the character info panel).
# The draw-side alpha lever lives in character_info_overlay_frame_presenter.gd.
const EDITORIAL_BG_PATH := "res://assets/ui/pause_menu/pause_system_editorial_map_bg_cyberpunk_v2.png"
const EMPTY_HERO_PERK_CRYSTAL_PATH := "res://assets/ui/character_info/character_info_empty_perk_crystal_imagegen_v1.png"
const EMPTY_HERO_RINGPET_EGG_PATH := "res://assets/ui/character_info/character_info_empty_guardian_spirit_egg_traditional_v1.png"
const EMPTY_HERO_PASSIVE_CLUSTER_PATH := "res://assets/ui/character_info/character_info_empty_passive_crystal_cluster_imagegen_v1.png"
# Slice C scene dressing: human hologram figure, machined empty-slot socket, mystic backdrop.
const HUMAN_HOLOGRAM_PATH := "res://assets/ui/character_info/character_info_human_hologram_imagegen_v1.png"
const EMPTY_SLOT_SOCKET_PATH := "res://assets/ui/character_info/character_info_empty_slot_socket_imagegen_v1.png"
const MYSTIC_BACKDROP_PATH := "res://assets/ui/character_info/character_info_mystic_backdrop_imagegen_v1.png"
const SECTION_GLYPH_COLOR := Color(0.92, 0.96, 1.0, 0.95)
const CLASS_EMBLEM_PATHS := {
	"smasher": "res://assets/ui/character_info/character_info_class_emblem_smasher_imagegen_v1.png",
	"viper": "res://assets/ui/character_info/character_info_class_emblem_viper_imagegen_v1.png",
	"soldier": "res://assets/ui/character_info/character_info_class_emblem_soldier_imagegen_v1.png",
	"blacksmith": "res://assets/ui/character_info/character_info_class_emblem_blacksmith_imagegen_v1.png",
	"optimus": "res://assets/ui/character_info/character_info_class_emblem_optimus_imagegen_v1.png",
}
const OVERLAY_SLOT_BORDER := Color(80.0 / 255.0, 100.0 / 255.0, 140.0 / 255.0, 0.72)
const OVERLAY_SKILL_EMPTY_HOVER_FILL := Color(80.0 / 255.0, 90.0 / 255.0, 110.0 / 255.0, 0.35)
const OVERLAY_ACTIVE_EMPTY_TEXT := Color(95.0 / 255.0, 100.0 / 255.0, 120.0 / 255.0)
const OVERLAY_SCROLLBAR_TRACK := Color(0.0, 0.0, 0.0, 0.35)
const OVERLAY_PERK_SCROLLBAR_THUMB := Color(120.0 / 255.0, 170.0 / 255.0, 1.0, 0.72)
const OVERLAY_PASSIVE_SCROLLBAR_THUMB := Color(120.0 / 255.0, 220.0 / 255.0, 170.0 / 255.0, 0.72)
const OVERLAY_EQUIPPED_BADGE_FILL := Color(70.0 / 255.0, 160.0 / 255.0, 1.0, 0.92)
const OVERLAY_TOOLTIP_PANEL_FILL := Color(12.0 / 255.0, 16.0 / 255.0, 28.0 / 255.0, 0.97)
const OVERLAY_TOOLTIP_ROLL_PANEL_FILL := Color(18.0 / 255.0, 22.0 / 255.0, 40.0 / 255.0, 0.97)
const OVERLAY_TOOLTIP_ROLL_BORDER := Color(1.0, 140.0 / 255.0, 70.0 / 255.0)
const EQUIPMENT_SILHOUETTE_BASE := Color(32.0 / 255.0, 43.0 / 255.0, 72.0 / 255.0, 0.46)
const EQUIPMENT_SILHOUETTE_HEAD := Color(20.0 / 255.0, 27.0 / 255.0, 48.0 / 255.0, 0.56)
const EQUIPMENT_SILHOUETTE_NECK := Color(20.0 / 255.0, 27.0 / 255.0, 48.0 / 255.0, 0.44)
const EQUIPMENT_SILHOUETTE_DEEP_DETAIL := Color(20.0 / 255.0, 27.0 / 255.0, 48.0 / 255.0, 0.42)
const EQUIPMENT_SILHOUETTE_BASE_DETAIL := Color(32.0 / 255.0, 43.0 / 255.0, 72.0 / 255.0, 0.42)
const EQUIPMENT_SILHOUETTE_LINE := Color(105.0 / 255.0, 134.0 / 255.0, 205.0 / 255.0, 0.18)
const EQUIPMENT_SLOT_FILL_ENABLED := Color(13.0 / 255.0, 18.0 / 255.0, 32.0 / 255.0, 0.92)
const EQUIPMENT_SLOT_FILL_DISABLED := Color(13.0 / 255.0, 18.0 / 255.0, 32.0 / 255.0, 0.42)
const EQUIPMENT_SLOT_BORDER_DISABLED := Color(85.0 / 255.0, 91.0 / 255.0, 112.0 / 255.0, 0.30)
const EQUIPMENT_SLOT_BORDER_FILLED := Color(105.0 / 255.0, 245.0 / 255.0, 170.0 / 255.0, 0.92)
const EQUIPMENT_LABEL_DISABLED := Color(120.0 / 255.0, 126.0 / 255.0, 142.0 / 255.0)
const EQUIPMENT_COLOR_DISABLED := Color(85.0 / 255.0, 91.0 / 255.0, 112.0 / 255.0)
const EQUIPMENT_COLOR_FILLED := Color(105.0 / 255.0, 245.0 / 255.0, 170.0 / 255.0)
const EQUIPMENT_COLOR_HEAD := Color(120.0 / 255.0, 190.0 / 255.0, 1.0)
const EQUIPMENT_COLOR_TOP := Color(1.0, 160.0 / 255.0, 95.0 / 255.0)
const EQUIPMENT_COLOR_ARM := Color(185.0 / 255.0, 145.0 / 255.0, 1.0)
const EQUIPMENT_COLOR_BELT := Color(1.0, 215.0 / 255.0, 100.0 / 255.0)
const EQUIPMENT_COLOR_BACK := Color(125.0 / 255.0, 220.0 / 255.0, 1.0)
const EQUIPMENT_COLOR_KNEE := Color(120.0 / 255.0, 1.0, 205.0 / 255.0)
const EQUIPMENT_COLOR_SHOES := Color(115.0 / 255.0, 230.0 / 255.0, 150.0 / 255.0)
const EQUIPMENT_COLOR_ACCESSORY := Color(220.0 / 255.0, 175.0 / 255.0, 1.0)
const BASE_ACCESSORY_SLOT_COUNT := 2
const BASE_ACTIVE_ITEM_SLOT_COUNT := 3
const UI_TEXT_SCALE := 1.12
const OPEN_ANIMATION_DURATION := 0.14
const MOUSE_MOTION_REDRAW_DISTANCE := 32.0
const MOUSE_MOTION_REDRAW_DISTANCE_SQ := MOUSE_MOTION_REDRAW_DISTANCE * MOUSE_MOTION_REDRAW_DISTANCE
const UI_FONT_SIZE_CACHE_LIMIT := 64
const FALLBACK_SYMBOL_LETTER_CACHE_LIMIT := 256
const TEXT_SIZE_CACHE_LIMIT := 2048
const CENTERED_TEXT_SIZE_CACHE_LIMIT := 256
const WRAP_TEXT_CACHE_LIMIT := 1024
const PASSIVE_FRAME_COLOR_CACHE_LIMIT := 128
const PASSIVE_INVENTORY_COLUMN_TARGET := 84.0
const STAT_ROW_COUNT := 9
const LINGPET_HATCH_REQUIRED_HITS := 1
const FALLBACK_SYMBOL_RING_SEGMENTS := 8
const EQUIPMENT_BODY_RING_SEGMENTS := 4
const EQUIPMENT_BODY_ARC_SEGMENTS := 3
const EQUIPMENT_EMPTY_RING_SEGMENTS := 3
const EQUIPMENT_PLACEHOLDER_ARC_SEGMENTS := 3
const EQUIPMENT_ACCESSORY_RING_SEGMENTS := 3
const EQUIPMENT_SLOT_DEFINITIONS := CharacterInfoOverlayStaticData.EQUIPMENT_SLOT_DEFINITIONS

var active := false
var animation_time := 0.0
var _editorial_bg_texture: Texture2D = null
var _empty_perk_hero_texture: Texture2D = null
var _empty_ringpet_hero_texture: Texture2D = null
var _empty_passive_hero_texture: Texture2D = null
var _human_hologram_texture: Texture2D = null
var _empty_slot_socket_texture: Texture2D = null
var _mystic_backdrop_texture: Texture2D = null
var _class_emblem_textures: Dictionary = {}
var lingpet_panel_live2d_time := 0.0
var perk_scroll := 0.0
var passive_inventory_scroll := 0.0
var _lingpet_panel_live2d_redraw_active := false
var _last_perk_grid_rect := Rect2()
var _last_perk_content_height := 0.0
var _last_passive_inventory_rect := Rect2()
var _last_passive_inventory_grid_rect := Rect2()
var _last_passive_inventory_content_height := 0.0
var _last_equipment_rect := Rect2()
var _last_skill_rect := Rect2()
var _last_active_items_rect := Rect2()
# --- Inventory / equipment drag-and-drop + pick-up state (original PingFighter
# parity). _drag_source is "" when nothing is held. ---
var _drag_active := false
var _drag_is_mouse_down := false
var _drag_moved := false
var _drag_source := ""
var _drag_inventory_index := -1
var _drag_slot_key := ""
var _drag_active_index := -1
var _drag_press_pos := Vector2.ZERO
var _drag_current_pos := Vector2.ZERO
var _last_trash_rect := Rect2()
var _discard_confirm: Object = null
var _last_lingpet_skill_icon_rects: Array[Rect2] = []
var _last_lingpet_unlock_card_rects: Array = []
var _last_lingpet_slot_tab_rects: Array = []
var _last_lingpet_stat_row_rects: Array[Rect2] = []
var _last_equipment_slot_rects: Dictionary = {}
var _equipment_hover_uses_indexed_layout := false
var _equipment_layout_content_rect := Rect2()
var _equipment_layout_slot_size := -1.0
var _equipment_slot_rect_cache: Dictionary = {}
var _equipment_slot_rect_list_cache: Array[Rect2] = []
var _equipment_slot_icon_rect_cache: Array[Rect2] = []
var _equipment_slot_fallback_rect_cache: Array[Rect2] = []
var _equipment_slot_placeholder_rect_cache: Array[Rect2] = []
var _equipment_slot_locked_line_a_start_cache: Array[Vector2] = []
var _equipment_slot_locked_line_a_end_cache: Array[Vector2] = []
var _equipment_slot_locked_line_b_start_cache: Array[Vector2] = []
var _equipment_slot_locked_line_b_end_cache: Array[Vector2] = []
var _equipment_slot_center_x_cache: Array[float] = []
var _equipment_slot_center_y_cache: Array[float] = []
var _equipment_slot_label_y_cache: Array[float] = []
var _equipment_slot_index_cache: Dictionary = {}
var _equipment_slot_keys: Array[String] = []
var _equipment_slot_labels: Array[String] = []
var _equipment_slot_compact_labels: Array[String] = []
var _equipment_slot_visible_label_cache: Array[String] = []
var _equipment_slot_visible_label_cache_compact := false
var _equipment_slot_bases: Array[String] = []
var _equipment_slot_accessory_numbers: Array[int] = []
var _equipment_slot_empty_colors: Array[Color] = []
var _equipment_slot_empty_border_colors: Array[Color] = []
var _equipment_slot_item_cache: Array[Dictionary] = []
var _equipment_slot_has_item_cache: Array[bool] = []
var _equipment_slot_enabled_cache: Array[bool] = []
var _equipment_slot_label_color_cache: Array[Color] = []
var _equipment_slot_base_color_cache: Array[Color] = []
var _equipment_slot_border_color_cache: Array[Color] = []
var _equipment_slot_fill_color_cache: Array[Color] = []
var _equipment_slot_border_width_cache: Array[float] = []
var _equipment_slot_locked_line_color_cache: Array[Color] = []
var _equipment_slot_frame_cache_slot_state_hash := 0
var _equipment_slot_frame_cache_accessory_slot_count := -1
var _equipment_slot_frame_cache_slot_count := -1
var _empty_equipment_item: Dictionary = {}
var _equipment_silhouette_content_rect := Rect2()
var _equipment_silhouette_slot_size := -1.0
var _equipment_silhouette_body_x := 0.0
var _equipment_silhouette_head_center := Vector2.ZERO
var _equipment_silhouette_neck_rect := Rect2()
var _equipment_silhouette_shoulder_y := 0.0
var _equipment_silhouette_waist_y := 0.0
var _equipment_silhouette_hip_y := 0.0
var _equipment_silhouette_waist_w := 0.0
var _equipment_silhouette_torso_poly := PackedVector2Array()
var _equipment_silhouette_left_arm_poly := PackedVector2Array()
var _equipment_silhouette_right_arm_poly := PackedVector2Array()
var _equipment_silhouette_left_leg_poly := PackedVector2Array()
var _equipment_silhouette_right_leg_poly := PackedVector2Array()
var _active_item_catalog: Object = ActiveItemCatalog.new()
var _active_item_icon_renderer: Object = ActiveItemHudSlotIconRenderer.new()
var _character_runtime: Object = PlayerCharacterRuntime.new()
var _lingpet_art_texture_cache: Dictionary = {}
var _lingpet_skill_icon_texture_cache: Dictionary = {}
var _lingpet_stats_cache: Dictionary = {}
var _shared_icon_assets_prewarmed := false
var _static_text_prewarmed := false
var _active_item_text_prewarmed := false
var _runtime_perk_text_prewarmed := false
var _skill_text_prewarmed := false
var _prewarm_assets_step_index := 0
var _prewarm_text_step_index := 0
var _active_item_text_prewarm_entries: Array = []
var _active_item_text_prewarm_cursor := 0
var _runtime_perk_text_prewarm_entries: Array = []
var _runtime_perk_text_prewarm_cursor := 0
var _skill_text_prewarm_entries: Array = []
var _skill_text_prewarm_cursor := 0
var _lingpet_panel_prewarm_step_index := 0
var _prewarm_shared_runtime_icon_assets_done := false
var _prewarm_shared_active_item_icons_done := false
var _passive_inventory_icon_prewarm_items_hash := 0
var _passive_inventory_icon_prewarm_item_count := -1
var _passive_inventory_draw_cache_items_hash := 0
var _passive_inventory_draw_cache_item_count := -1
var _passive_inventory_summary_count := -1
var _passive_inventory_summary_equipped := -1
var _passive_inventory_summary: Dictionary = {"count": 0, "equipped": 0, "count_text": "보유 0 / 장착 0"}
var _header_subtitle_cache: Dictionary = {}
var _header_status_text_cache: Dictionary = {}
var _header_status_width_cache: Dictionary = {}
var _passive_inventory_count_text_width_cache: Dictionary = {}
var _passive_item_frame_color_cache: Dictionary = {}
var _passive_item_body_cache_hash := 0
var _passive_item_body_cache_ready := false
var _passive_item_body_cache := ""
var _passive_item_roll_entries_cache_item_hash := 0
var _passive_item_roll_entries_cache_runtime_id := 0
var _passive_item_roll_entries_cache_polish_multiplier := -1.0
var _passive_item_roll_entries_cache: Array = []
var _passive_item_roll_entry_dict_cache: Array = []
var _equipment_item_display_name_cache_hash := 0
var _equipment_item_display_name_cache_ready := false
var _equipment_item_display_name_cache := ""
var _item_quality_color_cache_hash := 0
var _item_quality_color_cache_ready := false
var _item_quality_color_cache := Color.WHITE
var _tooltip_subtitle_color_source := Color.TRANSPARENT
var _tooltip_subtitle_color_cache := Color.WHITE
var _tooltip_entry_lines_cache_entries_hash := 0
var _tooltip_entry_lines_cache_size := 0
var _tooltip_entry_lines_cache_width := 0
var _tooltip_entry_lines_cache_max_lines := 0
var _tooltip_entry_lines_cache: Array = []
var _tooltip_entry_line_dict_cache: Array = []
var _tooltip_entry_line_text_cache: Array[String] = []
var _tooltip_entry_line_color_cache: Array[Color] = []
var _empty_tooltip_roll_entries: Array = []
var _ui_font_size_cache: Array[int] = []
var _fallback_symbol_letter_cache: Dictionary = {}
var _text_size_cache: Dictionary = {}
var _text_size_fast_text := ""
var _text_size_fast_ui_size := 0
var _text_size_fast_value := Vector2.ZERO
var _wrap_text_cache: Dictionary = {}
var _wrap_text_fast_text := ""
var _wrap_text_fast_size := 0
var _wrap_text_fast_width := 0
var _wrap_text_fast_max_lines := 0
var _wrap_text_fast_lines: Array = []
var _acquired_perk_cache_hash := 0
var _acquired_perk_cache_ready := false
var _acquired_perk_cache: Array = []
# TAB perk-grid animation liveness. `_perk_grid_has_animated_icon` is recomputed each
# perk-grid draw: true while the padded grid shows at least one sheet-backed (animated)
# perk icon. CharacterInfoOverlayLifecycle.update reads it to fire a throttled redraw
# (~110ms cadence, tracked by `_perk_grid_anim_frame_step`) so animated mythic-perk
# icons keep playing without a mouse-move nudge, while an all-static panel stays at
# zero redraw cost.
var _perk_grid_has_animated_icon: bool = false
var _perk_grid_anim_frame_step: int = -1
var _acquired_perk_draw_id_cache: Array[String] = []
var _acquired_perk_draw_color_cache: Array[Color] = []
var _acquired_perk_border_color_cache: Array[Color] = []
var _acquired_perk_hover_border_color_cache: Array[Color] = []
var _acquired_perk_level_text_cache: Array[String] = []
var _acquired_perk_level_color_cache: Array[Color] = []
var _acquired_perk_hover_title_cache: Array[String] = []
var _acquired_perk_hover_body_cache: Array[String] = []
var _acquired_perk_hover_detail_cache: Array[String] = []
var _perk_level_text_size_cache_texts: Array[String] = []
var _perk_level_text_size_cache_sizes: Array[int] = []
var _perk_level_text_size_cache_font_ids: Array[int] = []
var _perk_level_text_size_cache_values: Array[Vector2] = []
var _perk_level_text_size_fast_text := ""
var _perk_level_text_size_fast_size := 0
var _perk_level_text_size_fast_font_id := 0
var _perk_level_text_size_fast_value := Vector2.ZERO
var _centered_text_size_cache_texts: Array[String] = []
var _centered_text_size_cache_sizes: Array[int] = []
var _centered_text_size_cache_font_ids: Array[int] = []
var _centered_text_size_cache_values: Array[Vector2] = []
var _centered_text_size_fast_text := ""
var _centered_text_size_fast_size := 0
var _centered_text_size_fast_font_id := 0
var _centered_text_size_fast_value := Vector2.ZERO
var _skill_slot_layout_rect := Rect2()
var _skill_slot_layout_count := -1
var _skill_slot_layout_slot_size := -1.0
var _skill_slot_rect_cache: Array[Rect2] = []
var _skill_slot_icon_rect_cache: Array[Rect2] = []
var _skill_slot_fallback_rect_cache: Array[Rect2] = []
var _skill_slot_center_cache: Array[Vector2] = []
var _skill_slot_center_x_cache: Array[float] = []
var _skill_slot_label_y := 0.0
var _skill_slot_draw_cache_equipped_hash := 0
var _skill_slot_draw_cache_skill_data_hash := 0
var _skill_slot_draw_cache_fallback_color := Color.TRANSPARENT
var _skill_slot_id_cache: Array[String] = []
var _skill_slot_data_cache: Array[Dictionary] = []
var _skill_slot_label_cache: Array[String] = []
var _skill_slot_color_cache: Array[Color] = []
var _skill_slot_fill_color_cache: Array[Color] = []
var _skill_slot_border_color_cache: Array[Color] = []
var _active_item_label_cache_names: Array[String] = []
var _active_item_label_cache_raw_display_names: Array[String] = []
var _active_item_display_name_cache: Array[String] = []
var _active_item_trimmed_label_cache: Array[String] = []
var _active_slot_draw_cache_slots_hash := 0
var _active_slot_draw_cache_max_slots := -1
var _active_slot_draw_cache_visuals_id := -1
var _active_slot_draw_cache_should_cache_colors := false
var _active_slot_has_item_cache: Array[bool] = []
var _active_slot_item_cache: Array[Dictionary] = []
var _active_slot_fallback_color_cache: Array[Color] = []
var _active_slot_has_fallback_color_cache: Array[bool] = []
var _active_slot_layout_rect := Rect2()
var _active_slot_layout_count := -1
var _active_slot_layout_slot_size := -1.0
var _active_slot_layout_gap := -1.0
var _active_slot_rect_cache: Array[Rect2] = []
var _active_slot_fallback_rect_cache: Array[Rect2] = []
var _active_slot_center_x_cache: Array[float] = []
var _active_slot_empty_marker_y := 0.0
var _active_slot_label_y := 0.0
var _passive_grid_layout_rect := Rect2()
var _passive_grid_layout_scroll := -1.0
var _passive_grid_layout_columns := -1
var _passive_grid_layout_cell_size := -1.0
var _passive_grid_layout_stride := -1.0
var _passive_grid_layout_item_count := -1
var _passive_grid_visible_index_cache: Array[int] = []
var _passive_grid_cell_rect_cache: Array[Rect2] = []
var _passive_grid_icon_rect_cache: Array[Rect2] = []
var _passive_grid_fallback_rect_cache: Array[Rect2] = []
var _passive_grid_badge_rect_cache: Array[Rect2] = []
var _passive_grid_badge_center_x_cache: Array[float] = []
var _passive_grid_badge_center_y_cache: Array[float] = []
var _passive_inventory_item_cache: Array[Dictionary] = []
var _passive_inventory_draw_color_cache: Array[Color] = []
var _passive_inventory_border_color_cache: Array[Color] = []
var _passive_inventory_active_border_color_cache: Array[Color] = []
var _passive_inventory_equipped_cache: Array[bool] = []
var _passive_scrollbar_track_rect := Rect2()
var _passive_scrollbar_thumb_rect := Rect2()
var _perk_grid_layout_rect := Rect2()
var _perk_grid_layout_scroll := -1.0
var _perk_grid_layout_columns := -1
var _perk_grid_layout_cell_size := -1.0
var _perk_grid_layout_stride := -1.0
var _perk_grid_layout_item_count := -1
var _perk_grid_visible_index_cache: Array[int] = []
var _perk_grid_cell_rect_cache: Array[Rect2] = []
var _perk_grid_icon_rect_cache: Array[Rect2] = []
var _perk_grid_center_x_cache: Array[float] = []
var _perk_grid_level_y_cache: Array[float] = []
var _perk_scrollbar_track_rect := Rect2()
var _perk_scrollbar_thumb_rect := Rect2()
var _stats_row_cache: Array = []
var _stats_row_count := 0
var _stats_label_cache: Array[String] = []
var _stats_value_cache: Array[String] = []
var _stats_color_cache: Array[Color] = []
var _stats_value_width_cache: Array[float] = []
var _stats_value_width_text_cache: Array[String] = []
var _stats_value_width_size_cache: Array[int] = []
var _stats_value_width_font_id_cache: Array[int] = []
var _frame_stat_sources: Array = []
var _frame_hover_data: Dictionary = {}
var _layout_view_size := Vector2(-1.0, -1.0)
var _layout_panel_rect := Rect2()
var _layout_equipment_rect := Rect2()
var _layout_skill_rect := Rect2()
var _layout_active_items_rect := Rect2()
var _layout_perk_rect := Rect2()
var _layout_lingpet_rect := Rect2()
var _layout_stats_rect := Rect2()
var _layout_inventory_rect := Rect2()
var _last_passive_grid_start := Vector2.ZERO
var _last_passive_grid_cell_size := 0.0
var _last_passive_grid_stride := 0.0
var _last_passive_grid_columns := 0
var _last_passive_grid_item_count := 0
var _last_perk_grid_start := Vector2.ZERO
var _last_perk_grid_cell_size := 0.0
var _last_perk_grid_stride := 0.0
var _last_perk_grid_columns := 0
var _last_perk_grid_item_count := 0
var _layout_lingpet_stats_rect := Rect2()
var _perk_display_entries_cache: Array = []
var _perk_display_entries_source: Array = []
var _perk_display_entries_slot_count := 0
var _last_skill_slot_start := Vector2.ZERO
var _last_skill_slot_size := 0.0
var _last_skill_slot_height := 0.0
var _last_skill_slot_stride := 0.0
var _last_skill_slot_count := 0
var _last_active_slot_start := Vector2.ZERO
var _last_active_slot_size := 0.0
var _last_active_slot_stride := 0.0
var _last_active_slot_count := 0
var _redraw_requested := false
var _input_redraw_requested := false
var _last_hover_signature := ""
var _last_mouse_redraw_position := Vector2.ZERO
var _has_mouse_redraw_position := false
var _skill_cooldown_pause_active := false
var _skill_cooldown_pause_owner: Object = null
var _skill_cooldown_pause_registry: Object = null

func state_fields_warning_anchor() -> int:
	var value := 0
	value = hash([value, active, animation_time, _editorial_bg_texture, _empty_perk_hero_texture, _empty_ringpet_hero_texture, _empty_passive_hero_texture, lingpet_panel_live2d_time, perk_scroll, passive_inventory_scroll, _lingpet_panel_live2d_redraw_active, _last_perk_grid_rect, _last_perk_content_height, _last_passive_inventory_rect, _last_passive_inventory_grid_rect, _last_passive_inventory_content_height, _last_equipment_rect, _last_skill_rect, _last_active_items_rect, _last_lingpet_skill_icon_rects, _last_lingpet_unlock_card_rects, _last_lingpet_stat_row_rects, _last_equipment_slot_rects, _equipment_hover_uses_indexed_layout, _equipment_layout_content_rect, _equipment_layout_slot_size, _equipment_slot_rect_cache, _equipment_slot_rect_list_cache, _equipment_slot_icon_rect_cache, _equipment_slot_fallback_rect_cache, _equipment_slot_placeholder_rect_cache, _equipment_slot_locked_line_a_start_cache, _equipment_slot_locked_line_a_end_cache, _equipment_slot_locked_line_b_start_cache, _equipment_slot_locked_line_b_end_cache, _equipment_slot_center_x_cache, _equipment_slot_center_y_cache, _equipment_slot_label_y_cache, _equipment_slot_index_cache, _equipment_slot_keys, _equipment_slot_labels, _equipment_slot_compact_labels, _equipment_slot_visible_label_cache, _equipment_slot_visible_label_cache_compact, _equipment_slot_bases, _equipment_slot_accessory_numbers, _equipment_slot_empty_colors, _equipment_slot_empty_border_colors])
	value = hash([value, _equipment_slot_item_cache, _equipment_slot_has_item_cache, _equipment_slot_enabled_cache, _equipment_slot_label_color_cache, _equipment_slot_base_color_cache, _equipment_slot_border_color_cache, _equipment_slot_fill_color_cache, _equipment_slot_border_width_cache, _equipment_slot_locked_line_color_cache, _equipment_slot_frame_cache_slot_state_hash, _equipment_slot_frame_cache_accessory_slot_count, _equipment_slot_frame_cache_slot_count, _empty_equipment_item, _equipment_silhouette_content_rect, _equipment_silhouette_slot_size, _equipment_silhouette_body_x, _equipment_silhouette_head_center, _equipment_silhouette_neck_rect, _equipment_silhouette_shoulder_y, _equipment_silhouette_waist_y, _equipment_silhouette_hip_y, _equipment_silhouette_waist_w, _equipment_silhouette_torso_poly, _equipment_silhouette_left_arm_poly, _equipment_silhouette_right_arm_poly, _equipment_silhouette_left_leg_poly, _equipment_silhouette_right_leg_poly, _active_item_catalog, _active_item_icon_renderer, _character_runtime, _lingpet_art_texture_cache, _lingpet_skill_icon_texture_cache, _lingpet_stats_cache, _shared_icon_assets_prewarmed, _static_text_prewarmed, _active_item_text_prewarmed, _runtime_perk_text_prewarmed, _skill_text_prewarmed, _prewarm_assets_step_index, _prewarm_text_step_index, _active_item_text_prewarm_entries, _active_item_text_prewarm_cursor, _runtime_perk_text_prewarm_entries, _runtime_perk_text_prewarm_cursor, _skill_text_prewarm_entries, _skill_text_prewarm_cursor, _lingpet_panel_prewarm_step_index, _prewarm_shared_runtime_icon_assets_done, _prewarm_shared_active_item_icons_done, _passive_inventory_icon_prewarm_items_hash, _passive_inventory_icon_prewarm_item_count])
	value = hash([value, _passive_inventory_draw_cache_items_hash, _passive_inventory_draw_cache_item_count, _passive_inventory_summary_count, _passive_inventory_summary_equipped, _passive_inventory_summary, _header_subtitle_cache, _header_status_text_cache, _header_status_width_cache, _passive_inventory_count_text_width_cache, _passive_item_frame_color_cache, _passive_item_body_cache_hash, _passive_item_body_cache_ready, _passive_item_body_cache, _passive_item_roll_entries_cache_item_hash, _passive_item_roll_entries_cache_runtime_id, _passive_item_roll_entries_cache_polish_multiplier, _passive_item_roll_entries_cache, _passive_item_roll_entry_dict_cache, _equipment_item_display_name_cache_hash, _equipment_item_display_name_cache_ready, _equipment_item_display_name_cache, _item_quality_color_cache_hash, _item_quality_color_cache_ready, _item_quality_color_cache, _tooltip_subtitle_color_source, _tooltip_subtitle_color_cache, _tooltip_entry_lines_cache_entries_hash, _tooltip_entry_lines_cache_size, _tooltip_entry_lines_cache_width, _tooltip_entry_lines_cache_max_lines, _tooltip_entry_lines_cache, _tooltip_entry_line_dict_cache, _tooltip_entry_line_text_cache, _tooltip_entry_line_color_cache, _empty_tooltip_roll_entries, _ui_font_size_cache, _fallback_symbol_letter_cache, _text_size_cache, _text_size_fast_text, _text_size_fast_ui_size])
	value = hash([value, _text_size_fast_value, _wrap_text_cache, _wrap_text_fast_text, _wrap_text_fast_size, _wrap_text_fast_width, _wrap_text_fast_max_lines, _wrap_text_fast_lines, _acquired_perk_cache_hash, _acquired_perk_cache_ready, _acquired_perk_cache, _acquired_perk_draw_id_cache, _acquired_perk_draw_color_cache, _acquired_perk_border_color_cache, _acquired_perk_hover_border_color_cache, _acquired_perk_level_text_cache, _acquired_perk_level_color_cache, _acquired_perk_hover_title_cache, _acquired_perk_hover_body_cache, _acquired_perk_hover_detail_cache, _perk_level_text_size_cache_texts, _perk_level_text_size_cache_sizes, _perk_level_text_size_cache_font_ids, _perk_level_text_size_cache_values, _perk_level_text_size_fast_text, _perk_level_text_size_fast_size, _perk_level_text_size_fast_font_id, _perk_level_text_size_fast_value, _centered_text_size_cache_texts, _centered_text_size_cache_sizes, _centered_text_size_cache_font_ids, _centered_text_size_cache_values, _centered_text_size_fast_text, _centered_text_size_fast_size, _centered_text_size_fast_font_id, _centered_text_size_fast_value, _skill_slot_layout_rect, _skill_slot_layout_count, _skill_slot_layout_slot_size, _skill_slot_rect_cache, _skill_slot_icon_rect_cache, _skill_slot_fallback_rect_cache])
	value = hash([value, _skill_slot_center_cache, _skill_slot_center_x_cache, _skill_slot_label_y, _skill_slot_draw_cache_equipped_hash, _skill_slot_draw_cache_skill_data_hash, _skill_slot_draw_cache_fallback_color, _skill_slot_id_cache, _skill_slot_data_cache, _skill_slot_label_cache, _skill_slot_color_cache, _skill_slot_fill_color_cache, _skill_slot_border_color_cache, _active_item_label_cache_names, _active_item_label_cache_raw_display_names, _active_item_display_name_cache, _active_item_trimmed_label_cache, _active_slot_draw_cache_slots_hash, _active_slot_draw_cache_max_slots, _active_slot_draw_cache_visuals_id, _active_slot_draw_cache_should_cache_colors, _active_slot_has_item_cache, _active_slot_item_cache, _active_slot_fallback_color_cache, _active_slot_has_fallback_color_cache, _active_slot_layout_rect, _active_slot_layout_count, _active_slot_layout_slot_size, _active_slot_layout_gap, _active_slot_rect_cache, _active_slot_fallback_rect_cache, _active_slot_center_x_cache, _active_slot_empty_marker_y, _active_slot_label_y, _passive_grid_layout_rect, _passive_grid_layout_scroll, _passive_grid_layout_columns, _passive_grid_layout_cell_size, _passive_grid_layout_stride, _passive_grid_layout_item_count, _passive_grid_visible_index_cache])
	value = hash([value, _passive_grid_cell_rect_cache, _passive_grid_icon_rect_cache, _passive_grid_fallback_rect_cache, _passive_grid_badge_rect_cache, _passive_grid_badge_center_x_cache, _passive_grid_badge_center_y_cache, _passive_inventory_item_cache, _passive_inventory_draw_color_cache, _passive_inventory_border_color_cache, _passive_inventory_active_border_color_cache, _passive_inventory_equipped_cache, _passive_scrollbar_track_rect, _passive_scrollbar_thumb_rect, _perk_grid_layout_rect, _perk_grid_layout_scroll, _perk_grid_layout_columns, _perk_grid_layout_cell_size, _perk_grid_layout_stride, _perk_grid_layout_item_count, _perk_grid_visible_index_cache, _perk_grid_cell_rect_cache, _perk_grid_icon_rect_cache, _perk_grid_center_x_cache, _perk_grid_level_y_cache, _perk_scrollbar_track_rect, _perk_scrollbar_thumb_rect, _stats_row_cache, _stats_row_count, _stats_label_cache, _stats_value_cache, _stats_color_cache, _stats_value_width_cache, _stats_value_width_text_cache, _stats_value_width_size_cache, _stats_value_width_font_id_cache, _frame_stat_sources, _frame_hover_data, _layout_view_size, _layout_panel_rect, _layout_equipment_rect])
	value = hash([value, _layout_skill_rect, _layout_active_items_rect, _layout_perk_rect, _layout_lingpet_rect, _layout_stats_rect, _layout_inventory_rect, _last_passive_grid_start, _last_passive_grid_cell_size, _last_passive_grid_stride, _last_passive_grid_columns, _last_passive_grid_item_count, _last_perk_grid_start, _last_perk_grid_cell_size, _last_perk_grid_stride, _last_perk_grid_columns, _last_perk_grid_item_count, _last_skill_slot_start, _last_skill_slot_size, _last_skill_slot_height, _last_skill_slot_stride, _last_skill_slot_count, _last_active_slot_start, _last_active_slot_size, _last_active_slot_stride, _last_active_slot_count, _redraw_requested, _input_redraw_requested, _last_hover_signature, _last_mouse_redraw_position, _has_mouse_redraw_position, _skill_cooldown_pause_active, _skill_cooldown_pause_owner, _skill_cooldown_pause_registry])
	return value
