extends RefCounted

const CARD_ROOT := "res://assets/ui/character_cards/"
const LIVE2D_ROOT := "res://assets/ui/character_live2d/"
const CHARACTER_SELECT_ORDER := ["ufo_player", "soldier", "viper", "blacksmith", "optimus"]


static func get_characters() -> Array:
	var characters: Array = [
		{
			"id": "ufo_player",
			"runtime_id": "smasher",
			"tagline": "게이지 폭발 연속 스매시",
			"difficulty_stars": 2,
			"skill_icon_paths": [
				"res://assets/sprites/skills/smasher_power_smashing_skill_orb.png",
				"res://assets/sprites/skills/smasher_drive_skill_orb.png",
				"res://assets/sprites/skills/smasher_shield_kiting_skill_orb.png",
			],
			"full_body_live2d_path": LIVE2D_ROOT + "smasher_fullbody_hover_idle_loop49_assetanim_v2_realesrgan_animev3_hq1024_frame0_safe.png",
			"full_body_live2d_sheet_path": LIVE2D_ROOT + "smasher_fullbody_hover_idle_loop49_assetanim_v2_realesrgan_animev3_hq1024_safe.png",
			"full_body_live2d_cols": 7,
			"full_body_live2d_rows": 7,
			"full_body_live2d_count": 49,
			"full_body_live2d_interval": 0.033,
			"full_body_live2d_trim_rect": Rect2(203.0, 6.0, 628.0, 1000.0),
			"full_body_live2d_stage_scale": 0.96,
			"full_body_live2d_stage_x_scale": 0.90,
			"full_body_live2d_stage_y_scale": 1.12,
			"full_body_live2d_stage_x_offset_ratio": 0.0,
			"full_body_live2d_stage_y_offset_ratio": 0.01,
			"name": "스매셔",
			"character_name": "미카",
			"class_name": "스매셔",
			"role": "핵심 스트라이커",
			"description": "풀파워 스매시로 흐름을 밀어붙이는 정면 돌파형 캐릭터.",
			"special": "스매시 전용 스킬트리 보유",
			"stats": {"속도": 4, "파워": 7, "방어": 4},
			"unlocked": true,
			"card_color": Color8(0, 230, 255),
			"glow_color": Color8(0, 200, 255),
			"portrait_path": CARD_ROOT + "smasher_card_female_bionic_paddle_helmet_imagegen_v1_cutout_clean_padded.png",
			"card_face_focus": Vector2(0.52, 0.21),
			"card_face_source_height_ratio": 0.34,
			"live2d_preview_still_path": CARD_ROOT + "smasher_card_female_bionic_paddle_helmet_imagegen_v1_cutout_clean_padded.png",
			"live2d_fullframe_sheet_path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_smooth_menu_idle_loop49_autosprite_v8_realesrgan_animev3_hq1536_safe.png",
			"live2d_fullframe_sheet_candidates": [
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_smooth_menu_idle_loop49_autosprite_v8_realesrgan_animev3_hq1536_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(336.0, 68.0, 899.0, 1344.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_smooth_menu_idle_loop49_autosprite_v8_hq1536_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(336.0, 69.0, 898.5, 1342.5),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_smooth_menu_idle_loop49_autosprite_v8_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(224.0, 46.0, 599.0, 895.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_loop49_autosprite_v2_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(200.0, 41.0, 684.0, 911.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_loop49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(200.0, 41.0, 684.0, 911.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_loop147_v4_true_motion_scale_locked_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
					"trim_rect": Rect2(200.0, 41.0, 684.0, 911.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_ABC_loop147_v3_true_motion_scale_locked_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
					"trim_rect": Rect2(200.0, 41.0, 684.0, 911.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_ABC_loop147_v2_size_locked_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
					"trim_rect": Rect2(200.0, 41.0, 684.0, 911.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_clean_midthigh_rigid_loop49_autosprite_v1_jawfix_v2.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(192.0, 43.0, 662.0, 956.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_clean_midthigh_rigid_loop49_autosprite_v1.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(192.0, 43.0, 662.0, 956.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_center_palmshield_midthigh_rigid_loop49_autosprite_v1_nukki_fix_v2.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(191.0, 54.0, 647.0, 920.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_center_palmshield_midthigh_rigid_loop49_autosprite_v1.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(191.0, 54.0, 647.0, 920.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_center_palmshield_upperbody_loop49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(70.0, 107.0, 914.0, 886.0),
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_smooth_menu_idle_loop49_autosprite_v8_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_no_fins_micro_idle_ABC_loop147_original_anchor_autosprite_v7_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_micro_idle_ADC_loop147_original_anchor_autosprite_v6_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_white_chest_idle_ABC_loop147_original_anchor_autosprite_v5_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_loop64_autosprite_v2_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_female_bionic_active_idle_loop64_autosprite_v1_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_live2d_card_64f_autosprite_v3.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.033,
				},
				{
					"path": LIVE2D_ROOT + "smasher_live2d_card_49f_autosprite_v2.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.072,
				},
				{
					"path": LIVE2D_ROOT + "smasher_live2d_fullframe_sheet_v2.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": CARD_ROOT + "smasher_card_female_bionic_paddle_helmet_imagegen_v1_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": CARD_ROOT + "smasher_card_from_live2d_v2_frame01_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
			],
			"live2d_fullframe_cols": 7,
			"live2d_fullframe_rows": 7,
			"live2d_fullframe_count": 49,
			"live2d_fullframe_interval": 0.033,
			"live2d_trim_rect": Rect2(336.0, 68.0, 899.0, 1344.0),
			"confirm_intro_sheet_path": LIVE2D_ROOT + "smasher_select_confirm_swing_bada_loop98_autosprite_v2_stable_realesrgan_animev3_hq1152_safe.png",
			"confirm_intro_cols": 14,
			"confirm_intro_rows": 7,
			"confirm_intro_count": 98,
			"confirm_intro_interval": 0.020,
			"confirm_intro_min_interval": 0.01,
			"confirm_intro_min_duration": 2.35,
			"confirm_intro_trim_transparent_source": true,
			"confirm_intro_trim_rect": Rect2(74.25, 40.5, 933.75, 1017.0),
			"confirm_intro_float_motion_enabled": false,
			"confirm_intro_transition_duration": 0.18,
			"confirm_intro_return_transition_duration": 0.0,
			"confirm_intro_return_sheet_path": "",
			"confirm_intro_return_cols": 7,
			"confirm_intro_return_rows": 7,
			"confirm_intro_return_count": 49,
			"confirm_intro_return_interval": 0.020,
			"confirm_intro_return_min_interval": 0.01,
			"confirm_intro_return_trim_transparent_source": false,
			"confirm_intro_return_trim_rect": Rect2(0.0, 0.0, 1024.0, 1024.0),
			"confirm_intro_return_float_motion_enabled": false,
			"confirm_intro_return_stage_scale": 1.0,
			"confirm_intro_return_stage_x_offset_ratio": 0.0,
			"confirm_intro_return_stage_y_offset_ratio": 0.0,
			"click_motion_return_transition_duration": 0.0,
			"confirm_intro_stage_scale": 1.04,
			"confirm_intro_stage_x_offset_ratio": -0.034,
			"confirm_intro_stage_y_offset_ratio": -0.006,
			"confirm_intro_voice_path": "res://voice/smasherselect.mp3",
			"confirm_intro_voice_delay": 0.78,
			"confirm_intro_voice_volume_db": -6.0,
			"confirm_intro_exit_flash_enabled": true,
			"confirm_intro_exit_flash_hold": 0.08,
			"confirm_intro_exit_flash_duration": 0.55,
			"confirm_intro_exit_flash_style": "burst",
			"confirm_intro_exit_flash_color": Color(0.16, 0.90, 1.0),
			"confirm_intro_exit_flash_glow_color": Color(0.74, 0.98, 1.0),
			"confirm_intro_exit_flash_secondary_color": Color(1.0, 1.0, 1.0),
			"confirm_intro_exit_flash_field_intensity": 1.0,
			"confirm_intro_exit_flash_card_intensity": 1.0,
			"confirm_intro_exit_flash_white_wash_target": 0.94,
			"confirm_intro_exit_flash_chroma": 0.013,
			"live2d_deform_still": false,
			"live2d_deform_strips": 18,
			"live2d_motion_strength": 0.0,
			"live2d_float_bob": 2.0,
			"live2d_float_sway": 0.8,
			"live2d_float_scale": 0.005,
			"live2d_mouse_response": 0.08,
			"live2d_stage_scale": 0.98,
			"live2d_stage_y_offset": -0.005,
			"live2d_stage_min_top_ratio": 0.035,
			"live2d_card_cutline_ratio": 0.79,
			"live2d_trim_transparent_source": true,
			"live2d_trim_padding_ratio": 0.050,
			"live2d_trim_sample_frame_limit": 49,
			"live2d_layer_motion_strength": 0.0,
			"live2d_canvas_offsets_enabled": false,
			"live2d_motion_regions_enabled": false,
			"live2d_motion_regions": [
				{
					"name": "hair_sway",
					"source_rect": Rect2(0.10, 0.02, 0.58, 0.30),
					"pivot": Vector2(0.48, 0.95),
					"offset": Vector2(2.6, 0.8),
					"rotation": 0.010,
					"speed": 1.65,
					"phase": 0.4,
				},
				{
					"name": "bangs",
					"source_rect": Rect2(0.18, 0.12, 0.38, 0.22),
					"pivot": Vector2(0.52, 0.18),
					"offset": Vector2(1.8, 0.6),
					"rotation": -0.007,
					"speed": 2.05,
					"phase": 1.2,
				},
				{
					"name": "hand_racket",
					"source_rect": Rect2(0.38, 0.36, 0.56, 0.61),
					"pivot": Vector2(0.32, 0.78),
					"offset": Vector2(2.2, 1.5),
					"rotation": 0.018,
					"speed": 1.45,
					"phase": 2.1,
				},
			],
			"live2d_blink_enabled": false,
			"live2d_blink_interval": 3.4,
			"live2d_blink_duration": 0.22,
			"live2d_blink_eyes": [
				{"center": Vector2(0.34, 0.35), "size": Vector2(0.115, 0.036), "angle": -0.03},
				{"center": Vector2(0.49, 0.35), "size": Vector2(0.105, 0.036), "angle": -0.01},
			],
			"live2d_canvas_locked": false,
			"live2d_layers": {},
		},
		{
			"id": "soldier",
			"runtime_id": "soldier",
			"tagline": "화기 전환 전술가",
			"difficulty_stars": 2,
			"skill_icon_paths": [
				"res://assets/sprites/skills/commando_pistol_skill_orb.png",
				"res://assets/sprites/skills/commando_ak47_skill_orb.png",
				"res://assets/sprites/skills/commando_supply_drop_skill_orb.png",
			],
			"full_body_live2d_path": LIVE2D_ROOT + "commando_fullbody_hatfix_padded_idle_loop49_autosprite_v6_frame0_safe.png",
			"full_body_live2d_sheet_path": LIVE2D_ROOT + "commando_fullbody_hatfix_padded_idle_loop49_autosprite_v6_safe.png",
			"full_body_live2d_cols": 7,
			"full_body_live2d_rows": 7,
			"full_body_live2d_count": 49,
			"full_body_live2d_interval": 0.033,
			"full_body_live2d_trim_rect": Rect2(325.0, 72.0, 386.0, 865.0),
			"full_body_live2d_stage_scale": 0.784,
			"full_body_live2d_stage_x_offset_ratio": 0.0,
			"full_body_live2d_stage_y_offset_ratio": 0.01,
			"name": "코만도",
			"character_name": "레나",
			"class_name": "코만도",
			"role": "전술 통제",
			"description": "보급 호출과 화기 전환으로 전장을 재구성하는 밀리터리 전술가.",
			"special": "전투 경험과 전술적 우위",
			"stats": {"속도": 6, "파워": 6, "방어": 6},
			"unlocked": true,
			"card_color": Color8(95, 145, 68),
			"glow_color": Color8(120, 180, 82),
			"portrait_path": CARD_ROOT + "commando_card_pistol_close_smasher_pose_imagegen_v4_cutout_clean_padded.png",
			"card_face_focus": Vector2(0.49, 0.20),
			"card_face_source_height_ratio": 0.34,
			"live2d_preview_still_path": CARD_ROOT + "commando_card_pistol_close_smasher_pose_imagegen_v4_cutout_clean_padded.png",
			"live2d_fullframe_sheet_path": LIVE2D_ROOT + "commando_pistol_close_card_idle_loop49_autosprite_v1_realesrgan_animev3_hq1536_safe.png",
			"live2d_fullframe_sheet_candidates": [
				{
					"path": LIVE2D_ROOT + "commando_pistol_close_card_idle_loop49_autosprite_v1_realesrgan_animev3_hq1536_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(247.0, 51.0, 1129.0, 1370.0),
				},
				{
					"path": LIVE2D_ROOT + "commando_pistol_close_card_idle_loop49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_pistol_close_card_idle_loop64_autosprite_v1_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_bishoujo_idle_loop64_autosprite_v6_prompt_body_bob_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_bishoujo_idle_loop64_autosprite_v5_body_sway_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_bishoujo_idle_loop64_autosprite_v4_radar_bounce_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_bishoujo_idle_loop64_autosprite_v2_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": CARD_ROOT + "commando_card_pistol_close_smasher_pose_imagegen_v4_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_large_bust_64f_autosprite_v4_skirt_stable.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_large_bust_64f_autosprite_v1.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "commando_live2d_card_64f_autosprite_v1.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.050,
				},
			],
			"live2d_fullframe_cols": 7,
			"live2d_fullframe_rows": 7,
			"live2d_fullframe_count": 49,
			"live2d_fullframe_interval": 0.045,
			"live2d_trim_rect": Rect2(247.0, 51.0, 1129.0, 1370.0),
			"live2d_trim_transparent_source": true,
			"live2d_trim_sample_frame_limit": 49,
			"confirm_intro_sheet_path": LIVE2D_ROOT + "commando_select_confirm_radio_ready_loop98_autosprite_v1_stable_realesrgan_animev3_hq1152_safe.png",
			"confirm_intro_cols": 14,
			"confirm_intro_rows": 7,
			"confirm_intro_count": 98,
			"confirm_intro_interval": 0.020,
			"confirm_intro_min_interval": 0.01,
			"confirm_intro_min_duration": 2.80,
			"confirm_intro_trim_transparent_source": true,
			"confirm_intro_trim_rect": Rect2(221.0, 67.0, 785.0, 1031.0),
			"confirm_intro_float_motion_enabled": false,
			"confirm_intro_transition_duration": 0.16,
			"confirm_intro_stage_scale": 1.0,
			"confirm_intro_stage_x_offset_ratio": -0.018,
			"confirm_intro_stage_y_offset_ratio": 0.0,
			"confirm_intro_voice_path": "res://voice/commandoselect.mp3",
			"confirm_intro_voice_delay": 0.25,
			"confirm_intro_voice_volume_db": -5.0,
			"confirm_intro_exit_flash_enabled": true,
			"confirm_intro_exit_flash_hold": 0.08,
			"confirm_intro_exit_flash_duration": 0.32,
			"confirm_intro_exit_flash_style": "burst",
			"confirm_intro_exit_flash_color": Color(0.38, 0.95, 0.20),
			"confirm_intro_exit_flash_glow_color": Color(0.58, 1.0, 0.36),
			"confirm_intro_exit_flash_secondary_color": Color(1.0, 1.0, 1.0),
			"live2d_float_bob": 3.0,
			"live2d_float_sway": 0.9,
			"live2d_float_scale": 0.004,
			"live2d_mouse_response": 0.04,
			"live2d_deform_fullframe_sheet": false,
			"live2d_motion_regions_enabled": false,
			"live2d_card_cutline_ratio": 0.79,
			"live2d_layers": _layer_paths("commando"),
		},
		{
			"id": "blacksmith",
			"runtime_id": "blacksmith",
			"tagline": "단조 수호 거리제어형",
			"difficulty_stars": 2,
			"skill_icon_paths": [],
			"full_body_live2d_path": LIVE2D_ROOT + "baltor_kohaku_fullbody_proportionfix_idle_loop49_autosprite_asset_v8b_frame0_safe.png",
			"full_body_live2d_sheet_path": LIVE2D_ROOT + "baltor_kohaku_fullbody_proportionfix_idle_loop49_autosprite_asset_v8b_realesrgan_animev3_hq1024_safe.png",
			"full_body_live2d_cols": 7,
			"full_body_live2d_rows": 7,
			"full_body_live2d_count": 49,
			"full_body_live2d_interval": 0.033,
			"full_body_live2d_trim_rect": Rect2(40.0, 0.0, 920.0, 1000.0),
			"full_body_live2d_stage_scale": 1.08,
			"full_body_live2d_stage_x_scale": 0.782,
			"full_body_live2d_stage_y_scale": 1.20,
			"full_body_live2d_stage_x_offset_ratio": 0.0,
			"full_body_live2d_stage_y_offset_ratio": 0.015,
			"name": "발토르",
			"character_name": "코하쿠",
			"class_name": "발토르",
			"role": "단조 수호자",
			"description": "아담한 체구로 낮게 버티며 화로빛 해머와 토르쉴드로 거리를 잡고 공수를 함께 끌어올린다.",
			"special": "토르쉴드·포탑 시너지 모듈",
			"stats": {"속도": 5, "파워": 7, "방어": 5},
			"unlocked": true,
			"unlock_hint": "해금 후 플레이 가능",
			"card_color": Color8(190, 137, 76),
			"glow_color": Color8(235, 180, 95),
			"portrait_path": CARD_ROOT + "baltor_card_kohaku_moe_hammerbehind_l2d_imagegen_v9_cutout_clean_padded.png",
			"card_face_focus": Vector2(0.56, 0.21),
			"card_face_source_height_ratio": 0.35,
			"live2d_preview_still_path": LIVE2D_ROOT + "baltor_kohaku_upperthigh_redraw_idle_loop49_autosprite_v1_frame0_safe.png",
			"live2d_fullframe_sheet_path": LIVE2D_ROOT + "baltor_kohaku_upperthigh_redraw_idle_loop49_autosprite_v1_realesrgan_animev3_hq1024_safe.png",
			"live2d_fullframe_sheet_candidates": [
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_upperthigh_redraw_idle_loop49_autosprite_v1_realesrgan_animev3_hq1024_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(57.0, 9.0, 924.0, 996.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_fullbody_proportionfix_idle_loop49_autosprite_asset_v8b_realesrgan_animev3_hq1024_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(40.0, 0.0, 920.0, 1000.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_hammer_fixed_upperthigh_idle_loop49_autosprite_v2_thigh_visible_runtime_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(0.0, 0.0, 1024.0, 1024.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_hammer_fixed_upperthigh_idle_loop49_autosprite_v2_recommended.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(9.0, 0.0, 927.0, 891.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_short_thigh_menu_idle_loop49_autosprite_hq1024_v5_shortthigh_y850_flickerfix_v2.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(160.0, 70.0, 760.0, 920.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_short_thigh_menu_idle_loop49_autosprite_hq1024_v5_shortthigh_y850_runtime_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(160.0, 70.0, 760.0, 920.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_short_thigh_menu_idle_loop49_assetanim_v4_realesrgan_animev3_hq1024.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(140.0, 0.0, 740.0, 840.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_short_thigh_menu_idle_loop49_assetanim_v4.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(70.0, 0.0, 370.0, 420.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_moe_hammerbehind_idle_loop49_autosprite_v10_realesrgan_animev3_hq1280_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(128.0, 164.0, 1024.0, 1024.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_kohaku_moe_hammerbehind_idle_loop49_autosprite_v10_hq1024_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(102.4, 131.2, 819.2, 819.2),
				},
				{
					"path": CARD_ROOT + "baltor_card_kohaku_moe_hammerbehind_l2d_imagegen_v9_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
					"trim_rect": Rect2(56.0, 60.0, 912.0, 1323.0),
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_ABC_loop147_original_anchor_autosprite_v3_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_ABC_loop147_anchor_autosprite_v2_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_ABC_loop147_autosprite_v1_safe.png",
					"cols": 14,
					"rows": 11,
					"count": 147,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_loop_A_49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_loop_B_49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "baltor_dwarf_maid_gothic_shield_loop_C_49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": CARD_ROOT + "baltor_card_female_dwarf_maid_sailor_gothic_shield_imagegen_v5_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": CARD_ROOT + "baltor_card_back_otaku_anime_imagegen_v3.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
			],
			"live2d_fullframe_cols": 7,
			"live2d_fullframe_rows": 7,
			"live2d_fullframe_count": 49,
			"live2d_fullframe_interval": 0.033,
			"confirm_intro_sheet_path": LIVE2D_ROOT + "baltor_kohaku_select_click_escape_talk_loop98_autosprite_v4_cleanedge_realesrgan_animev3_hq1024_safe.png",
			"confirm_intro_cols": 14,
			"confirm_intro_rows": 7,
			"confirm_intro_count": 98,
			"confirm_intro_interval": 0.020,
			"confirm_intro_min_interval": 0.01,
			"confirm_intro_min_duration": 1.96,
			"confirm_intro_trim_transparent_source": true,
			"confirm_intro_trim_rect": Rect2(54.0, 13.0, 928.0, 988.0),
			"confirm_intro_float_motion_enabled": false,
			"confirm_intro_transition_duration": 0.16,
			"confirm_intro_return_transition_duration": 0.0,
			"confirm_intro_restore_elapsed_mode": "restart",
			"confirm_intro_stage_scale": 1.0,
			"confirm_intro_stage_x_offset_ratio": 0.0,
			"confirm_intro_stage_y_offset_ratio": 0.0,
			"confirm_intro_align_bottom_to_cutline": true,
			"confirm_intro_voice_path": "res://assets/sounds/voice/kohaku_select_confirm_naneun_domangchilggeoya_v4.mp3",
			"confirm_intro_voice_delay": 0.14,
			"confirm_intro_voice_volume_db": -5.0,
			"confirm_intro_exit_flash_enabled": true,
			"confirm_intro_exit_flash_hold": 0.08,
			"confirm_intro_exit_flash_duration": 0.42,
			"confirm_intro_exit_flash_style": "burst",
			"confirm_intro_exit_flash_color": Color(1.0, 0.63, 0.18),
			"confirm_intro_exit_flash_glow_color": Color(1.0, 0.86, 0.36),
			"confirm_intro_exit_flash_secondary_color": Color(1.0, 1.0, 1.0),
			"confirm_intro_exit_flash_field_intensity": 0.95,
			"confirm_intro_exit_flash_card_intensity": 1.0,
			"confirm_intro_exit_flash_white_wash_target": 0.90,
			"confirm_intro_exit_flash_chroma": 0.012,
			"live2d_deform_still": false,
			"live2d_deform_strips": 18,
			"live2d_motion_strength": 0.38,
			"live2d_float_bob": 0.0,
			"live2d_float_sway": 0.0,
			"live2d_float_scale": 0.0,
			"live2d_mouse_response": 0.03,
			"live2d_stage_scale": 0.784,
			"live2d_stage_x_scale": 0.729,
			"live2d_stage_y_scale": 1.15,
			"live2d_stage_y_offset": 0.0,
			"live2d_align_bottom_to_cutline": true,
			"live2d_stage_min_top_ratio": 0.035,
			"live2d_card_cutline_ratio": 0.79,
			"live2d_trim_rect": Rect2(57.0, 9.0, 924.0, 996.0),
			"live2d_trim_transparent_source": true,
			"live2d_trim_padding_ratio": 0.050,
			"live2d_deform_fullframe_sheet": false,
			"live2d_motion_regions_enabled": false,
			"live2d_layers": _layer_paths("baltor"),
		},
		{
			"id": "optimus",
			"runtime_id": "optimus",
			"tagline": "기계 강화 역전 돌파",
			"difficulty_stars": 3,
			"skill_icon_paths": [],
			"full_body_live2d_path": LIVE2D_ROOT + "optimus_fullbody_capsule_mecha_idle_micro_loop49_autosprite_v4_frame0_safe.png",
			"full_body_live2d_sheet_path": LIVE2D_ROOT + "optimus_fullbody_capsule_mecha_idle_micro_loop49_autosprite_v4_realesrgan_animev3_hq1024_safe.png",
			"full_body_live2d_cols": 7,
			"full_body_live2d_rows": 7,
			"full_body_live2d_count": 49,
			"full_body_live2d_interval": 0.033,
			"full_body_live2d_trim_rect": Rect2(168.0, 0.0, 687.0, 1024.0),
			"full_body_live2d_stage_scale": 0.96,
			"full_body_live2d_stage_x_offset_ratio": 0.0,
			"full_body_live2d_stage_y_offset_ratio": 0.01,
			"name": "옵티머스",
			"character_name": "이오",
			"class_name": "옵티머스",
			"role": "카드 사이클러",
			"description": "별개 쿨타임의 카드형 스킬을 굴려 위기의 흐름을 뒤집는다.",
			"special": "스매셔 계열 전용 장비",
			"stats": {"속도": 5, "파워": 7, "방어": 5},
			"unlocked": false,
			"unlock_hint": "해금 후 플레이 가능",
			"card_color": Color8(120, 200, 255),
			"glow_color": Color8(150, 220, 255),
			"portrait_path": CARD_ROOT + "optimus_engineer_glasses_manual_fishnet_l2d_samecrop_cutout_v1.png",
			"card_face_focus": Vector2(0.50, 0.19),
			"card_face_source_height_ratio": 0.32,
			"live2d_preview_still_path": CARD_ROOT + "optimus_engineer_glasses_manual_fishnet_l2d_samecrop_cutout_v1.png",
			"live2d_fullframe_sheet_path": LIVE2D_ROOT + "optimus_io_magenta_onebounce_idle_loop64_autosprite_v5_realesrgan_animev3_hq1536_safe.png",
			"live2d_fullframe_sheet_candidates": [
				{
					"path": LIVE2D_ROOT + "optimus_io_magenta_onebounce_idle_loop64_autosprite_v5_realesrgan_animev3_hq1536_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.050,
					"trim_rect": Rect2(295.0, 27.0, 973.0, 1509.0),
				},
				{
					"path": LIVE2D_ROOT + "optimus_engineer_glasses_manual_fishnet_idle_loop49_autosprite_v1_video_upscaled1088x1472_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(133.0, 37.0, 891.0, 1405.0),
				},
				{
					"path": LIVE2D_ROOT + "optimus_engineer_glasses_manual_fishnet_idle_loop49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(65.0, 16.0, 411.0, 480.0),
				},
				{
					"path": CARD_ROOT + "optimus_engineer_glasses_manual_fishnet_l2d_samecrop_cutout_v1.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
					"trim_rect": Rect2(0.0, 0.0, 1146.0, 1372.0),
				},
				{
					"path": LIVE2D_ROOT + "optimus_capsule_partner_bikini_card_loop49_autosprite_v1_video_upscaled1088x1472.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(0.0, 0.0, 1088.0, 1472.0),
				},
				{
					"path": LIVE2D_ROOT + "optimus_capsule_partner_bikini_card_loop49_autosprite_v1_upscaled1024.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(0.0, 0.0, 1024.0, 1024.0),
				},
				{
					"path": LIVE2D_ROOT + "optimus_capsule_partner_bikini_card_loop49_autosprite_v1.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.033,
					"trim_rect": Rect2(0.0, 0.0, 512.0, 512.0),
				},
				{
					"path": CARD_ROOT + "optimus_capsule_partner_bikini_teaser_imagegen_v1.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": CARD_ROOT + "optimus_card_back_otaku_anime_imagegen_v3.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
			],
			"live2d_fullframe_cols": 8,
			"live2d_fullframe_rows": 8,
			"live2d_fullframe_count": 64,
			"live2d_fullframe_interval": 0.050,
			"live2d_trim_rect": Rect2(295.0, 27.0, 973.0, 1509.0),
			"live2d_trim_transparent_source": true,
			"live2d_trim_sample_frame_limit": 49,
			"live2d_deform_fullframe_sheet": false,
			"live2d_motion_regions_enabled": false,
			"live2d_float_bob": 0.8,
			"live2d_float_sway": 0.0,
			"live2d_float_scale": 0.001,
			"live2d_mouse_response": 0.04,
			"live2d_stage_scale": 0.94,
			"live2d_stage_y_offset": 0.000,
			"live2d_stage_min_top_ratio": 0.035,
			"live2d_card_cutline_ratio": 0.79,
			"confirm_intro_sheet_path": LIVE2D_ROOT + "optimus_io_magenta_talk_nozoom_click_loop64_autosprite_v6_realesrgan_animev3_hq1152_safe.png",
			"confirm_intro_cols": 8,
			"confirm_intro_rows": 8,
			"confirm_intro_count": 64,
			"confirm_intro_interval": 0.060,
			"confirm_intro_min_interval": 0.01,
			"confirm_intro_min_duration": 4.00,
			"confirm_intro_trim_transparent_source": true,
			"confirm_intro_trim_rect": Rect2(230.0, 34.0, 693.0, 1118.0),
			"confirm_intro_float_motion_enabled": false,
			"confirm_intro_transition_duration": 0.16,
			"confirm_intro_stage_scale": 1.0,
			"confirm_intro_stage_x_offset_ratio": 0.0,
			"confirm_intro_stage_y_offset_ratio": 0.0,
			"confirm_intro_voice_path": "res://voice/optimusselect.mp3",
			"confirm_intro_voice_delay": 1.00,
			"confirm_intro_voice_volume_db": -5.0,
			"click_motion_voice_path": "res://voice/optimusselect.mp3",
			"click_motion_voice_delay": 1.00,
			"click_motion_voice_volume_db": -5.0,
			"confirm_intro_exit_flash_enabled": true,
			"confirm_intro_exit_flash_hold": 0.08,
			"confirm_intro_exit_flash_duration": 0.42,
			"confirm_intro_exit_flash_style": "burst",
			"confirm_intro_exit_flash_color": Color(0.42, 0.78, 1.0),
			"confirm_intro_exit_flash_glow_color": Color(0.70, 0.94, 1.0),
			"confirm_intro_exit_flash_secondary_color": Color(1.0, 1.0, 1.0),
			"confirm_intro_exit_flash_field_intensity": 0.95,
			"confirm_intro_exit_flash_card_intensity": 1.0,
			"confirm_intro_exit_flash_white_wash_target": 0.90,
			"confirm_intro_exit_flash_chroma": 0.010,
			"live2d_layers": _layer_paths("optimus"),
		},
		{
			"id": "viper",
			"runtime_id": "viper",
			"tagline": "연속 슬래시 어쌔신",
			"difficulty_stars": 3,
			"skill_icon_paths": [
				"res://assets/sprites/skills/viper_shadow_step_skill_orb.png",
				"res://assets/sprites/skills/viper_marshal_kick_skill_orb.png",
				"res://assets/sprites/skills/viper_blade_rush_skill_orb.png",
			],
			"full_body_live2d_path": LIVE2D_ROOT + "viper_serin_fullbody_closed_suit_idle_loop49_autosprite_asset_v2_realesrgan_animev3_hq1024_frame0_safe.png",
			"full_body_live2d_sheet_path": LIVE2D_ROOT + "viper_serin_fullbody_closed_suit_idle_loop49_autosprite_asset_v2_realesrgan_animev3_hq1024_safe.png",
			"full_body_live2d_cols": 7,
			"full_body_live2d_rows": 7,
			"full_body_live2d_count": 49,
			"full_body_live2d_interval": 0.033,
			"full_body_live2d_trim_rect": Rect2(256.0, 32.0, 568.0, 960.0),
			"full_body_live2d_stage_scale": 0.98,
			"full_body_live2d_stage_x_offset_ratio": 0.0,
			"full_body_live2d_stage_y_offset_ratio": 0.0,
			"name": "바이퍼",
			"character_name": "세린",
			"class_name": "바이퍼",
			"role": "사이버 어쌔신",
			"description": "블레이드와 팬텀킥으로 빈틈을 파고드는 빠른 연계형 캐릭터.",
			"special": "플라즈마 블레이드 전용 스킬트리",
			"stats": {"속도": 4, "파워": 5, "방어": 3},
			"unlocked": true,
			"card_color": Color8(178, 76, 255),
			"glow_color": Color8(190, 90, 255),
			"portrait_path": CARD_ROOT + "viper_card_headhand_blade_lips_pose_imagegen_v4_cutout_clean_padded.png",
			"card_face_focus": Vector2(0.55, 0.21),
			"card_face_source_height_ratio": 0.33,
			"live2d_preview_still_path": CARD_ROOT + "viper_card_headhand_blade_lips_pose_imagegen_v4_cutout_clean_padded.png",
			"live2d_fullframe_sheet_path": LIVE2D_ROOT + "viper_blade_lips_headhand_idle_loop49_autosprite_v1_realesrgan_animev3_hq1536_safe.png",
			"live2d_fullframe_sheet_candidates": [
				{
					"path": LIVE2D_ROOT + "viper_blade_lips_headhand_idle_loop49_autosprite_v1_realesrgan_animev3_hq1536_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(0.0, 0.0, 1536.0, 1536.0),
				},
				{
					"path": LIVE2D_ROOT + "viper_blade_lips_headhand_idle_loop49_autosprite_v1_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_blade_lick_bounce_loop49_autosprite_v2_realesrgan_animev3_hq1536_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(0.0, 0.0, 1536.0, 1536.0),
				},
				{
					"path": LIVE2D_ROOT + "viper_blade_lick_bounce_loop49_autosprite_v2_realesrgan_animev3_hq1536_lingerlick_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(0.0, 0.0, 1536.0, 1536.0),
				},
				{
					"path": LIVE2D_ROOT + "viper_subtle_blade_lick_loop49_autosprite_v3_realesrgan_animev3_hq1536_toppad70_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
					"trim_rect": Rect2(0.0, 0.0, 1536.0, 1536.0),
				},
				{
					"path": LIVE2D_ROOT + "viper_subtle_blade_lick_loop49_autosprite_v3_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_subtle_blade_lick_loop64_autosprite_v3_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_blade_lick_bounce_loop49_autosprite_v2_safe.png",
					"cols": 7,
					"rows": 7,
					"count": 49,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_blade_lick_bounce_loop64_autosprite_v2_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_live2d_headhand_blade_lips_loop64_autosprite_v1_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": CARD_ROOT + "viper_card_headhand_blade_lips_pose_imagegen_v4_cutout_clean_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": LIVE2D_ROOT + "viper_live2d_card_calm_idle_loop64_autosprite_v4_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_live2d_card_blade_swing_loop64_autosprite_v2_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": LIVE2D_ROOT + "viper_live2d_card_blade_swing_asset_64f_autosprite_v1_safe.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": CARD_ROOT + "viper_card_keyvisual_inner_thigh_imagegen_v1_cutout_padded.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
				{
					"path": LIVE2D_ROOT + "viper_live2d_angle_locked_64f_autosprite_v3.png",
					"cols": 8,
					"rows": 8,
					"count": 64,
					"interval": 0.045,
				},
				{
					"path": CARD_ROOT + "viper_card_back_otaku_anime_imagegen_v7.png",
					"cols": 1,
					"rows": 1,
					"count": 1,
					"interval": 0.16,
				},
			],
			"live2d_fullframe_cols": 7,
			"live2d_fullframe_rows": 7,
			"live2d_fullframe_count": 49,
			"live2d_fullframe_interval": 0.045,
			"confirm_intro_sheet_path": LIVE2D_ROOT + "viper_select_confirm_idle_to_mumble_slash_loop98_autosprite_v13_jetpackflame_clean_realesrgan_animev3_hq1152_safe.png",
			"confirm_intro_cols": 14,
			"confirm_intro_rows": 7,
			"confirm_intro_count": 98,
			"confirm_intro_interval": 0.020,
			"confirm_intro_min_interval": 0.01,
			"confirm_intro_min_duration": 1.96,
			"confirm_intro_trim_transparent_source": true,
			"confirm_intro_trim_rect": Rect2(121.0, 67.0, 817.0, 1030.0),
			"confirm_intro_float_motion_enabled": false,
			"confirm_intro_transition_duration": 0.16,
			"confirm_intro_stage_scale": 0.91,
			"confirm_intro_stage_x_offset_ratio": -0.042,
			"confirm_intro_stage_y_offset_ratio": -0.018,
			"confirm_intro_voice_path": "res://assets/sounds/voice/viper_select_confirm_puppy_clean_v7_ang_wang.mp3",
			"confirm_intro_voice_delay": 0.22,
			"confirm_intro_voice_volume_db": -5.0,
			"confirm_intro_exit_flash_enabled": true,
			"confirm_intro_exit_flash_hold": 0.08,
			"confirm_intro_exit_flash_duration": 0.58,
			"confirm_intro_exit_flash_style": "slash",
			"confirm_intro_exit_flash_color": Color(0.72, 0.28, 1.0),
			"confirm_intro_exit_flash_glow_color": Color(0.95, 0.70, 1.0),
			"confirm_intro_exit_flash_secondary_color": Color(1.0, 1.0, 1.0),
			"confirm_intro_exit_flash_field_intensity": 1.05,
			"confirm_intro_exit_flash_card_intensity": 1.0,
			"confirm_intro_exit_flash_white_wash_target": 0.92,
			"confirm_intro_exit_flash_chroma": 0.016,
			"live2d_float_bob": 0.0,
			"live2d_float_sway": 0.0,
			"live2d_float_scale": 0.0,
			"live2d_mouse_response": 0.03,
			"live2d_stage_scale": 1.05,
			"live2d_stage_y_offset": 0.060,
			"live2d_stage_min_top_ratio": 0.035,
			"live2d_card_cutline_ratio": 0.79,
			"live2d_trim_transparent_source": true,
			"live2d_trim_padding_ratio": 0.050,
			"live2d_layers": _layer_paths("viper"),
		},
	]
	return _ordered_characters(characters)


static func _ordered_characters(characters: Array) -> Array:
	var characters_by_id: Dictionary = {}
	var ordered: Array = []
	for character_value in characters:
		if not (character_value is Dictionary):
			continue
		var character: Dictionary = character_value
		characters_by_id[str(character.get("id", ""))] = character
	for character_id in CHARACTER_SELECT_ORDER:
		if characters_by_id.has(character_id):
			ordered.append(characters_by_id[character_id])
	for character_value in characters:
		if not (character_value is Dictionary):
			ordered.append(character_value)
			continue
		var character: Dictionary = character_value
		if not CHARACTER_SELECT_ORDER.has(str(character.get("id", ""))):
			ordered.append(character)
	return ordered


static func _layer_paths(character_key: String) -> Dictionary:
	return {
		"back_hair": LIVE2D_ROOT + character_key + "_back_hair.png",
		"body": LIVE2D_ROOT + character_key + "_body.png",
		"arm_back": LIVE2D_ROOT + character_key + "_arm_back.png",
		"head": LIVE2D_ROOT + character_key + "_head.png",
		"eyes_open": LIVE2D_ROOT + character_key + "_eyes_open.png",
		"eyes_closed": LIVE2D_ROOT + character_key + "_eyes_closed.png",
		"mouth": LIVE2D_ROOT + character_key + "_mouth.png",
		"front_hair": LIVE2D_ROOT + character_key + "_front_hair.png",
		"arm_front": LIVE2D_ROOT + character_key + "_arm_front.png",
		"accessory": LIVE2D_ROOT + character_key + "_accessory.png",
	}


static func _registered_layer_paths(character_key: String) -> Dictionary:
	return {
		"back_hair": LIVE2D_ROOT + character_key + "_registered_back_hair.png",
		"body": LIVE2D_ROOT + character_key + "_registered_body.png",
		"arm_back": LIVE2D_ROOT + character_key + "_registered_arm_back.png",
		"head": LIVE2D_ROOT + character_key + "_registered_head.png",
		"eyes_open": LIVE2D_ROOT + character_key + "_registered_eyes_open.png",
		"eyes_closed": LIVE2D_ROOT + character_key + "_registered_eyes_closed.png",
		"mouth": LIVE2D_ROOT + character_key + "_registered_mouth.png",
		"front_hair": LIVE2D_ROOT + character_key + "_registered_front_hair.png",
		"arm_front": LIVE2D_ROOT + character_key + "_registered_arm_front.png",
		"accessory": LIVE2D_ROOT + character_key + "_registered_accessory.png",
	}


static func _smasher_rig_v6_paths() -> Dictionary:
	return {
		"back_hair": LIVE2D_ROOT + "smasher_live2d_rig_v6_back_hair.png",
		"body": LIVE2D_ROOT + "smasher_live2d_rig_v6_body.png",
		"head": LIVE2D_ROOT + "smasher_live2d_rig_v6_head_face.png",
		"front_hair": LIVE2D_ROOT + "smasher_live2d_rig_v6_front_hair.png",
		"eyes_open": LIVE2D_ROOT + "smasher_live2d_rig_v6_eyes_open.png",
		"eyes_closed": LIVE2D_ROOT + "smasher_live2d_rig_v6_eyes_closed.png",
		"mouth": LIVE2D_ROOT + "smasher_live2d_rig_v6_mouth.png",
		"glasses": LIVE2D_ROOT + "smasher_live2d_rig_v6_glasses.png",
		"arm_front": LIVE2D_ROOT + "smasher_live2d_rig_v6_arm_front.png",
		"racket": LIVE2D_ROOT + "smasher_live2d_rig_v6_racket.png",
		"effects": LIVE2D_ROOT + "smasher_live2d_rig_v6_effects.png",
	}
