extends RefCounted

# Native copy owned by the perk-fusion feature. Keeping these tables complete
# prevents a new UI key from silently degrading to English in non-English
# locales; the coverage smoke compares every locale against the canonical EN
# keys in perk_fusion_localization.gd.

const UI_OVERRIDES := {
	"zh": {
		"card_name": "特性融合",
		"card_description": "选择两个满级特性，将其合成为一个融合特性。",
		"card_detail": "选择两项融合材料。结果会在揭晓动画前锁定。",
		"materials_title": "选择融合材料",
		"materials_subtitle": "请选择两个满级特性。",
		"page": "第 %d / %d 页",
		"cancel": "取消",
		"confirm": "查看融合",
		"selected": "已选择 %d / 2",
		"confirm_title": "确认融合",
		"confirm_subtitle": "所选的两个特性将绑定为一个融合体。",
		"irreversible": "确认后无法返回本次选择。",
		"reselect": "重新选择材料",
		"commit": "执行融合",
		"prob_success": "稳定融合",
		"prob_side": "副作用",
		"prob_core_stable": "融合核已稳定",
		"prob_byproduct": "副产物",
		"animation_title": "融合中……",
		"animation_subtitle": "正在计算已锁定的结果。",
		"material_a": "材料 A",
		"material_b": "材料 B",
		"skip": "按确认键跳过动画",
		"reveal_subtitle": "已生成新的融合记录。",
		"stable_subtitle": "副作用已被稳定，原有性能得以保留。",
		"fusion_default": "融合体",
		"level_fusion": "融合",
		"continue": "按确认键继续",
		"result_stable": "稳定：无副作用",
		"result_success": "保留全部材料选项",
		"result_side": "部分选项受到副作用影响",
		"result_byproduct": "获得新的副产物",
		"penalty_count": "削弱选项记录：%d",
		"deleted_count": "删除选项记录：%d",
		"option_change": "%s · %s：%s → %s（实际削弱 %s%%）",
		"option_deleted": "%s · %s：已删除",
		"byproduct_line": "副产物：%s",
		"byproduct_with_detail": "副产物：%s — %s",
		"byproduct_targets": "适用材料：%s",
		"result_change_summary": "削弱 %d 个选项 · 删除 %d 个",
		"result_byproduct_summary": "副产物：%s",
		"material_level": "%s · Lv.%d",
		"material_effective_level": "%s · Lv.%d → %d",
		"fusion_stats_header": "材料选项",
		"option_preserved": "%s：%s",
		"option_changed_compact": "%s：%s → %s（实际削弱 %s%%）",
		"option_deleted_compact": "%s：%s 已删除",
		"deleted_badge": "已删除",
		"higher_is_better": "数值越高越有利",
		"lower_is_better": "数值越低越有利",
		"no_numeric_options": "没有数值型融合选项",
		"result_fallback": "融合结果已记录。",
		"max_level": "最高等级",
		"unknown_perk": "未知特性",
		"summary": "%s + %s · %s融合",
		"summary_byproducts": " · %d 个副产物",
		"label_stable": "稳定",
		"label_success": "成功",
		"label_side": "副作用",
		"label_byproduct": "副产物",
		"outcome_stable": "稳定融合完成",
		"outcome_success": "融合成功",
		"outcome_side": "发生副作用",
		"outcome_byproduct": "发现副产物",
		"outcome_complete": "融合完成",
	},
	"ja": {
		"card_name": "パーク融合",
		"card_description": "最大レベルのパークを2つ選び、1つの融合パークにします。",
		"card_detail": "融合素材を2つ選択します。結果は公開演出の前に確定します。",
		"materials_title": "融合素材を選択",
		"materials_subtitle": "最大レベルのパークを2つ選んでください。",
		"page": "%d / %d ページ",
		"cancel": "キャンセル",
		"confirm": "融合を確認",
		"selected": "%d / 2 選択",
		"confirm_title": "融合確認",
		"confirm_subtitle": "選択した2つのパークを1つの融合体に結合します。",
		"irreversible": "確定後は今回の選択に戻れません。",
		"reselect": "素材を選び直す",
		"commit": "融合を確定",
		"prob_success": "安定融合",
		"prob_side": "副作用",
		"prob_core_stable": "融合核安定化済み",
		"prob_byproduct": "副産物",
		"animation_title": "融合中…",
		"animation_subtitle": "確定した結果を計算しています。",
		"material_a": "素材 A",
		"material_b": "素材 B",
		"skip": "決定キーで演出をスキップ",
		"reveal_subtitle": "新しい融合記録が作成されました。",
		"stable_subtitle": "副作用が安定化され、元の性能が維持されました。",
		"fusion_default": "融合体",
		"level_fusion": "融合",
		"continue": "決定キーで続行",
		"result_stable": "安定化：副作用なし",
		"result_success": "素材の全オプションを維持",
		"result_side": "一部オプションに副作用を適用",
		"result_byproduct": "新しい副産物を獲得",
		"penalty_count": "弱体化オプション記録：%d",
		"deleted_count": "削除オプション記録：%d",
		"option_change": "%s · %s：%s → %s（実質 %s%% 弱体化）",
		"option_deleted": "%s · %s：削除",
		"byproduct_line": "副産物：%s",
		"byproduct_with_detail": "副産物：%s — %s",
		"byproduct_targets": "適用可能な素材：%s",
		"result_change_summary": "オプション弱体化 %d件 · 削除 %d件",
		"result_byproduct_summary": "副産物：%s",
		"material_level": "%s · Lv.%d",
		"material_effective_level": "%s · Lv.%d → %d",
		"fusion_stats_header": "素材オプション",
		"option_preserved": "%s：%s",
		"option_changed_compact": "%s：%s → %s（実質 %s%% 弱体化）",
		"option_deleted_compact": "%s：%s 削除",
		"deleted_badge": "削除",
		"higher_is_better": "高いほど有利",
		"lower_is_better": "低いほど有利",
		"no_numeric_options": "数値型の融合オプションなし",
		"result_fallback": "融合結果を記録しました。",
		"max_level": "最大レベル",
		"unknown_perk": "不明なパーク",
		"summary": "%s + %s · %s融合",
		"summary_byproducts": " · 副産物 %d個",
		"label_stable": "安定",
		"label_success": "成功",
		"label_side": "副作用",
		"label_byproduct": "副産物",
		"outcome_stable": "安定融合完了",
		"outcome_success": "融合成功",
		"outcome_side": "副作用発生",
		"outcome_byproduct": "副産物発見",
		"outcome_complete": "融合完了",
	},
	"es": {
		"card_name": "Fusión de ventajas",
		"card_description": "Elige dos ventajas al nivel máximo y combínalas en una ventaja de fusión.",
		"card_detail": "Selecciona dos materiales de fusión. El resultado queda fijado antes de la animación.",
		"materials_title": "Elegir materiales de fusión",
		"materials_subtitle": "Elige dos ventajas al nivel máximo.",
		"page": "Página %d / %d",
		"cancel": "Cancelar",
		"confirm": "Revisar fusión",
		"selected": "%d / 2 elegidas",
		"confirm_title": "Confirmar fusión",
		"confirm_subtitle": "Las dos ventajas elegidas se unirán en una sola fusión.",
		"irreversible": "No podrás volver a esta elección después de confirmar.",
		"reselect": "Volver a elegir materiales",
		"commit": "Confirmar fusión",
		"prob_success": "Fusión estable",
		"prob_side": "Efecto adverso",
		"prob_core_stable": "Núcleo estabilizado",
		"prob_byproduct": "Subproducto",
		"animation_title": "Fusionando…",
		"animation_subtitle": "Calculando el resultado ya fijado.",
		"material_a": "Material A",
		"material_b": "Material B",
		"skip": "Confirma para omitir la animación",
		"reveal_subtitle": "Se ha creado un nuevo registro de fusión.",
		"stable_subtitle": "El efecto adverso se estabilizó y se conservaron los efectos originales.",
		"fusion_default": "Fusión",
		"level_fusion": "Fusión",
		"continue": "Confirma para continuar",
		"result_stable": "Estable: sin efecto adverso",
		"result_success": "Se conservaron todas las opciones",
		"result_side": "Algunas opciones recibieron un efecto adverso",
		"result_byproduct": "Nuevo subproducto obtenido",
		"penalty_count": "Opciones reducidas registradas: %d",
		"deleted_count": "Opciones eliminadas registradas: %d",
		"option_change": "%s · %s: %s → %s (reducción real: %s%%)",
		"option_deleted": "%s · %s: eliminada",
		"byproduct_line": "Subproducto: %s",
		"byproduct_with_detail": "Subproducto: %s — %s",
		"byproduct_targets": "Materiales válidos: %s",
		"result_change_summary": "%d opciones reducidas · %d eliminadas",
		"result_byproduct_summary": "Subproductos: %s",
		"material_level": "%s · Nv.%d",
		"material_effective_level": "%s · Nv.%d → %d",
		"fusion_stats_header": "Opciones de los materiales",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (reducción real: %s%%)",
		"option_deleted_compact": "%s: %s eliminada",
		"deleted_badge": "eliminada",
		"higher_is_better": "cuanto más alto, mejor",
		"lower_is_better": "cuanto más bajo, mejor",
		"no_numeric_options": "Sin opción numérica de fusión",
		"result_fallback": "Resultado de fusión registrado.",
		"max_level": "Nivel máximo",
		"unknown_perk": "Ventaja desconocida",
		"summary": "%s + %s · fusión %s",
		"summary_byproducts": " · %d subproducto(s)",
		"label_stable": "estable",
		"label_success": "exitosa",
		"label_side": "efecto adverso",
		"label_byproduct": "subproducto",
		"outcome_stable": "Fusión estable completada",
		"outcome_success": "Fusión exitosa",
		"outcome_side": "Efecto adverso",
		"outcome_byproduct": "Subproducto encontrado",
		"outcome_complete": "Fusión completada",
	},
	"pt-BR": {
		"card_name": "Fusão de vantagens",
		"card_description": "Escolha duas vantagens no nível máximo e combine-as em uma vantagem de fusão.",
		"card_detail": "Selecione dois materiais de fusão. O resultado é fixado antes da animação.",
		"materials_title": "Escolher materiais de fusão",
		"materials_subtitle": "Escolha duas vantagens no nível máximo.",
		"page": "Página %d / %d",
		"cancel": "Cancelar",
		"confirm": "Revisar fusão",
		"selected": "%d / 2 escolhidas",
		"confirm_title": "Confirmar fusão",
		"confirm_subtitle": "As duas vantagens escolhidas serão unidas em uma única fusão.",
		"irreversible": "Não será possível voltar a esta escolha após confirmar.",
		"reselect": "Escolher materiais novamente",
		"commit": "Confirmar fusão",
		"prob_success": "Fusão estável",
		"prob_side": "Efeito colateral",
		"prob_core_stable": "Núcleo estabilizado",
		"prob_byproduct": "Subproduto",
		"animation_title": "Fundindo…",
		"animation_subtitle": "Calculando o resultado já fixado.",
		"material_a": "Material A",
		"material_b": "Material B",
		"skip": "Confirme para pular a animação",
		"reveal_subtitle": "Um novo registro de fusão foi criado.",
		"stable_subtitle": "O efeito colateral foi estabilizado e os efeitos originais foram preservados.",
		"fusion_default": "Fusão",
		"level_fusion": "Fusão",
		"continue": "Confirme para continuar",
		"result_stable": "Estável: sem efeito colateral",
		"result_success": "Todas as opções foram preservadas",
		"result_side": "Algumas opções receberam um efeito colateral",
		"result_byproduct": "Novo subproduto obtido",
		"penalty_count": "Opções reduzidas registradas: %d",
		"deleted_count": "Opções removidas registradas: %d",
		"option_change": "%s · %s: %s → %s (redução real: %s%%)",
		"option_deleted": "%s · %s: removida",
		"byproduct_line": "Subproduto: %s",
		"byproduct_with_detail": "Subproduto: %s — %s",
		"byproduct_targets": "Materiais válidos: %s",
		"result_change_summary": "%d opções reduzidas · %d removidas",
		"result_byproduct_summary": "Subprodutos: %s",
		"material_level": "%s · Nv.%d",
		"material_effective_level": "%s · Nv.%d → %d",
		"fusion_stats_header": "Opções dos materiais",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (redução real: %s%%)",
		"option_deleted_compact": "%s: %s removida",
		"deleted_badge": "removida",
		"higher_is_better": "quanto maior, melhor",
		"lower_is_better": "quanto menor, melhor",
		"no_numeric_options": "Sem opção numérica de fusão",
		"result_fallback": "Resultado da fusão registrado.",
		"max_level": "Nível máximo",
		"unknown_perk": "Vantagem desconhecida",
		"summary": "%s + %s · fusão %s",
		"summary_byproducts": " · %d subproduto(s)",
		"label_stable": "estável",
		"label_success": "bem-sucedida",
		"label_side": "efeito colateral",
		"label_byproduct": "subproduto",
		"outcome_stable": "Fusão estável concluída",
		"outcome_success": "Fusão bem-sucedida",
		"outcome_side": "Efeito colateral",
		"outcome_byproduct": "Subproduto encontrado",
		"outcome_complete": "Fusão concluída",
	},
	"ru": {
		"card_name": "Слияние перков",
		"card_description": "Выберите два перка максимального уровня и объедините их в один перк слияния.",
		"card_detail": "Выберите два материала. Результат фиксируется до анимации раскрытия.",
		"materials_title": "Выбор материалов слияния",
		"materials_subtitle": "Выберите два перка максимального уровня.",
		"page": "Страница %d / %d",
		"cancel": "Отмена",
		"confirm": "Проверить слияние",
		"selected": "Выбрано %d / 2",
		"confirm_title": "Подтвердить слияние",
		"confirm_subtitle": "Два выбранных перка будут связаны в одно слияние.",
		"irreversible": "После подтверждения вернуться к этому выбору нельзя.",
		"reselect": "Выбрать материалы заново",
		"commit": "Выполнить слияние",
		"prob_success": "Стабильное слияние",
		"prob_side": "Побочный эффект",
		"prob_core_stable": "Ядро стабилизировано",
		"prob_byproduct": "Побочный продукт",
		"animation_title": "Слияние…",
		"animation_subtitle": "Вычисляется уже зафиксированный результат.",
		"material_a": "Материал A",
		"material_b": "Материал B",
		"skip": "Подтвердите, чтобы пропустить анимацию",
		"reveal_subtitle": "Создана новая запись о слиянии.",
		"stable_subtitle": "Побочный эффект стабилизирован, исходные свойства сохранены.",
		"fusion_default": "Слияние",
		"level_fusion": "Слияние",
		"continue": "Подтвердите, чтобы продолжить",
		"result_stable": "Стабильно: без побочного эффекта",
		"result_success": "Все свойства материалов сохранены",
		"result_side": "Некоторые свойства получили побочный эффект",
		"result_byproduct": "Получен новый побочный продукт",
		"penalty_count": "Записано ослабленных свойств: %d",
		"deleted_count": "Записано удалённых свойств: %d",
		"option_change": "%s · %s: %s → %s (реальное ослабление %s%%)",
		"option_deleted": "%s · %s: удалено",
		"byproduct_line": "Побочный продукт: %s",
		"byproduct_with_detail": "Побочный продукт: %s — %s",
		"byproduct_targets": "Подходящие материалы: %s",
		"result_change_summary": "Ослаблено свойств: %d · удалено: %d",
		"result_byproduct_summary": "Побочные продукты: %s",
		"material_level": "%s · ур.%d",
		"material_effective_level": "%s · ур.%d → %d",
		"fusion_stats_header": "Свойства материалов",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (ослабление %s%%)",
		"option_deleted_compact": "%s: %s удалено",
		"deleted_badge": "удалено",
		"higher_is_better": "чем выше, тем лучше",
		"lower_is_better": "чем ниже, тем лучше",
		"no_numeric_options": "Нет числовых свойств для слияния",
		"result_fallback": "Результат слияния записан.",
		"max_level": "Максимальный уровень",
		"unknown_perk": "Неизвестный перк",
		"summary": "%s + %s · слияние: %s",
		"summary_byproducts": " · побочных продуктов: %d",
		"label_stable": "стабильное",
		"label_success": "успешное",
		"label_side": "побочный эффект",
		"label_byproduct": "побочный продукт",
		"outcome_stable": "Стабильное слияние завершено",
		"outcome_success": "Слияние успешно",
		"outcome_side": "Побочный эффект",
		"outcome_byproduct": "Найден побочный продукт",
		"outcome_complete": "Слияние завершено",
	},
}

const BYPRODUCT_NAMES := {
	"zh": {
		"overload_circuit": "过载回路", "reverb": "回响", "golden_trajectory": "黄金轨迹", "static_field": "静电场",
		"recycle_protocol": "回收协议", "core_stabilize": "融合核稳定化", "limit_break": "极限突破", "dual_catalyst": "双重催化剂",
	},
	"ja": {
		"overload_circuit": "オーバーロード回路", "reverb": "残響", "golden_trajectory": "黄金軌道", "static_field": "静電場",
		"recycle_protocol": "リサイクルプロトコル", "core_stabilize": "融合核安定化", "limit_break": "リミットブレイク", "dual_catalyst": "二重触媒",
	},
	"es": {
		"overload_circuit": "Circuito de sobrecarga", "reverb": "Reverberación", "golden_trajectory": "Trayectoria dorada", "static_field": "Campo estático",
		"recycle_protocol": "Protocolo de reciclaje", "core_stabilize": "Estabilizador del núcleo", "limit_break": "Ruptura de límites", "dual_catalyst": "Catalizador doble",
	},
	"pt-BR": {
		"overload_circuit": "Circuito de sobrecarga", "reverb": "Reverberação", "golden_trajectory": "Trajetória dourada", "static_field": "Campo estático",
		"recycle_protocol": "Protocolo de reciclagem", "core_stabilize": "Estabilizador do núcleo", "limit_break": "Ruptura de limite", "dual_catalyst": "Catalisador duplo",
	},
	"ru": {
		"overload_circuit": "Цепь перегрузки", "reverb": "Эхо", "golden_trajectory": "Золотая траектория", "static_field": "Статическое поле",
		"recycle_protocol": "Протокол переработки", "core_stabilize": "Стабилизатор ядра", "limit_break": "Прорыв предела", "dual_catalyst": "Двойной катализатор",
	},
}

const BYPRODUCT_DETAILS := {
	"zh": {
		"overload_circuit": "冲刺后的首次回击使球速提高15%",
		"reverb": "使用技能后3秒内移动速度提高25%",
		"golden_trajectory": "每次撞墙获得2金币，每回合最多40金币",
		"static_field": "失分后4秒内首领移动速度降低30%",
		"recycle_protocol": "失分时有25%概率补满全部冲刺令牌",
		"core_stabilize": "稳定下一次融合的副作用",
		"limit_break": "适用材料的有效等级提高1级",
		"dual_catalyst": "下一次符合条件的副产物概率提高15个百分点",
	},
	"ja": {
		"overload_circuit": "ダッシュ後の最初の返球でボール速度+15%",
		"reverb": "スキル使用後3秒間、移動速度+25%",
		"golden_trajectory": "壁反射ごとにゴールド2、1ラウンド最大40",
		"static_field": "失点後4秒間、ボスの移動速度-30%",
		"recycle_protocol": "失点時25%の確率で全ダッシュトークンを補充",
		"core_stabilize": "次の融合1回の副作用を安定化",
		"limit_break": "適用可能な素材の有効レベル+1",
		"dual_catalyst": "次の対象となる副産物抽選率+15ポイント",
	},
	"es": {
		"overload_circuit": "+15% de velocidad de bola en la primera devolución tras un impulso",
		"reverb": "+25% de velocidad de movimiento durante 3 s tras usar una habilidad",
		"golden_trajectory": "+2 de oro por rebote en pared, hasta 40 por ronda",
		"static_field": "-30% de velocidad de movimiento del jefe durante 4 s tras perder un punto",
		"recycle_protocol": "25% de probabilidad de rellenar todos los tokens de impulso al perder un punto",
		"core_stabilize": "estabiliza el efecto adverso de la siguiente fusión",
		"limit_break": "+1 nivel efectivo para los materiales válidos",
		"dual_catalyst": "+15 puntos porcentuales a la siguiente tirada de subproducto válida",
	},
	"pt-BR": {
		"overload_circuit": "+15% de velocidade da bola na primeira rebatida após um impulso",
		"reverb": "+25% de velocidade de movimento por 3 s após usar uma habilidade",
		"golden_trajectory": "+2 de ouro por quique na parede, até 40 por rodada",
		"static_field": "-30% de velocidade de movimento do chefe por 4 s após perder um ponto",
		"recycle_protocol": "25% de chance de recarregar todos os tokens de impulso ao perder um ponto",
		"core_stabilize": "estabiliza o efeito colateral da próxima fusão",
		"limit_break": "+1 nível efetivo para os materiais válidos",
		"dual_catalyst": "+15 pontos percentuais na próxima rolagem de subproduto válida",
	},
	"ru": {
		"overload_circuit": "+15% к скорости мяча при первом ответном ударе после рывка",
		"reverb": "+25% к скорости движения на 3 с после применения навыка",
		"golden_trajectory": "+2 золота за отскок от стены, до 40 за раунд",
		"static_field": "-30% к скорости босса на 4 с после пропущенного очка",
		"recycle_protocol": "25% шанс восполнить все жетоны рывка после пропущенного очка",
		"core_stabilize": "стабилизирует побочный эффект следующего слияния",
		"limit_break": "+1 к эффективному уровню подходящих материалов",
		"dual_catalyst": "+15 процентных пунктов к следующему подходящему шансу побочного продукта",
	},
}

const OPTION_LABELS := {
	"zh": {
		"runtime_skill_bonus": "效果数值", "star_bonus_pct": "星尘加成", "trigger_chance_pct": "触发概率", "invincible_duration_sec": "无敌持续时间",
		"boomerang_knockback_pct": "回旋镖击退", "boomerang_stun_pct": "回旋镖眩晕概率", "boomerang_launch_speed_pct": "回旋镖发射速度", "boomerang_homing_pct": "回旋镖追踪力", "boomerang_spawn_bonus_pct": "回旋镖生成量",
		"auto_dash_token_count": "自动冲刺令牌", "auto_dash_cooldown_sec": "自动冲刺冷却", "attraction_range": "吸引范围", "bonus_perk_chance": "额外特性概率", "chargebag_pct": "充能袋加成", "gauge_preserve_pct": "能量保留量",
		"wall_length_pct": "砖墙长度", "item_cooldown_pct": "道具冷却缩减", "wall_spawn_bonus_pct": "砖墙生成量", "gold_bonus_pct": "金币加成", "double_spawn_pct": "双倍生成概率", "shard_count": "破片数量", "knockback_level": "击退等级",
		"gauge_cost": "能量消耗", "fuel_bonus_flat": "燃料加成", "gauge_gain_pct": "能量获取量", "negate_chance_pct": "伤害免除概率", "aipill_gauge_reduction": "AI药丸能量缩减", "aipill_spawn_bonus_pct": "AI药丸生成量",
		"throw_speed_pct": "投掷速度", "explosion_range_pct": "爆炸范围", "smoke_duration_pct": "烟幕持续时间", "prep_reduction_pct": "准备时间缩减", "rainbow_glove_trigger_chance_pct": "彩虹手套触发概率", "rainbow_glove_cooldown_reduction_pct": "彩虹手套冷却缩减",
		"knee_charge_pct": "护膝充能量", "soul_burst_gauge_cost": "灵魂爆发能量消耗", "stun_resist_pct": "眩晕抗性", "knockback_resist_pct": "击退抗性", "mist_trigger_chance_pct": "毒雾触发概率", "mist_duration_sec": "毒雾持续时间", "perk_level_bonus": "特性有效等级加成", "sage_speed_penalty_pct": "贤者戒指速度惩罚", "sage_body_penalty_pct": "贤者戒指体型惩罚",
	},
	"ja": {
		"runtime_skill_bonus": "効果値", "star_bonus_pct": "スターダストボーナス", "trigger_chance_pct": "発動率", "invincible_duration_sec": "無敵時間",
		"boomerang_knockback_pct": "ブーメランノックバック", "boomerang_stun_pct": "ブーメラン気絶率", "boomerang_launch_speed_pct": "ブーメラン射出速度", "boomerang_homing_pct": "ブーメラン誘導力", "boomerang_spawn_bonus_pct": "ブーメラン生成量",
		"auto_dash_token_count": "自動ダッシュトークン", "auto_dash_cooldown_sec": "自動ダッシュ再使用時間", "attraction_range": "吸引範囲", "bonus_perk_chance": "追加パーク率", "chargebag_pct": "チャージバッグボーナス", "gauge_preserve_pct": "ゲージ保持量",
		"wall_length_pct": "レンガ壁の長さ", "item_cooldown_pct": "アイテム再使用短縮", "wall_spawn_bonus_pct": "レンガ壁生成量", "gold_bonus_pct": "ゴールドボーナス", "double_spawn_pct": "二重生成率", "shard_count": "破片数", "knockback_level": "ノックバック段階",
		"gauge_cost": "ゲージ消費量", "fuel_bonus_flat": "燃料ボーナス", "gauge_gain_pct": "ゲージ獲得量", "negate_chance_pct": "無効化率", "aipill_gauge_reduction": "AIピルのゲージ軽減", "aipill_spawn_bonus_pct": "AIピル生成量",
		"throw_speed_pct": "投てき速度", "explosion_range_pct": "爆発範囲", "smoke_duration_pct": "煙幕持続時間", "prep_reduction_pct": "準備時間短縮", "rainbow_glove_trigger_chance_pct": "レインボーグローブ発動率", "rainbow_glove_cooldown_reduction_pct": "レインボーグローブ再使用短縮",
		"knee_charge_pct": "ニーパッド充填量", "soul_burst_gauge_cost": "ソウルバーストのゲージ消費量", "stun_resist_pct": "気絶耐性", "knockback_resist_pct": "ノックバック耐性", "mist_trigger_chance_pct": "毒霧発動率", "mist_duration_sec": "毒霧持続時間", "perk_level_bonus": "パーク有効レベルボーナス", "sage_speed_penalty_pct": "賢者の指輪の速度ペナルティ", "sage_body_penalty_pct": "賢者の指輪の体格ペナルティ",
	},
	"es": {
		"runtime_skill_bonus": "Valor del efecto", "star_bonus_pct": "Bonificación de polvo estelar", "trigger_chance_pct": "Probabilidad de activación", "invincible_duration_sec": "Duración de invencibilidad",
		"boomerang_knockback_pct": "Empuje del bumerán", "boomerang_stun_pct": "Probabilidad de aturdir del bumerán", "boomerang_launch_speed_pct": "Velocidad de lanzamiento del bumerán", "boomerang_homing_pct": "Guiado del bumerán", "boomerang_spawn_bonus_pct": "Cantidad de bumeranes",
		"auto_dash_token_count": "Tokens de impulso automático", "auto_dash_cooldown_sec": "Recarga del impulso automático", "attraction_range": "Alcance de atracción", "bonus_perk_chance": "Probabilidad de ventaja adicional", "chargebag_pct": "Bonificación de bolsa de carga", "gauge_preserve_pct": "Energía conservada",
		"wall_length_pct": "Longitud del muro", "item_cooldown_pct": "Reducción de recarga de objetos", "wall_spawn_bonus_pct": "Cantidad de muros", "gold_bonus_pct": "Bonificación de oro", "double_spawn_pct": "Probabilidad de aparición doble", "shard_count": "Cantidad de fragmentos", "knockback_level": "Nivel de empuje",
		"gauge_cost": "Coste de energía", "fuel_bonus_flat": "Bonificación de combustible", "gauge_gain_pct": "Energía obtenida", "negate_chance_pct": "Probabilidad de anular daño", "aipill_gauge_reduction": "Reducción de energía de la píldora IA", "aipill_spawn_bonus_pct": "Cantidad de píldoras IA",
		"throw_speed_pct": "Velocidad de lanzamiento", "explosion_range_pct": "Alcance de explosión", "smoke_duration_pct": "Duración del humo", "prep_reduction_pct": "Reducción de preparación", "rainbow_glove_trigger_chance_pct": "Activación del guante arcoíris", "rainbow_glove_cooldown_reduction_pct": "Reducción de recarga del guante arcoíris",
		"knee_charge_pct": "Carga de rodillera", "soul_burst_gauge_cost": "Coste de energía de Explosión de alma", "stun_resist_pct": "Resistencia al aturdimiento", "knockback_resist_pct": "Resistencia al empuje", "mist_trigger_chance_pct": "Activación de niebla tóxica", "mist_duration_sec": "Duración de niebla tóxica", "perk_level_bonus": "Bonificación de nivel efectivo", "sage_speed_penalty_pct": "Penalización de velocidad del anillo sabio", "sage_body_penalty_pct": "Penalización de tamaño del anillo sabio",
	},
	"pt-BR": {
		"runtime_skill_bonus": "Valor do efeito", "star_bonus_pct": "Bônus de poeira estelar", "trigger_chance_pct": "Chance de ativação", "invincible_duration_sec": "Duração da invencibilidade",
		"boomerang_knockback_pct": "Repulsão do bumerangue", "boomerang_stun_pct": "Chance de atordoar do bumerangue", "boomerang_launch_speed_pct": "Velocidade de lançamento do bumerangue", "boomerang_homing_pct": "Rastreamento do bumerangue", "boomerang_spawn_bonus_pct": "Quantidade de bumerangues",
		"auto_dash_token_count": "Tokens de impulso automático", "auto_dash_cooldown_sec": "Recarga do impulso automático", "attraction_range": "Alcance de atração", "bonus_perk_chance": "Chance de vantagem extra", "chargebag_pct": "Bônus da bolsa de carga", "gauge_preserve_pct": "Energia preservada",
		"wall_length_pct": "Comprimento da parede", "item_cooldown_pct": "Redução de recarga de itens", "wall_spawn_bonus_pct": "Quantidade de paredes", "gold_bonus_pct": "Bônus de ouro", "double_spawn_pct": "Chance de surgimento duplo", "shard_count": "Quantidade de fragmentos", "knockback_level": "Nível de repulsão",
		"gauge_cost": "Custo de energia", "fuel_bonus_flat": "Bônus de combustível", "gauge_gain_pct": "Energia obtida", "negate_chance_pct": "Chance de anular dano", "aipill_gauge_reduction": "Redução de energia da pílula IA", "aipill_spawn_bonus_pct": "Quantidade de pílulas IA",
		"throw_speed_pct": "Velocidade de arremesso", "explosion_range_pct": "Alcance da explosão", "smoke_duration_pct": "Duração da fumaça", "prep_reduction_pct": "Redução de preparo", "rainbow_glove_trigger_chance_pct": "Ativação da luva arco-íris", "rainbow_glove_cooldown_reduction_pct": "Redução de recarga da luva arco-íris",
		"knee_charge_pct": "Carga da joelheira", "soul_burst_gauge_cost": "Custo de energia da Explosão da alma", "stun_resist_pct": "Resistência a atordoamento", "knockback_resist_pct": "Resistência a repulsão", "mist_trigger_chance_pct": "Ativação da névoa tóxica", "mist_duration_sec": "Duração da névoa tóxica", "perk_level_bonus": "Bônus de nível efetivo", "sage_speed_penalty_pct": "Penalidade de velocidade do anel sábio", "sage_body_penalty_pct": "Penalidade de tamanho do anel sábio",
	},
	"ru": {
		"runtime_skill_bonus": "Величина эффекта", "star_bonus_pct": "Бонус звёздной пыли", "trigger_chance_pct": "Шанс срабатывания", "invincible_duration_sec": "Длительность неуязвимости",
		"boomerang_knockback_pct": "Отбрасывание бумеранга", "boomerang_stun_pct": "Шанс оглушения бумерангом", "boomerang_launch_speed_pct": "Скорость запуска бумеранга", "boomerang_homing_pct": "Наведение бумеранга", "boomerang_spawn_bonus_pct": "Количество бумерангов",
		"auto_dash_token_count": "Жетоны авто-рывка", "auto_dash_cooldown_sec": "Перезарядка авто-рывка", "attraction_range": "Радиус притяжения", "bonus_perk_chance": "Шанс дополнительного перка", "chargebag_pct": "Бонус сумки заряда", "gauge_preserve_pct": "Сохранённая энергия",
		"wall_length_pct": "Длина стены", "item_cooldown_pct": "Сокращение перезарядки предметов", "wall_spawn_bonus_pct": "Количество стен", "gold_bonus_pct": "Бонус золота", "double_spawn_pct": "Шанс двойного появления", "shard_count": "Количество осколков", "knockback_level": "Уровень отбрасывания",
		"gauge_cost": "Расход энергии", "fuel_bonus_flat": "Бонус топлива", "gauge_gain_pct": "Получение энергии", "negate_chance_pct": "Шанс отмены урона", "aipill_gauge_reduction": "Снижение расхода энергии ИИ-таблетки", "aipill_spawn_bonus_pct": "Количество ИИ-таблеток",
		"throw_speed_pct": "Скорость броска", "explosion_range_pct": "Радиус взрыва", "smoke_duration_pct": "Длительность дыма", "prep_reduction_pct": "Сокращение подготовки", "rainbow_glove_trigger_chance_pct": "Срабатывание радужной перчатки", "rainbow_glove_cooldown_reduction_pct": "Сокращение перезарядки радужной перчатки",
		"knee_charge_pct": "Заряд наколенника", "soul_burst_gauge_cost": "Расход энергии Взрыва души", "stun_resist_pct": "Сопротивление оглушению", "knockback_resist_pct": "Сопротивление отбрасыванию", "mist_trigger_chance_pct": "Срабатывание ядовитого тумана", "mist_duration_sec": "Длительность ядовитого тумана", "perk_level_bonus": "Бонус эффективного уровня", "sage_speed_penalty_pct": "Штраф скорости кольца мудреца", "sage_body_penalty_pct": "Штраф размера кольца мудреца",
	},
}

# Units are keyed by semantic family, not option id, so every locale owns the
# visible suffixes without duplicating the option-label table.
const OPTION_UNITS := {
	"ko": {"seconds": "초", "count": "개", "levels": "단계", "perk_level": "Lv.", "pixels": "px", "gauge": "게이지", "fuel": "연료"},
	"en": {"seconds": "s", "count": "", "levels": "levels", "perk_level": "Lv.", "pixels": "px", "gauge": "gauge", "fuel": "fuel"},
	"zh": {"seconds": "秒", "count": "个", "levels": "级", "perk_level": "级", "pixels": "像素", "gauge": "能量", "fuel": "燃料"},
	"ja": {"seconds": "秒", "count": "個", "levels": "段階", "perk_level": "Lv.", "pixels": "px", "gauge": "ゲージ", "fuel": "燃料"},
	"es": {"seconds": "s", "count": "uds.", "levels": "niveles", "perk_level": "Nv.", "pixels": "px", "gauge": "energía", "fuel": "combustible"},
	"pt-BR": {"seconds": "s", "count": "un.", "levels": "níveis", "perk_level": "Nv.", "pixels": "px", "gauge": "energia", "fuel": "combustível"},
	"ru": {"seconds": "с", "count": "шт.", "levels": "ур.", "perk_level": "ур.", "pixels": "пкс", "gauge": "энергия", "fuel": "топливо"},
}
