extends RefCounted

# Native copy owned by the perk-fusion feature. Keeping these tables complete
# prevents a new UI key from silently degrading to English in non-English
# locales; the coverage smoke compares every locale against the canonical EN
# keys in perk_fusion_localization.gd.

const UI_OVERRIDES := {
	"zh": {
		"card_name": "特性融合",
		"card_description": "选择两个满级特性，将其合成为一个融合特性。",
		"card_detail": "选择两项融合材料。结果会在揭晓动画前锁定。",
		"materials_title": "选择融合材料",
		"materials_subtitle": "请选择两个满级特性。",
		"page": "第 %d / %d 页",
		"cancel": "取消",
		"confirm": "查看融合",
		"selected": "已选择 %d / 2",
		"confirm_title": "确认融合",
		"confirm_subtitle": "所选的两个特性将绑定为一个融合体。",
		"irreversible": "确认后无法返回本次选择。",
		"reselect": "重新选择材料",
		"commit": "执行融合",
		"prob_success": "维持原状",
		"prob_side": "走火入魔",
		"prob_core_stable": "融合核已稳定",
		"prob_byproduct": "上乘武功",
		"prob_byproduct_count": "上乘武功 +%d",
		"prob_rare_slot": "稀有槽 %d%%",
		"animation_title": "融合中……",
		"animation_subtitle": "正在计算已锁定的结果。",
		"material_a": "材料 A",
		"material_b": "材料 B",
		"skip": "按确认键跳过动画",
		"reveal_subtitle": "已生成新的融合记录。",
		"stable_subtitle": "走火入魔已被平息，原有性能得以保留。",
		"fusion_default": "融合体",
		"level_fusion": "融合",
		"continue": "按确认键继续",
		"result_stable": "稳定：未发生走火入魔",
		"result_success": "保留全部材料选项",
		"result_side": "走火入魔使部分选项减弱",
		"result_byproduct": "习得新的上乘武功",
		"penalty_count": "削弱选项记录：%d",
		"deleted_count": "删除选项记录：%d",
		"option_change": "%s · %s：%s → %s（实际削弱 %s%%）",
		"option_deleted": "%s · %s：已删除",
		"byproduct_line": "上乘武功：%s",
		"byproduct_with_detail": "上乘武功：%s — %s",
		"byproduct_targets": "适用材料：%s",
		"result_change_summary": "削弱 %d 个选项 · 删除 %d 个",
		"result_byproduct_summary": "上乘武功：%s",
		"material_level": "%s · Lv.%d",
		"material_effective_level": "%s · Lv.%d → %d",
		"fusion_stats_header": "材料选项",
		"option_preserved": "%s：%s",
		"option_changed_compact": "%s：%s → %s（实际削弱 %s%%）",
		"option_deleted_compact": "%s：%s 已删除",
		"deleted_badge": "已删除",
		"higher_is_better": "数值越高越有利",
		"lower_is_better": "数值越低越有利",
		"no_numeric_options": "没有数值型融合选项",
		"result_fallback": "融合结果已记录。",
		"max_level": "最高等级",
		"unknown_perk": "未知特性",
		"summary": "%s + %s · %s融合",
		"summary_byproducts": " · 上乘武功：%d",
		"label_stable": "稳定",
		"label_success": "成功",
		"label_side": "走火入魔",
		"label_byproduct": "上乘武功",
		"outcome_stable": "稳定融合完成",
		"outcome_success": "融合成功",
		"outcome_side": "走火入魔",
		"outcome_byproduct": "上乘武功显现",
		"outcome_complete": "融合完成",
	},
	"ja": {
		"card_name": "パーク融合",
		"card_description": "最大レベルのパークを2つ選び、1つの融合パークにします。",
		"card_detail": "融合素材を2つ選択します。結果は公開演出の前に確定します。",
		"materials_title": "融合素材を選択",
		"materials_subtitle": "最大レベルのパークを2つ選んでください。",
		"page": "%d / %d ページ",
		"cancel": "キャンセル",
		"confirm": "融合を確認",
		"selected": "%d / 2 選択",
		"confirm_title": "融合確認",
		"confirm_subtitle": "選択した2つのパークを1つの融合体に結合します。",
		"irreversible": "確定後は今回の選択に戻れません。",
		"reselect": "素材を選び直す",
		"commit": "融合を確定",
		"prob_success": "維持",
		"prob_side": "走火入魔",
		"prob_core_stable": "融合核安定化済み",
		"prob_byproduct": "上乗武功",
		"prob_byproduct_count": "上乗武功 +%d",
		"prob_rare_slot": "希少枠 %d%%",
		"animation_title": "融合中…",
		"animation_subtitle": "確定した結果を計算しています。",
		"material_a": "素材 A",
		"material_b": "素材 B",
		"skip": "決定キーで演出をスキップ",
		"reveal_subtitle": "新しい融合記録が作成されました。",
		"stable_subtitle": "走火入魔が鎮まり、元の性能が維持されました。",
		"fusion_default": "融合体",
		"level_fusion": "融合",
		"continue": "決定キーで続行",
		"result_stable": "安定化：走火入魔なし",
		"result_success": "素材の全オプションを維持",
		"result_side": "走火入魔で一部オプションが弱体化",
		"result_byproduct": "新しい上乗武功を習得",
		"penalty_count": "弱体化オプション記録：%d",
		"deleted_count": "削除オプション記録：%d",
		"option_change": "%s · %s：%s → %s（実質 %s%% 弱体化）",
		"option_deleted": "%s · %s：削除",
		"byproduct_line": "上乗武功：%s",
		"byproduct_with_detail": "上乗武功：%s — %s",
		"byproduct_targets": "適用可能な素材：%s",
		"result_change_summary": "オプション弱体化 %d件 · 削除 %d件",
		"result_byproduct_summary": "上乗武功：%s",
		"material_level": "%s · Lv.%d",
		"material_effective_level": "%s · Lv.%d → %d",
		"fusion_stats_header": "素材オプション",
		"option_preserved": "%s：%s",
		"option_changed_compact": "%s：%s → %s（実質 %s%% 弱体化）",
		"option_deleted_compact": "%s：%s 削除",
		"deleted_badge": "削除",
		"higher_is_better": "高いほど有利",
		"lower_is_better": "低いほど有利",
		"no_numeric_options": "数値型の融合オプションなし",
		"result_fallback": "融合結果を記録しました。",
		"max_level": "最大レベル",
		"unknown_perk": "不明なパーク",
		"summary": "%s + %s · %s融合",
		"summary_byproducts": " · 上乗武功：%d",
		"label_stable": "安定",
		"label_success": "成功",
		"label_side": "走火入魔",
		"label_byproduct": "上乗武功",
		"outcome_stable": "安定融合完了",
		"outcome_success": "融合成功",
		"outcome_side": "走火入魔",
		"outcome_byproduct": "上乗武功を習得",
		"outcome_complete": "融合完了",
	},
	"es": {
		"card_name": "Fusión de ventajas",
		"card_description": "Elige dos ventajas al nivel máximo y combínalas en una ventaja de fusión.",
		"card_detail": "Selecciona dos materiales de fusión. El resultado queda fijado antes de la animación.",
		"materials_title": "Elegir materiales de fusión",
		"materials_subtitle": "Elige dos ventajas al nivel máximo.",
		"page": "Página %d / %d",
		"cancel": "Cancelar",
		"confirm": "Revisar fusión",
		"selected": "%d / 2 elegidas",
		"confirm_title": "Confirmar fusión",
		"confirm_subtitle": "Las dos ventajas elegidas se unirán en una sola fusión.",
		"irreversible": "No podrás volver a esta elección después de confirmar.",
		"reselect": "Volver a elegir materiales",
		"commit": "Confirmar fusión",
		"prob_success": "Conservado",
		"prob_side": "Desviación del qi",
		"prob_core_stable": "Núcleo estabilizado",
		"prob_byproduct": "Arte marcial superior",
		"prob_byproduct_count": "Arte marcial superior +%d",
		"prob_rare_slot": "Ranura rara %d%%",
		"animation_title": "Fusionando…",
		"animation_subtitle": "Calculando el resultado ya fijado.",
		"material_a": "Material A",
		"material_b": "Material B",
		"skip": "Confirma para omitir la animación",
		"reveal_subtitle": "Se ha creado un nuevo registro de fusión.",
		"stable_subtitle": "La desviación del qi se estabilizó y se conservaron los efectos originales.",
		"fusion_default": "Fusión",
		"level_fusion": "Fusión",
		"continue": "Confirma para continuar",
		"result_stable": "Estable: sin desviación del qi",
		"result_success": "Se conservaron todas las opciones",
		"result_side": "La desviación del qi debilitó algunas opciones",
		"result_byproduct": "Nuevo arte marcial superior adquirido",
		"penalty_count": "Opciones reducidas registradas: %d",
		"deleted_count": "Opciones eliminadas registradas: %d",
		"option_change": "%s · %s: %s → %s (reducción real: %s%%)",
		"option_deleted": "%s · %s: eliminada",
		"byproduct_line": "Arte marcial superior: %s",
		"byproduct_with_detail": "Arte marcial superior: %s — %s",
		"byproduct_targets": "Materiales válidos: %s",
		"result_change_summary": "%d opciones reducidas · %d eliminadas",
		"result_byproduct_summary": "Artes marciales superiores: %s",
		"material_level": "%s · Nv.%d",
		"material_effective_level": "%s · Nv.%d → %d",
		"fusion_stats_header": "Opciones de los materiales",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (reducción real: %s%%)",
		"option_deleted_compact": "%s: %s eliminada",
		"deleted_badge": "eliminada",
		"higher_is_better": "cuanto más alto, mejor",
		"lower_is_better": "cuanto más bajo, mejor",
		"no_numeric_options": "Sin opción numérica de fusión",
		"result_fallback": "Resultado de fusión registrado.",
		"max_level": "Nivel máximo",
		"unknown_perk": "Ventaja desconocida",
		"summary": "%s + %s · fusión %s",
		"summary_byproducts": " · Artes marciales superiores: %d",
		"label_stable": "estable",
		"label_success": "exitosa",
		"label_side": "desviación del qi",
		"label_byproduct": "arte marcial superior",
		"outcome_stable": "Fusión estable completada",
		"outcome_success": "Fusión exitosa",
		"outcome_side": "Desviación del qi",
		"outcome_byproduct": "Arte marcial superior adquirido",
		"outcome_complete": "Fusión completada",
	},
	"pt-BR": {
		"card_name": "Fusão de vantagens",
		"card_description": "Escolha duas vantagens no nível máximo e combine-as em uma vantagem de fusão.",
		"card_detail": "Selecione dois materiais de fusão. O resultado é fixado antes da animação.",
		"materials_title": "Escolher materiais de fusão",
		"materials_subtitle": "Escolha duas vantagens no nível máximo.",
		"page": "Página %d / %d",
		"cancel": "Cancelar",
		"confirm": "Revisar fusão",
		"selected": "%d / 2 escolhidas",
		"confirm_title": "Confirmar fusão",
		"confirm_subtitle": "As duas vantagens escolhidas serão unidas em uma única fusão.",
		"irreversible": "Não será possível voltar a esta escolha após confirmar.",
		"reselect": "Escolher materiais novamente",
		"commit": "Confirmar fusão",
		"prob_success": "Mantido",
		"prob_side": "Desvio de qi",
		"prob_core_stable": "Núcleo estabilizado",
		"prob_byproduct": "Arte marcial superior",
		"prob_byproduct_count": "Arte marcial superior +%d",
		"prob_rare_slot": "Espaço raro %d%%",
		"animation_title": "Fundindo…",
		"animation_subtitle": "Calculando o resultado já fixado.",
		"material_a": "Material A",
		"material_b": "Material B",
		"skip": "Confirme para pular a animação",
		"reveal_subtitle": "Um novo registro de fusão foi criado.",
		"stable_subtitle": "O desvio de qi foi estabilizado e os efeitos originais foram preservados.",
		"fusion_default": "Fusão",
		"level_fusion": "Fusão",
		"continue": "Confirme para continuar",
		"result_stable": "Estável: sem desvio de qi",
		"result_success": "Todas as opções foram preservadas",
		"result_side": "O desvio de qi enfraqueceu algumas opções",
		"result_byproduct": "Nova arte marcial superior adquirida",
		"penalty_count": "Opções reduzidas registradas: %d",
		"deleted_count": "Opções removidas registradas: %d",
		"option_change": "%s · %s: %s → %s (redução real: %s%%)",
		"option_deleted": "%s · %s: removida",
		"byproduct_line": "Arte marcial superior: %s",
		"byproduct_with_detail": "Arte marcial superior: %s — %s",
		"byproduct_targets": "Materiais válidos: %s",
		"result_change_summary": "%d opções reduzidas · %d removidas",
		"result_byproduct_summary": "Artes marciais superiores: %s",
		"material_level": "%s · Nv.%d",
		"material_effective_level": "%s · Nv.%d → %d",
		"fusion_stats_header": "Opções dos materiais",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (redução real: %s%%)",
		"option_deleted_compact": "%s: %s removida",
		"deleted_badge": "removida",
		"higher_is_better": "quanto maior, melhor",
		"lower_is_better": "quanto menor, melhor",
		"no_numeric_options": "Sem opção numérica de fusão",
		"result_fallback": "Resultado da fusão registrado.",
		"max_level": "Nível máximo",
		"unknown_perk": "Vantagem desconhecida",
		"summary": "%s + %s · fusão %s",
		"summary_byproducts": " · Artes marciais superiores: %d",
		"label_stable": "estável",
		"label_success": "bem-sucedida",
		"label_side": "desvio de qi",
		"label_byproduct": "arte marcial superior",
		"outcome_stable": "Fusão estável concluída",
		"outcome_success": "Fusão bem-sucedida",
		"outcome_side": "Desvio de qi",
		"outcome_byproduct": "Arte marcial superior adquirida",
		"outcome_complete": "Fusão concluída",
	},
	"ru": {
		"card_name": "Слияние перков",
		"card_description": "Выберите два перка максимального уровня и объедините их в один перк слияния.",
		"card_detail": "Выберите два материала. Результат фиксируется до анимации раскрытия.",
		"materials_title": "Выбор материалов слияния",
		"materials_subtitle": "Выберите два перка максимального уровня.",
		"page": "Страница %d / %d",
		"cancel": "Отмена",
		"confirm": "Проверить слияние",
		"selected": "Выбрано %d / 2",
		"confirm_title": "Подтвердить слияние",
		"confirm_subtitle": "Два выбранных перка будут связаны в одно слияние.",
		"irreversible": "После подтверждения вернуться к этому выбору нельзя.",
		"reselect": "Выбрать материалы заново",
		"commit": "Выполнить слияние",
		"prob_success": "Сохранение",
		"prob_side": "Отклонение ци",
		"prob_core_stable": "Ядро стабилизировано",
		"prob_byproduct": "Высшее боевое искусство",
		"prob_byproduct_count": "Высшее боевое искусство +%d",
		"prob_rare_slot": "Редкий слот %d%%",
		"animation_title": "Слияние…",
		"animation_subtitle": "Вычисляется уже зафиксированный результат.",
		"material_a": "Материал A",
		"material_b": "Материал B",
		"skip": "Подтвердите, чтобы пропустить анимацию",
		"reveal_subtitle": "Создана новая запись о слиянии.",
		"stable_subtitle": "Отклонение ци стабилизировано, исходные свойства сохранены.",
		"fusion_default": "Слияние",
		"level_fusion": "Слияние",
		"continue": "Подтвердите, чтобы продолжить",
		"result_stable": "Стабильно: без отклонения ци",
		"result_success": "Все свойства материалов сохранены",
		"result_side": "Отклонение ци ослабило некоторые свойства",
		"result_byproduct": "Получено новое высшее боевое искусство",
		"penalty_count": "Записано ослабленных свойств: %d",
		"deleted_count": "Записано удалённых свойств: %d",
		"option_change": "%s · %s: %s → %s (реальное ослабление %s%%)",
		"option_deleted": "%s · %s: удалено",
		"byproduct_line": "Высшее боевое искусство: %s",
		"byproduct_with_detail": "Высшее боевое искусство: %s — %s",
		"byproduct_targets": "Подходящие материалы: %s",
		"result_change_summary": "Ослаблено свойств: %d · удалено: %d",
		"result_byproduct_summary": "Высшие боевые искусства: %s",
		"material_level": "%s · ур.%d",
		"material_effective_level": "%s · ур.%d → %d",
		"fusion_stats_header": "Свойства материалов",
		"option_preserved": "%s: %s",
		"option_changed_compact": "%s: %s → %s (ослабление %s%%)",
		"option_deleted_compact": "%s: %s удалено",
		"deleted_badge": "удалено",
		"higher_is_better": "чем выше, тем лучше",
		"lower_is_better": "чем ниже, тем лучше",
		"no_numeric_options": "Нет числовых свойств для слияния",
		"result_fallback": "Результат слияния записан.",
		"max_level": "Максимальный уровень",
		"unknown_perk": "Неизвестный перк",
		"summary": "%s + %s · слияние: %s",
		"summary_byproducts": " · высших боевых искусств: %d",
		"label_stable": "стабильное",
		"label_success": "успешное",
		"label_side": "отклонение ци",
		"label_byproduct": "высшее боевое искусство",
		"outcome_stable": "Стабильное слияние завершено",
		"outcome_success": "Слияние успешно",
		"outcome_side": "Отклонение ци",
		"outcome_byproduct": "Обретено высшее боевое искусство",
		"outcome_complete": "Слияние завершено",
	},
}

const BYPRODUCT_NAMES := {
	"zh": {
		"overload_circuit": "雷霆推进", "reverb": "回响", "golden_trajectory": "黄金轨迹", "static_field": "静电场",
		"recycle_protocol": "绝处逢生", "meridian_expand": "经脉扩展", "gravitybelt": "刹那身法", "smartphone": "应变诀", "core_stabilize": "融合核稳定化", "limit_break": "极限突破", "dual_catalyst": "双重催化剂", "linked_arsenal": "连环兵藏", "returning_light_step": "回光幻步", "spellbreaker_guard": "破法护身诀",
	},
	"ja": {
		"overload_circuit": "雷迅推進", "reverb": "残響", "golden_trajectory": "黄金軌道", "static_field": "静電場",
		"recycle_protocol": "絶処逢生", "meridian_expand": "経脈拡張", "gravitybelt": "刹那身法", "smartphone": "応変訣", "core_stabilize": "融合核安定化", "limit_break": "リミットブレイク", "dual_catalyst": "二重触媒", "linked_arsenal": "連環兵蔵", "returning_light_step": "回光幻歩", "spellbreaker_guard": "破法護身訣",
	},
	"es": {
		"overload_circuit": "Impulso del rayo", "reverb": "Reverberación", "golden_trajectory": "Trayectoria dorada", "static_field": "Campo estático",
		"recycle_protocol": "Renacer al límite", "meridian_expand": "Expansión de meridianos", "gravitybelt": "Arte Corporal Instantánea", "smartphone": "Arte de Adaptación", "core_stabilize": "Estabilizador del núcleo", "limit_break": "Ruptura de límites", "dual_catalyst": "Catalizador doble", "linked_arsenal": "Arsenal encadenado", "returning_light_step": "Paso Fantasma del Último Destello", "spellbreaker_guard": "Arte de Guardia Rompehechizos",
	},
	"pt-BR": {
		"overload_circuit": "Impulso Relâmpago", "reverb": "Reverberação", "golden_trajectory": "Trajetória dourada", "static_field": "Campo estático",
		"recycle_protocol": "Renascimento no limite", "meridian_expand": "Expansão de meridianos", "gravitybelt": "Arte Corporal Instantânea", "smartphone": "Arte da Adaptação", "core_stabilize": "Estabilizador do núcleo", "limit_break": "Ruptura de limite", "dual_catalyst": "Catalisador duplo", "linked_arsenal": "Arsenal encadeado", "returning_light_step": "Passo Fantasma do Último Clarão", "spellbreaker_guard": "Arte da Guarda Quebra-feitiços",
	},
	"ru": {
		"overload_circuit": "Грозовой разгон", "reverb": "Эхо", "golden_trajectory": "Золотая траектория", "static_field": "Статическое поле",
		"recycle_protocol": "Возрождение на грани", "meridian_expand": "Расширение меридианов", "gravitybelt": "Мгновенное Искусство Тела", "smartphone": "Искусство Адаптации", "core_stabilize": "Стабилизатор ядра", "limit_break": "Прорыв предела", "dual_catalyst": "Двойной катализатор", "linked_arsenal": "Цепной арсенал", "returning_light_step": "Призрачный шаг последнего света", "spellbreaker_guard": "Искусство защиты от чар",
	},
}

const BYPRODUCT_DETAILS := {
	"zh": {
		"overload_circuit": "冲刺中击球时有15%概率使球速提高80%并变为红紫色；首领格挡后恢复原速和颜色",
		"reverb": "使用技能后3秒内移动速度提高70%",
		"golden_trajectory": "每次撞墙获得2金币，每回合最多40金币",
		"static_field": "失分后的发球等待期间，静电场最多持续10秒，首领移动速度降低30%",
		"recycle_protocol": "失分时有25%概率补满全部冲刺令牌",
		"meridian_expand": "本局武功最大栏位增加1个",
		"core_stabilize": "平息下一次融合的走火入魔",
		"limit_break": "适用材料的有效等级提高1级",
		"dual_catalyst": "下一次符合条件的上乘武功概率提高15个百分点",
		"gravitybelt": "移动输入会立刻达到最高速度，松开输入后立即停止",
		"smartphone": "危急时自动使用恢复、秒表或金刚结界主动道具",
		"linked_arsenal": "每持有1颗滑步珠，主动道具栏位增加1个",
		"returning_light_step": "无可用滑步次数且即将失分时，有30%概率瞬移到球的落点",
		"spellbreaker_guard": "回球时有12%概率展开5秒结界，可招架符合条件的首领技能",
	},
	"ja": {
		"overload_circuit": "ダッシュ中の打球時に15%の確率でボール速度+80%、ボールが赤紫色に変化。ボスのガードで速度と色が元に戻る",
		"reverb": "スキル使用後3秒間、移動速度+70%",
		"golden_trajectory": "壁反射ごとにゴールド2、1ラウンド最大40",
		"static_field": "失点後のサーブ待機中、静電場が最大10秒間持続し、ボスの移動速度-30%",
		"recycle_protocol": "失点時25%の確率で全ダッシュトークンを補充",
		"meridian_expand": "このランの武功最大枠+1",
		"core_stabilize": "次の融合1回の走火入魔を安定化",
		"limit_break": "適用可能な素材の有効レベル+1",
		"dual_catalyst": "次の対象となる上乗武功抽選率+15ポイント",
		"gravitybelt": "移動入力が即座に最高速へ到達し、入力を離すとすぐ停止",
		"smartphone": "緊急時に回復・ストップウォッチ・金剛結界のアクティブアイテムを自動使用",
		"linked_arsenal": "所持している滑走珠1個につきアクティブアイテム枠+1",
		"returning_light_step": "使用可能な滑走トークンがなく失点寸前の時、30%の確率でボールの落下地点へ瞬間移動",
		"spellbreaker_guard": "打ち返し時に12%の確率で5秒間の結界を展開し、対象となるボススキルをパリィ",
	},
	"es": {
		"overload_circuit": "15% de probabilidad de +80% de velocidad y de volver la pelota rojo púrpura al golpear durante un impulso; la velocidad y el color se restablecen cuando el jefe bloquea",
		"reverb": "+70% de velocidad de movimiento durante 3 s tras usar una habilidad",
		"golden_trajectory": "+2 de oro por rebote en pared, hasta 40 por ronda",
		"static_field": "-30% de velocidad de movimiento del jefe durante un máximo de 10 s mientras espera el saque tras perder un punto",
		"recycle_protocol": "25% de probabilidad de rellenar todos los tokens de impulso al perder un punto",
		"meridian_expand": "+1 espacio máximo de Mugong durante esta partida",
		"core_stabilize": "estabiliza la desviación del qi de la siguiente fusión",
		"limit_break": "+1 nivel efectivo para los materiales válidos",
		"dual_catalyst": "+15 puntos porcentuales a la siguiente tirada válida de arte marcial superior",
		"gravitybelt": "el movimiento alcanza la velocidad máxima al instante y se detiene al soltar",
		"smartphone": "usa automáticamente objetos activos de recuperación, Cronómetro o Barrera Vajra en emergencias",
		"linked_arsenal": "+1 espacio de objeto activo por cada Orbe de Deslizamiento",
		"returning_light_step": "30% de probabilidad de teleportarse al punto de caída de la pelota cuando no quedan fichas de deslizamiento utilizables y el rival está a punto de anotar",
		"spellbreaker_guard": "12% de probabilidad al devolver la pelota de alzar una barrera de 5 s que para habilidades válidas del jefe",
	},
	"pt-BR": {
		"overload_circuit": "15% de chance de +80% de velocidade e de deixar a bola vermelho-púrpura ao rebater durante um impulso; velocidade e cor voltam ao normal quando o chefe bloqueia",
		"reverb": "+70% de velocidade de movimento por 3 s após usar uma habilidade",
		"golden_trajectory": "+2 de ouro por quique na parede, até 40 por rodada",
		"static_field": "-30% de velocidade de movimento do chefe por até 10 s durante a espera do saque após perder um ponto",
		"recycle_protocol": "25% de chance de recarregar todos os tokens de impulso ao perder um ponto",
		"meridian_expand": "+1 espaço máximo de Mugong nesta partida",
		"core_stabilize": "estabiliza o desvio de qi da próxima fusão",
		"limit_break": "+1 nível efetivo para os materiais válidos",
		"dual_catalyst": "+15 pontos percentuais na próxima rolagem válida de arte marcial superior",
		"gravitybelt": "o movimento atinge a velocidade máxima instantaneamente e para ao soltar",
		"smartphone": "usa automaticamente itens ativos de recuperação, Cronômetro ou Barreira Vajra em emergências",
		"linked_arsenal": "+1 espaço de item ativo por Orbe de Deslize",
		"returning_light_step": "30% de chance de se teleportar ao ponto de queda da bola quando não restam fichas de deslizamento utilizáveis e o ponto está iminente",
		"spellbreaker_guard": "12% de chance ao devolver a bola de erguer uma barreira de 5 s que apara habilidades válidas do chefe",
	},
	"ru": {
		"overload_circuit": "15% шанс увеличить скорость мяча на 80% и окрасить его в красно-фиолетовый цвет при ударе во время рывка; после блока босса скорость и цвет восстанавливаются",
		"reverb": "+70% к скорости движения на 3 с после применения навыка",
		"golden_trajectory": "+2 золота за отскок от стены, до 40 за раунд",
		"static_field": "-30% к скорости босса максимум на 10 с во время ожидания подачи после пропущенного очка",
		"recycle_protocol": "25% шанс восполнить все жетоны рывка после пропущенного очка",
		"meridian_expand": "+1 к максимуму ячеек мугон в этом забеге",
		"core_stabilize": "стабилизирует отклонение ци при следующем слиянии",
		"limit_break": "+1 к эффективному уровню подходящих материалов",
		"dual_catalyst": "+15 процентных пунктов к следующему подходящему шансу высшего боевого искусства",
		"gravitybelt": "движение мгновенно достигает максимальной скорости и сразу останавливается при отпускании",
		"smartphone": "автоматически использует активные предметы лечения, Секундомер или Барьер Ваджры в экстренной ситуации",
		"linked_arsenal": "+1 ячейка активного предмета за каждую Сферу скольжения",
		"returning_light_step": "30% шанс телепортироваться к точке падения мяча, если не осталось доступных жетонов рывка и очко почти потеряно",
		"spellbreaker_guard": "12% шанс при возврате мяча создать на 5 с барьер, парирующий подходящие навыки босса",
	},
}

const OPTION_LABELS := {
	"zh": {
		"runtime_skill_bonus": "效果数值", "star_bonus_pct": "武魂加成", "trigger_chance_pct": "触发概率", "invincible_duration_sec": "无敌持续时间",
		"boomerang_knockback_pct": "回旋镖击退", "boomerang_stun_pct": "回旋镖眩晕概率", "boomerang_launch_speed_pct": "回旋镖发射速度", "boomerang_homing_pct": "回旋镖追踪力", "boomerang_spawn_bonus_pct": "回旋镖生成量",
		"auto_dash_token_count": "自动冲刺令牌", "auto_dash_cooldown_sec": "自动冲刺冷却", "attraction_range": "吸引范围", "bonus_perk_chance": "额外特性概率", "fusion_rare_slot_bonus_pct": "合一稀有槽概率", "fusion_byproduct_count_shift_pct": "合一多结果权重", "chargebag_pct": "充能袋加成", "gauge_preserve_pct": "能量保留量",
		"wall_length_pct": "土壁长度", "item_cooldown_pct": "道具冷却缩减", "wall_spawn_bonus_pct": "土壁牌出现量", "gold_bonus_pct": "金币加成", "double_spawn_pct": "双倍生成概率", "shard_count": "破片数量", "knockback_level": "击退等级",
		"gauge_cost": "能量消耗", "fuel_bonus_flat": "燃料加成", "gauge_gain_pct": "能量获取量", "negate_chance_pct": "伤害免除概率", "aipill_gauge_reduction": "神灵丸能量缩减", "aipill_spawn_bonus_pct": "神灵丸生成量",
		"throw_speed_pct": "投掷速度", "explosion_range_pct": "爆炸范围", "smoke_duration_pct": "烟幕持续时间", "prep_reduction_pct": "准备时间缩减", "rainbow_glove_trigger_chance_pct": "彩虹手套触发概率", "rainbow_glove_cooldown_reduction_pct": "彩虹手套冷却缩减",
		"knee_charge_pct": "护膝充能量", "soul_burst_gauge_cost": "灵魂爆发能量消耗", "stun_resist_pct": "眩晕抗性", "knockback_resist_pct": "击退抗性", "posture_correction_pct": "架势校正", "mist_trigger_chance_pct": "毒雾触发概率", "mist_duration_sec": "毒雾持续时间", "perk_level_bonus": "特性有效等级加成", "sage_speed_penalty_pct": "贤者戒指速度惩罚", "sage_body_penalty_pct": "贤者戒指体型惩罚",
	},
	"ja": {
		"runtime_skill_bonus": "効果値", "star_bonus_pct": "武魂ボーナス", "trigger_chance_pct": "発動率", "invincible_duration_sec": "無敵時間",
		"boomerang_knockback_pct": "ブーメランノックバック", "boomerang_stun_pct": "ブーメラン気絶率", "boomerang_launch_speed_pct": "ブーメラン射出速度", "boomerang_homing_pct": "ブーメラン誘導力", "boomerang_spawn_bonus_pct": "ブーメラン生成量",
		"auto_dash_token_count": "自動ダッシュトークン", "auto_dash_cooldown_sec": "自動ダッシュ再使用時間", "attraction_range": "吸引範囲", "bonus_perk_chance": "追加パーク率", "fusion_rare_slot_bonus_pct": "合一希少枠率", "fusion_byproduct_count_shift_pct": "合一複数結果比率", "chargebag_pct": "チャージバッグボーナス", "gauge_preserve_pct": "ゲージ保持量",
		"wall_length_pct": "土壁の長さ", "item_cooldown_pct": "アイテム再使用短縮", "wall_spawn_bonus_pct": "土壁札出現量", "gold_bonus_pct": "ゴールドボーナス", "double_spawn_pct": "二重生成率", "shard_count": "破片数", "knockback_level": "ノックバック段階",
		"gauge_cost": "ゲージ消費量", "fuel_bonus_flat": "燃料ボーナス", "gauge_gain_pct": "ゲージ獲得量", "negate_chance_pct": "無効化率", "aipill_gauge_reduction": "神霊丸のゲージ軽減", "aipill_spawn_bonus_pct": "神霊丸生成量",
		"throw_speed_pct": "投てき速度", "explosion_range_pct": "爆発範囲", "smoke_duration_pct": "煙幕持続時間", "prep_reduction_pct": "準備時間短縮", "rainbow_glove_trigger_chance_pct": "レインボーグローブ発動率", "rainbow_glove_cooldown_reduction_pct": "レインボーグローブ再使用短縮",
		"knee_charge_pct": "ニーパッド充填量", "soul_burst_gauge_cost": "ソウルバーストのゲージ消費量", "stun_resist_pct": "気絶耐性", "knockback_resist_pct": "ノックバック耐性", "posture_correction_pct": "姿勢補正", "mist_trigger_chance_pct": "毒霧発動率", "mist_duration_sec": "毒霧持続時間", "perk_level_bonus": "パーク有効レベルボーナス", "sage_speed_penalty_pct": "賢者の指輪の速度ペナルティ", "sage_body_penalty_pct": "賢者の指輪の体格ペナルティ",
	},
	"es": {
		"runtime_skill_bonus": "Valor del efecto", "star_bonus_pct": "Bonificación de alma marcial", "trigger_chance_pct": "Probabilidad de activación", "invincible_duration_sec": "Duración de invencibilidad",
		"boomerang_knockback_pct": "Empuje del bumerán", "boomerang_stun_pct": "Probabilidad de aturdir del bumerán", "boomerang_launch_speed_pct": "Velocidad de lanzamiento del bumerán", "boomerang_homing_pct": "Guiado del bumerán", "boomerang_spawn_bonus_pct": "Cantidad de bumeranes",
		"auto_dash_token_count": "Tokens de impulso automático", "auto_dash_cooldown_sec": "Recarga del impulso automático", "attraction_range": "Alcance de atracción", "bonus_perk_chance": "Probabilidad de ventaja adicional", "fusion_rare_slot_bonus_pct": "Probabilidad de ranura rara de fusión", "fusion_byproduct_count_shift_pct": "Proporción de resultados múltiples", "chargebag_pct": "Bonificación de bolsa de carga", "gauge_preserve_pct": "Energía conservada",
		"wall_length_pct": "Longitud del muro de tierra", "item_cooldown_pct": "Reducción de recarga de objetos", "wall_spawn_bonus_pct": "Aparición del Talismán Tobyeok", "gold_bonus_pct": "Bonificación de oro", "double_spawn_pct": "Probabilidad de aparición doble", "shard_count": "Cantidad de fragmentos", "knockback_level": "Nivel de empuje",
		"gauge_cost": "Coste de energía", "fuel_bonus_flat": "Bonificación de combustible", "gauge_gain_pct": "Energía obtenida", "negate_chance_pct": "Probabilidad de anular daño", "aipill_gauge_reduction": "Reducción de energía de la píldora espiritual", "aipill_spawn_bonus_pct": "Cantidad de píldoras espirituales",
		"throw_speed_pct": "Velocidad de lanzamiento", "explosion_range_pct": "Alcance de explosión", "smoke_duration_pct": "Duración del humo", "prep_reduction_pct": "Reducción de preparación", "rainbow_glove_trigger_chance_pct": "Activación del guante arcoíris", "rainbow_glove_cooldown_reduction_pct": "Reducción de recarga del guante arcoíris",
		"knee_charge_pct": "Carga de rodillera", "soul_burst_gauge_cost": "Coste de energía de Explosión de alma", "stun_resist_pct": "Resistencia al aturdimiento", "knockback_resist_pct": "Resistencia al empuje", "posture_correction_pct": "Corrección de postura", "mist_trigger_chance_pct": "Activación de niebla tóxica", "mist_duration_sec": "Duración de niebla tóxica", "perk_level_bonus": "Bonificación de nivel efectivo", "sage_speed_penalty_pct": "Penalización de velocidad del anillo sabio", "sage_body_penalty_pct": "Penalización de tamaño del anillo sabio",
	},
	"pt-BR": {
		"runtime_skill_bonus": "Valor do efeito", "star_bonus_pct": "Bônus de alma marcial", "trigger_chance_pct": "Chance de ativação", "invincible_duration_sec": "Duração da invencibilidade",
		"boomerang_knockback_pct": "Repulsão do bumerangue", "boomerang_stun_pct": "Chance de atordoar do bumerangue", "boomerang_launch_speed_pct": "Velocidade de lançamento do bumerangue", "boomerang_homing_pct": "Rastreamento do bumerangue", "boomerang_spawn_bonus_pct": "Quantidade de bumerangues",
		"auto_dash_token_count": "Tokens de impulso automático", "auto_dash_cooldown_sec": "Recarga do impulso automático", "attraction_range": "Alcance de atração", "bonus_perk_chance": "Chance de vantagem extra", "fusion_rare_slot_bonus_pct": "Chance do espaço raro da fusão", "fusion_byproduct_count_shift_pct": "Proporção de resultados múltiplos", "chargebag_pct": "Bônus da bolsa de carga", "gauge_preserve_pct": "Energia preservada",
		"wall_length_pct": "Comprimento do muro de terra", "item_cooldown_pct": "Redução de recarga de itens", "wall_spawn_bonus_pct": "Aparição do Talismã Tobyeok", "gold_bonus_pct": "Bônus de ouro", "double_spawn_pct": "Chance de surgimento duplo", "shard_count": "Quantidade de fragmentos", "knockback_level": "Nível de repulsão",
		"gauge_cost": "Custo de energia", "fuel_bonus_flat": "Bônus de combustível", "gauge_gain_pct": "Energia obtida", "negate_chance_pct": "Chance de anular dano", "aipill_gauge_reduction": "Redução de energia da pílula espiritual", "aipill_spawn_bonus_pct": "Quantidade de pílulas espirituais",
		"throw_speed_pct": "Velocidade de arremesso", "explosion_range_pct": "Alcance da explosão", "smoke_duration_pct": "Duração da fumaça", "prep_reduction_pct": "Redução de preparo", "rainbow_glove_trigger_chance_pct": "Ativação da luva arco-íris", "rainbow_glove_cooldown_reduction_pct": "Redução de recarga da luva arco-íris",
		"knee_charge_pct": "Carga da joelheira", "soul_burst_gauge_cost": "Custo de energia da Explosão da alma", "stun_resist_pct": "Resistência a atordoamento", "knockback_resist_pct": "Resistência a repulsão", "posture_correction_pct": "Correção de postura", "mist_trigger_chance_pct": "Ativação da névoa tóxica", "mist_duration_sec": "Duração da névoa tóxica", "perk_level_bonus": "Bônus de nível efetivo", "sage_speed_penalty_pct": "Penalidade de velocidade do anel sábio", "sage_body_penalty_pct": "Penalidade de tamanho do anel sábio",
	},
	"ru": {
		"runtime_skill_bonus": "Величина эффекта", "star_bonus_pct": "Бонус боевого духа", "trigger_chance_pct": "Шанс срабатывания", "invincible_duration_sec": "Длительность неуязвимости",
		"boomerang_knockback_pct": "Отбрасывание бумеранга", "boomerang_stun_pct": "Шанс оглушения бумерангом", "boomerang_launch_speed_pct": "Скорость запуска бумеранга", "boomerang_homing_pct": "Наведение бумеранга", "boomerang_spawn_bonus_pct": "Количество бумерангов",
		"auto_dash_token_count": "Жетоны авто-рывка", "auto_dash_cooldown_sec": "Перезарядка авто-рывка", "attraction_range": "Радиус притяжения", "bonus_perk_chance": "Шанс дополнительного перка", "fusion_rare_slot_bonus_pct": "Шанс редкого слота слияния", "fusion_byproduct_count_shift_pct": "Доля нескольких результатов", "chargebag_pct": "Бонус сумки заряда", "gauge_preserve_pct": "Сохранённая энергия",
		"wall_length_pct": "Длина земляной стены", "item_cooldown_pct": "Сокращение перезарядки предметов", "wall_spawn_bonus_pct": "Появление талисмана «Тобёк»", "gold_bonus_pct": "Бонус золота", "double_spawn_pct": "Шанс двойного появления", "shard_count": "Количество осколков", "knockback_level": "Уровень отбрасывания",
		"gauge_cost": "Расход энергии", "fuel_bonus_flat": "Бонус топлива", "gauge_gain_pct": "Получение энергии", "negate_chance_pct": "Шанс отмены урона", "aipill_gauge_reduction": "Снижение расхода энергии пилюли духа", "aipill_spawn_bonus_pct": "Количество пилюль духа",
		"throw_speed_pct": "Скорость броска", "explosion_range_pct": "Радиус взрыва", "smoke_duration_pct": "Длительность дыма", "prep_reduction_pct": "Сокращение подготовки", "rainbow_glove_trigger_chance_pct": "Срабатывание радужной перчатки", "rainbow_glove_cooldown_reduction_pct": "Сокращение перезарядки радужной перчатки",
		"knee_charge_pct": "Заряд наколенника", "soul_burst_gauge_cost": "Расход энергии Взрыва души", "stun_resist_pct": "Сопротивление оглушению", "knockback_resist_pct": "Сопротивление отбрасыванию", "posture_correction_pct": "Коррекция стойки", "mist_trigger_chance_pct": "Срабатывание ядовитого тумана", "mist_duration_sec": "Длительность ядовитого тумана", "perk_level_bonus": "Бонус эффективного уровня", "sage_speed_penalty_pct": "Штраф скорости кольца мудреца", "sage_body_penalty_pct": "Штраф размера кольца мудреца",
	},
}

# Units are keyed by semantic family, not option id, so every locale owns the
# visible suffixes without duplicating the option-label table.
const OPTION_UNITS := {
	"ko": {"seconds": "초", "count": "개", "levels": "단계", "perk_level": "경지", "pixels": "px", "gauge": "기력", "fuel": "연료"},
	"en": {"seconds": "s", "count": "", "levels": "levels", "perk_level": "Lv.", "pixels": "px", "gauge": "gauge", "fuel": "fuel"},
	"zh": {"seconds": "秒", "count": "个", "levels": "级", "perk_level": "级", "pixels": "像素", "gauge": "能量", "fuel": "燃料"},
	"ja": {"seconds": "秒", "count": "個", "levels": "段階", "perk_level": "Lv.", "pixels": "px", "gauge": "ゲージ", "fuel": "燃料"},
	"es": {"seconds": "s", "count": "uds.", "levels": "niveles", "perk_level": "Nv.", "pixels": "px", "gauge": "energía", "fuel": "combustible"},
	"pt-BR": {"seconds": "s", "count": "un.", "levels": "níveis", "perk_level": "Nv.", "pixels": "px", "gauge": "energia", "fuel": "combustível"},
	"ru": {"seconds": "с", "count": "шт.", "levels": "ур.", "perk_level": "ур.", "pixels": "пкс", "gauge": "энергия", "fuel": "топливо"},
}
