extends RefCounted

# Per-frame sprite socket catalog: named anchor points ("sockets") measured
# from the real sheet pixels, so composition layers (perk glows, attachments,
# future paper-doll parts) can track the drawn body frame-by-frame instead of
# riding a fixed whole-body offset.
#
# Coordinates are CELL-LOCAL pixels in the authored sheet's cell space
# (SMASHER_SOCKET_CELL_SIZE). Data is generated by
# tools/author_player_sprite_sockets.py from the shipped sheets -- re-run that
# tool when a sheet is replaced (e.g. the 환격전 restyle) instead of editing
# numbers by hand.
#
# Direction resolution: exact match -> "any" -> mirror of the opposite
# direction (the shipped left move sheets are literal mirrors of the right
# sheets). Mirroring flips x (cell_w - x) AND swaps the _l/_r socket ids so a
# socket id always names the screen-side it sits on.
#
# Fail-closed: unknown character / motion / empty data resolve to {} so
# consumers must skip rather than draw at a guessed position.

const SMASHER_SOCKET_CELL_SIZE := Vector2(160.0, 160.0)
const SMASHER_SOCKETS := {
	"walk": {
		"right": [
			{"foot_l": Vector2(71.0, 129.0), "foot_r": Vector2(92.0, 129.0), "head_top": Vector2(77.9, 30.0)},
			{"foot_l": Vector2(71.0, 128.0), "foot_r": Vector2(92.0, 128.0), "head_top": Vector2(77.6, 29.0)},
			{"foot_l": Vector2(72.0, 127.0), "foot_r": Vector2(91.0, 127.0), "head_top": Vector2(77.3, 28.0)},
			{"foot_l": Vector2(66.0, 126.0), "foot_r": Vector2(93.0, 126.0), "head_top": Vector2(77.5, 27.0)},
			{"foot_l": Vector2(72.0, 127.0), "foot_r": Vector2(92.0, 127.0), "head_top": Vector2(77.0, 28.0)},
			{"foot_l": Vector2(71.0, 128.0), "foot_r": Vector2(92.0, 128.0), "head_top": Vector2(77.4, 29.0)},
			{"foot_l": Vector2(71.0, 129.0), "foot_r": Vector2(92.0, 129.0), "head_top": Vector2(77.8, 30.0)},
			{"foot_l": Vector2(71.0, 129.0), "foot_r": Vector2(93.0, 129.0), "head_top": Vector2(78.0, 30.0)},
		],
	},
	"dash": {
		"right": [
			{"foot_l": Vector2(58.0, 123.0), "foot_r": Vector2(80.0, 123.0), "head_top": Vector2(82.3, 29.0)},
			{"foot_l": Vector2(49.0, 126.0), "foot_r": Vector2(80.0, 126.0), "head_top": Vector2(82.1, 28.0)},
			{"foot_l": Vector2(49.0, 126.0), "foot_r": Vector2(80.0, 126.0), "head_top": Vector2(85.6, 28.0)},
			{"foot_l": Vector2(50.0, 126.0), "foot_r": Vector2(79.0, 126.0), "head_top": Vector2(86.1, 27.0)},
			{"foot_l": Vector2(49.0, 126.0), "foot_r": Vector2(80.0, 126.0), "head_top": Vector2(86.2, 28.0)},
			{"foot_l": Vector2(50.0, 126.0), "foot_r": Vector2(79.0, 126.0), "head_top": Vector2(84.5, 28.0)},
			{"foot_l": Vector2(54.0, 125.0), "foot_r": Vector2(79.0, 125.0), "head_top": Vector2(83.6, 28.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(84.0, 125.0), "head_top": Vector2(83.2, 28.0)},
		],
	},
	"idle": {
		"any": [
			{"foot_l": Vector2(55.0, 129.0), "foot_r": Vector2(96.0, 129.0), "head_top": Vector2(71.0, 29.0)},
			{"foot_l": Vector2(56.0, 129.0), "foot_r": Vector2(96.0, 129.0), "head_top": Vector2(71.5, 29.0)},
			{"foot_l": Vector2(55.0, 128.0), "foot_r": Vector2(96.0, 128.0), "head_top": Vector2(72.2, 28.0)},
			{"foot_l": Vector2(55.0, 127.0), "foot_r": Vector2(97.0, 127.0), "head_top": Vector2(72.1, 28.0)},
			{"foot_l": Vector2(55.0, 127.0), "foot_r": Vector2(97.0, 127.0), "head_top": Vector2(71.6, 27.0)},
			{"foot_l": Vector2(55.0, 127.0), "foot_r": Vector2(97.0, 127.0), "head_top": Vector2(71.1, 28.0)},
			{"foot_l": Vector2(55.0, 128.0), "foot_r": Vector2(96.0, 128.0), "head_top": Vector2(71.0, 28.0)},
			{"foot_l": Vector2(55.0, 128.0), "foot_r": Vector2(97.0, 128.0), "head_top": Vector2(70.8, 29.0)},
		],
	},
	"attack": {
		"left": [
			{"foot_l": Vector2(53.0, 130.0), "foot_r": Vector2(107.0, 130.0), "head_top": Vector2(53.3, 27.0)},
			{"foot_l": Vector2(53.0, 130.0), "foot_r": Vector2(107.0, 130.0), "head_top": Vector2(54.2, 27.0)},
			{"foot_l": Vector2(53.0, 130.0), "foot_r": Vector2(108.0, 130.0), "head_top": Vector2(53.8, 27.0)},
			{"foot_l": Vector2(52.0, 130.0), "foot_r": Vector2(108.0, 130.0), "head_top": Vector2(54.0, 26.0)},
			{"foot_l": Vector2(52.0, 130.0), "foot_r": Vector2(107.0, 130.0), "head_top": Vector2(48.8, 27.0)},
			{"foot_l": Vector2(51.0, 130.0), "foot_r": Vector2(107.0, 130.0), "head_top": Vector2(78.1, 36.0)},
			{"foot_l": Vector2(51.0, 130.0), "foot_r": Vector2(106.0, 130.0), "head_top": Vector2(77.4, 36.0)},
			{"foot_l": Vector2(51.0, 130.0), "foot_r": Vector2(106.0, 130.0), "head_top": Vector2(77.2, 35.0)},
			{"foot_l": Vector2(51.0, 130.0), "foot_r": Vector2(107.0, 130.0), "head_top": Vector2(50.5, 21.0)},
			{"foot_l": Vector2(51.0, 129.0), "foot_r": Vector2(109.0, 129.0), "head_top": Vector2(64.2, 30.0)},
			{"foot_l": Vector2(52.0, 129.0), "foot_r": Vector2(109.0, 129.0), "head_top": Vector2(67.9, 30.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(109.0, 129.0), "head_top": Vector2(64.0, 28.0)},
			{"foot_l": Vector2(54.0, 129.0), "foot_r": Vector2(109.0, 129.0), "head_top": Vector2(60.0, 27.0)},
			{"foot_l": Vector2(53.0, 128.0), "foot_r": Vector2(109.0, 128.0), "head_top": Vector2(58.5, 27.0)},
			{"foot_l": Vector2(55.0, 129.0), "foot_r": Vector2(108.0, 129.0), "head_top": Vector2(56.7, 27.0)},
			{"foot_l": Vector2(54.0, 129.0), "foot_r": Vector2(107.0, 129.0), "head_top": Vector2(56.4, 27.0)},
		],
		"right": [
			{"foot_l": Vector2(57.0, 130.0), "foot_r": Vector2(105.0, 130.0), "head_top": Vector2(72.9, 28.0)},
			{"foot_l": Vector2(57.0, 130.0), "foot_r": Vector2(105.0, 130.0), "head_top": Vector2(73.1, 28.0)},
			{"foot_l": Vector2(55.0, 130.0), "foot_r": Vector2(106.0, 130.0), "head_top": Vector2(73.1, 28.0)},
			{"foot_l": Vector2(55.0, 130.0), "foot_r": Vector2(106.0, 130.0), "head_top": Vector2(73.5, 28.0)},
			{"foot_l": Vector2(55.0, 130.0), "foot_r": Vector2(106.0, 130.0), "head_top": Vector2(73.9, 28.0)},
			{"foot_l": Vector2(56.0, 130.0), "foot_r": Vector2(105.0, 130.0), "head_top": Vector2(73.7, 28.0)},
			{"foot_l": Vector2(57.0, 130.0), "foot_r": Vector2(105.0, 130.0), "head_top": Vector2(73.8, 27.0)},
			{"foot_l": Vector2(55.0, 129.0), "foot_r": Vector2(106.0, 129.0), "head_top": Vector2(73.7, 27.0)},
			{"foot_l": Vector2(57.0, 129.0), "foot_r": Vector2(105.0, 129.0), "head_top": Vector2(73.0, 27.0)},
			{"foot_l": Vector2(55.0, 128.0), "foot_r": Vector2(106.0, 128.0), "head_top": Vector2(73.5, 26.0)},
			{"foot_l": Vector2(56.0, 128.0), "foot_r": Vector2(106.0, 128.0), "head_top": Vector2(73.3, 26.0)},
			{"foot_l": Vector2(57.0, 128.0), "foot_r": Vector2(105.0, 128.0), "head_top": Vector2(73.3, 26.0)},
			{"foot_l": Vector2(57.0, 128.0), "foot_r": Vector2(105.0, 128.0), "head_top": Vector2(73.1, 26.0)},
			{"foot_l": Vector2(57.0, 128.0), "foot_r": Vector2(105.0, 128.0), "head_top": Vector2(73.1, 26.0)},
			{"foot_l": Vector2(55.0, 128.0), "foot_r": Vector2(106.0, 128.0), "head_top": Vector2(73.3, 26.0)},
			{"foot_l": Vector2(57.0, 129.0), "foot_r": Vector2(104.0, 129.0), "head_top": Vector2(73.4, 26.0)},
		],
	},
}

const _CHARACTER_SOCKETS := {
	"smasher": SMASHER_SOCKETS,
}
const _CHARACTER_CELL_SIZES := {
	"smasher": SMASHER_SOCKET_CELL_SIZE,
}
const _MIRROR_SOURCE := {"left": "right", "right": "left"}


static func has_socket_data(character_id: String, motion_id: String) -> bool:
	var motions: Dictionary = _CHARACTER_SOCKETS.get(character_id, {})
	return motions.has(motion_id)


static func get_cell_size(character_id: String) -> Vector2:
	return _CHARACTER_CELL_SIZES.get(character_id, Vector2.ZERO)


# Returns {socket_id: Vector2 screen_pos} for the given draw, or {} when no
# authored data covers it. dest_rect is the on-screen rect the sheet cell is
# drawn into, so socket positions inherit shake / scale from the body draw.
static func resolve_screen_sockets(
	character_id: String,
	motion_id: String,
	direction: String,
	frame_index: int,
	dest_rect: Rect2
) -> Dictionary:
	var cell_size: Vector2 = get_cell_size(character_id)
	if cell_size.x <= 0.0 or cell_size.y <= 0.0:
		return {}
	if dest_rect.size.x <= 0.0 or dest_rect.size.y <= 0.0:
		return {}
	var motions: Dictionary = _CHARACTER_SOCKETS.get(character_id, {})
	var directions: Variant = motions.get(motion_id, null)
	if not (directions is Dictionary):
		return {}
	var normalized_direction := direction.strip_edges().to_lower()
	var frames: Variant = null
	var mirrored := false
	if (directions as Dictionary).has(normalized_direction):
		frames = (directions as Dictionary).get(normalized_direction)
	elif (directions as Dictionary).has("any"):
		frames = (directions as Dictionary).get("any")
	elif _MIRROR_SOURCE.has(normalized_direction) and (directions as Dictionary).has(_MIRROR_SOURCE[normalized_direction]):
		frames = (directions as Dictionary).get(_MIRROR_SOURCE[normalized_direction])
		mirrored = true
	if not (frames is Array) or (frames as Array).is_empty():
		return {}
	var frame_list: Array = frames
	var clamped_frame: int = clampi(frame_index, 0, frame_list.size() - 1)
	var cell_sockets: Variant = frame_list[clamped_frame]
	if not (cell_sockets is Dictionary) or (cell_sockets as Dictionary).is_empty():
		return {}
	var result: Dictionary = {}
	for socket_id in (cell_sockets as Dictionary):
		var local: Vector2 = (cell_sockets as Dictionary)[socket_id]
		var out_id := str(socket_id)
		if mirrored:
			local = Vector2(cell_size.x - local.x, local.y)
			out_id = _mirror_socket_id(out_id)
		result[out_id] = dest_rect.position + Vector2(
			local.x / cell_size.x * dest_rect.size.x,
			local.y / cell_size.y * dest_rect.size.y
		)
	return result


static func _mirror_socket_id(socket_id: String) -> String:
	if socket_id.ends_with("_l"):
		return socket_id.substr(0, socket_id.length() - 2) + "_r"
	if socket_id.ends_with("_r"):
		return socket_id.substr(0, socket_id.length() - 2) + "_l"
	return socket_id
