extends RefCounted

# Per-frame sprite socket catalog: named anchor points ("sockets") measured
# from the real sheet pixels, so composition layers (perk glows, attachments,
# future paper-doll parts) can track the drawn body frame-by-frame instead of
# riding a fixed whole-body offset.
#
# Coordinates are CELL-LOCAL pixels in the authored sheet's cell space
# (SMASHER_SOCKET_CELL_SIZE). Data is generated by
# tools/author_player_sprite_sockets.py from the shipped sheets -- re-run that
# tool when a sheet is replaced (e.g. the 환격전 restyle) instead of editing
# numbers by hand.
#
# Direction resolution: exact match -> "any" -> mirror of the opposite
# direction (the shipped left move sheets are literal mirrors of the right
# sheets). Mirroring flips x (cell_w - x) AND swaps the _l/_r socket ids so a
# socket id always names the screen-side it sits on.
#
# Fail-closed: unknown character / motion / empty data resolve to {} so
# consumers must skip rather than draw at a guessed position.

const SMASHER_SOCKET_CELL_SIZE := Vector2(160.0, 160.0)
const SMASHER_SOCKETS := {
	"walk": {
		"right": [
			{"foot_l": Vector2(56.0, 128.0), "foot_r": Vector2(99.0, 128.0), "head_top": Vector2(73.9, 29.0)},
			{"foot_l": Vector2(56.0, 128.0), "foot_r": Vector2(99.0, 128.0), "head_top": Vector2(73.5, 28.0)},
			{"foot_l": Vector2(56.0, 127.0), "foot_r": Vector2(98.0, 127.0), "head_top": Vector2(73.5, 27.0)},
			{"foot_l": Vector2(56.0, 126.0), "foot_r": Vector2(98.0, 126.0), "head_top": Vector2(73.7, 27.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(98.0, 125.0), "head_top": Vector2(73.9, 27.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(99.0, 125.0), "head_top": Vector2(74.0, 28.0)},
			{"foot_l": Vector2(56.0, 126.0), "foot_r": Vector2(99.0, 126.0), "head_top": Vector2(74.3, 28.0)},
			{"foot_l": Vector2(57.0, 128.0), "foot_r": Vector2(98.0, 128.0), "head_top": Vector2(73.9, 29.0)},
		],
	},
	"dash": {
		"right": [
			{"foot_l": Vector2(44.0, 129.0), "foot_r": Vector2(101.0, 129.0), "head_top": Vector2(84.3, 35.0)},
			{"foot_l": Vector2(44.0, 129.0), "foot_r": Vector2(102.0, 129.0), "head_top": Vector2(85.1, 34.0)},
			{"foot_l": Vector2(40.0, 129.0), "foot_r": Vector2(104.0, 129.0), "head_top": Vector2(92.0, 31.0)},
			{"foot_l": Vector2(41.0, 129.0), "foot_r": Vector2(105.0, 129.0), "head_top": Vector2(99.0, 29.0)},
			{"foot_l": Vector2(39.0, 129.0), "foot_r": Vector2(105.0, 129.0), "head_top": Vector2(100.2, 27.0)},
			{"foot_l": Vector2(41.0, 129.0), "foot_r": Vector2(104.0, 129.0), "head_top": Vector2(98.8, 29.0)},
			{"foot_l": Vector2(41.0, 129.0), "foot_r": Vector2(103.0, 129.0), "head_top": Vector2(85.6, 32.0)},
			{"foot_l": Vector2(47.0, 129.0), "foot_r": Vector2(102.0, 129.0), "head_top": Vector2(83.9, 35.0)},
		],
	},
	"idle": {
		"any": [
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(72.7, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(72.6, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(71.6, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(71.0, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(71.1, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(71.9, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(72.6, 27.0)},
			{"foot_l": Vector2(53.0, 129.0), "foot_r": Vector2(99.0, 129.0), "head_top": Vector2(72.7, 27.0)},
		],
	},
	"attack": {
		"left": [
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(81.5, 33.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(81.3, 34.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(82.1, 37.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(81.6, 40.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(76.8, 42.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(75.2, 41.0)},
			{"foot_l": Vector2(54.0, 124.0), "foot_r": Vector2(102.0, 124.0), "head_top": Vector2(72.8, 38.0)},
			{"foot_l": Vector2(53.0, 124.0), "foot_r": Vector2(101.0, 124.0), "head_top": Vector2(73.5, 35.0)},
			{"foot_l": Vector2(53.0, 124.0), "foot_r": Vector2(101.0, 124.0), "head_top": Vector2(72.4, 37.0)},
			{"foot_l": Vector2(53.0, 124.0), "foot_r": Vector2(101.0, 124.0), "head_top": Vector2(70.0, 43.0)},
			{"foot_l": Vector2(53.0, 124.0), "foot_r": Vector2(101.0, 124.0), "head_top": Vector2(71.4, 39.0)},
			{"foot_l": Vector2(54.0, 124.0), "foot_r": Vector2(102.0, 124.0), "head_top": Vector2(76.2, 38.0)},
			{"foot_l": Vector2(54.0, 124.0), "foot_r": Vector2(102.0, 124.0), "head_top": Vector2(78.7, 35.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(102.0, 124.0), "head_top": Vector2(80.3, 34.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(82.2, 33.0)},
			{"foot_l": Vector2(55.0, 124.0), "foot_r": Vector2(103.0, 124.0), "head_top": Vector2(82.4, 33.0)},
		],
		"right": [
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(104.0, 125.0), "head_top": Vector2(79.9, 29.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(103.0, 125.0), "head_top": Vector2(79.7, 30.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(104.0, 125.0), "head_top": Vector2(79.4, 31.0)},
			{"foot_l": Vector2(55.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(79.9, 33.0)},
			{"foot_l": Vector2(55.0, 126.0), "foot_r": Vector2(104.0, 126.0), "head_top": Vector2(79.4, 33.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(78.9, 31.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(77.7, 30.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(76.8, 30.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(76.9, 30.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(76.9, 30.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(77.6, 30.0)},
			{"foot_l": Vector2(55.0, 125.0), "foot_r": Vector2(103.0, 125.0), "head_top": Vector2(80.0, 31.0)},
			{"foot_l": Vector2(56.0, 126.0), "foot_r": Vector2(104.0, 126.0), "head_top": Vector2(79.9, 33.0)},
			{"foot_l": Vector2(56.0, 126.0), "foot_r": Vector2(103.0, 126.0), "head_top": Vector2(79.1, 32.0)},
			{"foot_l": Vector2(56.0, 126.0), "foot_r": Vector2(104.0, 126.0), "head_top": Vector2(78.8, 31.0)},
			{"foot_l": Vector2(57.0, 126.0), "foot_r": Vector2(104.0, 126.0), "head_top": Vector2(78.1, 30.0)},
		],
	},
}

const _CHARACTER_SOCKETS := {
	"smasher": SMASHER_SOCKETS,
}
const _CHARACTER_CELL_SIZES := {
	"smasher": SMASHER_SOCKET_CELL_SIZE,
}
const _MIRROR_SOURCE := {"left": "right", "right": "left"}


static func has_socket_data(character_id: String, motion_id: String) -> bool:
	var motions: Dictionary = _CHARACTER_SOCKETS.get(character_id, {})
	return motions.has(motion_id)


static func get_cell_size(character_id: String) -> Vector2:
	return _CHARACTER_CELL_SIZES.get(character_id, Vector2.ZERO)


# Returns {socket_id: Vector2 screen_pos} for the given draw, or {} when no
# authored data covers it. dest_rect is the on-screen rect the sheet cell is
# drawn into, so socket positions inherit shake / scale from the body draw.
static func resolve_screen_sockets(
	character_id: String,
	motion_id: String,
	direction: String,
	frame_index: int,
	dest_rect: Rect2
) -> Dictionary:
	var cell_size: Vector2 = get_cell_size(character_id)
	if cell_size.x <= 0.0 or cell_size.y <= 0.0:
		return {}
	if dest_rect.size.x <= 0.0 or dest_rect.size.y <= 0.0:
		return {}
	var motions: Dictionary = _CHARACTER_SOCKETS.get(character_id, {})
	var directions: Variant = motions.get(motion_id, null)
	if not (directions is Dictionary):
		return {}
	var normalized_direction := direction.strip_edges().to_lower()
	var frames: Variant = null
	var mirrored := false
	if (directions as Dictionary).has(normalized_direction):
		frames = (directions as Dictionary).get(normalized_direction)
	elif (directions as Dictionary).has("any"):
		frames = (directions as Dictionary).get("any")
	elif _MIRROR_SOURCE.has(normalized_direction) and (directions as Dictionary).has(_MIRROR_SOURCE[normalized_direction]):
		frames = (directions as Dictionary).get(_MIRROR_SOURCE[normalized_direction])
		mirrored = true
	if not (frames is Array) or (frames as Array).is_empty():
		return {}
	var frame_list: Array = frames
	var clamped_frame: int = clampi(frame_index, 0, frame_list.size() - 1)
	var cell_sockets: Variant = frame_list[clamped_frame]
	if not (cell_sockets is Dictionary) or (cell_sockets as Dictionary).is_empty():
		return {}
	var result: Dictionary = {}
	for socket_id in (cell_sockets as Dictionary):
		var local: Vector2 = (cell_sockets as Dictionary)[socket_id]
		var out_id := str(socket_id)
		if mirrored:
			local = Vector2(cell_size.x - local.x, local.y)
			out_id = _mirror_socket_id(out_id)
		result[out_id] = dest_rect.position + Vector2(
			local.x / cell_size.x * dest_rect.size.x,
			local.y / cell_size.y * dest_rect.size.y
		)
	return result


static func _mirror_socket_id(socket_id: String) -> String:
	if socket_id.ends_with("_l"):
		return socket_id.substr(0, socket_id.length() - 2) + "_r"
	if socket_id.ends_with("_r"):
		return socket_id.substr(0, socket_id.length() - 2) + "_l"
	return socket_id
