extends RefCounted

const PlazaPlayerController := preload("res://scripts/plaza/plaza_player_controller.gd")

const REQUIRED_CONTEXT_KEYS: Array[String] = [
	"flow_gate",
	"current_stage",
	"plaza_theme",
	"player_pos",
	"player_textures",
	"camera_x",
	"ground_y",
	"world_size",
	"map_seed",
	"full_layout_for_test",
	"selected_character_type",
	"player_sprite_frame",
	"lingpet_companion_visible",
	"lingpet_companion_pet_id",
	"lingpet_follower_pos",
	"building_count",
	"hovered_building_type",
	"active_building",
	"dialog_text",
	"menu_open",
	"building_transition_active",
	"building_transition_phase",
	"building_transition_progress",
	"plaza_warp_active",
	"plaza_warp_phase",
	"plaza_warp_progress",
	"warp_fx_status",
	"character_info_status",
	"active_menu_type",
	"active_menu_title",
	"active_menu_subtitle",
	"active_menu_actions",
	"active_menu_last_message",
	"active_menu_visit_ap_consumed",
	"interior_view_active",
	"interior_status",
	"interior_npc_texture_loaded",
	"interior_room_texture_loaded",
	"last_bank_transaction_summary",
	"last_shop_transaction_summary",
	"last_blacksmith_transaction_summary",
	"last_gacha_transaction_summary",
	"last_lingpet_store_transaction_summary",
	"last_academy_transaction_summary",
	"last_tavern_transaction_summary",
	"runtime_perk_choice_active",
	"runtime_perk_choice_count",
	"runtime_perk_selected_index",
	"save_snapshot",
	"shop_inventory_count",
	"tavern_active_quest",
	"active_item_slot_count",
	"owned_lingpet_count",
	"blacksmith_target_summary",
	"exit_zone",
	"minimap_state",
	"game_rect",
]


func build(context: Dictionary) -> Dictionary:
	for required_key in REQUIRED_CONTEXT_KEYS:
		if not context.has(required_key):
			push_error("Plaza status context is missing required key: %s" % required_key)
			return {}
	var active_building: Dictionary = context["active_building"]
	var warp_fx_status: Dictionary = context["warp_fx_status"]
	var character_info_status: Dictionary = context["character_info_status"]
	var interior_status: Dictionary = context["interior_status"]
	var plaza_theme: Dictionary = context["plaza_theme"]
	var player_pos: Vector2 = context["player_pos"]
	var player_textures: Dictionary = context["player_textures"]
	var save_snapshot: Dictionary = context["save_snapshot"]
	return {
		"flow_gate": str(context["flow_gate"]),
		"current_stage": int(context["current_stage"]),
		"theme_id": str(plaza_theme.get("id", "")),
		"side_scroll": true,
		"player_pos": player_pos,
		"player_collision_rect": PlazaPlayerController.get_collision_rect(player_pos),
		"camera_x": float(context["camera_x"]),
		"camera_y": 0.0,
		"ground_y": float(context["ground_y"]),
		"world_size": context["world_size"],
		"map_seed": int(context["map_seed"]),
		"full_layout_for_test": bool(context["full_layout_for_test"]),
		"selected_character_type": str(context["selected_character_type"]),
		"player_sprite_loaded": bool(player_textures.get("has_sprite", false)),
		"player_sprite_mode": "sheet" if bool(player_textures.get("has_sprite", false)) else "neutral_placeholder",
		"player_sprite_frame": int(context["player_sprite_frame"]),
		"lingpet_companion_visible": bool(context["lingpet_companion_visible"]),
		"lingpet_companion_pet_id": str(context["lingpet_companion_pet_id"]),
		"lingpet_follower_pos": context["lingpet_follower_pos"],
		"building_count": int(context["building_count"]),
		"collision_rect_count": 0,
		"hovered_building_type": str(context["hovered_building_type"]),
		"interactable_building_type": str(active_building.get("type", "")),
		"dialog_text": str(context["dialog_text"]),
		"menu_open": bool(context["menu_open"]),
		"building_transition_active": bool(context["building_transition_active"]),
		"building_transition_phase": str(context["building_transition_phase"]),
		"building_transition_progress": float(context["building_transition_progress"]),
		"plaza_warp_active": bool(context["plaza_warp_active"]),
		"plaza_warp_phase": str(context["plaza_warp_phase"]),
		"plaza_warp_progress": float(context["plaza_warp_progress"]),
		"warp_pillar_fx_active": bool(warp_fx_status.get("active", false)),
		"warp_pillar_fx_actor_count": int(warp_fx_status.get("actor_count", 0)),
		"character_info_overlay_active": bool(character_info_status.get("active", false)),
		"character_info_overlay_visible": bool(character_info_status.get("visible", false)),
		"character_info_overlay_status": character_info_status.duplicate(true),
		"active_menu_type": str(context["active_menu_type"]),
		"active_menu_title": str(context["active_menu_title"]),
		"active_menu_subtitle": str(context["active_menu_subtitle"]),
		"active_menu_actions": (context["active_menu_actions"] as Array).duplicate(),
		"active_menu_last_message": str(context["active_menu_last_message"]),
		"active_menu_visit_ap_consumed": bool(context["active_menu_visit_ap_consumed"]),
		"interior_view_active": bool(context["interior_view_active"]),
		"interior_view_status": interior_status.duplicate(true),
		"interior_room_replaces_plaza": bool(interior_status.get("room_replaces_plaza", false)),
		"interior_panel_open": bool(interior_status.get("panel_open", false)),
		"interior_trade_ui_open": bool(interior_status.get("trade_ui_open", false)),
		"interior_shop_click_animation_active": bool(interior_status.get("shop_click_animation_active", false)),
		"interior_hovered_object_id": str(interior_status.get("hovered_object_id", "")),
		"interior_selected_object_id": str(interior_status.get("selected_object_id", "")),
		"interior_npc_texture_loaded": bool(context["interior_npc_texture_loaded"]),
		"interior_room_texture_loaded": bool(context["interior_room_texture_loaded"]),
		"interior_object_texture_count": int(interior_status.get("object_texture_count", 0)),
		"interior_player_inventory_count": int(interior_status.get("player_inventory_count", 0)),
		"interior_shop_inventory_count": int(interior_status.get("shop_inventory_count", 0)),
		"last_bank_transaction_summary": (context["last_bank_transaction_summary"] as Dictionary).duplicate(true),
		"last_shop_transaction_summary": (context["last_shop_transaction_summary"] as Dictionary).duplicate(true),
		"last_blacksmith_transaction_summary": (context["last_blacksmith_transaction_summary"] as Dictionary).duplicate(true),
		"last_gacha_transaction_summary": (context["last_gacha_transaction_summary"] as Dictionary).duplicate(true),
		"last_lingpet_store_transaction_summary": (context["last_lingpet_store_transaction_summary"] as Dictionary).duplicate(true),
		"last_academy_transaction_summary": (context["last_academy_transaction_summary"] as Dictionary).duplicate(true),
		"last_tavern_transaction_summary": (context["last_tavern_transaction_summary"] as Dictionary).duplicate(true),
		"runtime_perk_choice_active": bool(context["runtime_perk_choice_active"]),
		"runtime_perk_choice_count": int(context["runtime_perk_choice_count"]),
		"runtime_perk_selected_index": int(context["runtime_perk_selected_index"]),
		"plaza_gold": int(save_snapshot.get("plaza_gold", 0)),
		"shop_inventory_count": int(context["shop_inventory_count"]),
		"ap_current": int(save_snapshot.get("ap_current", 0)),
		"bank_deposit_gold": int(save_snapshot.get("bank_deposit_gold", 0)),
		"tavern_active_quest": (context["tavern_active_quest"] as Dictionary).duplicate(true),
		"active_item_slot_count": int(context["active_item_slot_count"]),
		"owned_lingpet_count": int(context["owned_lingpet_count"]),
		"blacksmith_target_summary": (context["blacksmith_target_summary"] as Dictionary).duplicate(true),
		"exit_zone": context["exit_zone"],
		"minimap_state": (context["minimap_state"] as Dictionary).duplicate(true),
		"game_rect": context["game_rect"],
	}
