#!/usr/bin/env python3
"""Deterministically derive the temporary Guardian Enhancement WAV set.

The outputs are canonical PCM16 mono RIFF/WAVE containers containing only
``fmt `` and ``data`` chunks. Rebuilding therefore also performs the GRT-036
intake repair: source metadata/trailing chunks are discarded and the RIFF size
is rewritten from the exact generated byte length.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from dataclasses import dataclass
from pathlib import Path


TARGET_RATE = 44_100
Q15 = 1 << 15


@dataclass(frozen=True)
class PcmSource:
    samples: tuple[int, ...]
    sample_rate: int


def _read_pcm_mono(path: Path) -> PcmSource:
    payload = path.read_bytes()
    if len(payload) < 12 or payload[:4] != b"RIFF" or payload[8:12] != b"WAVE":
        raise ValueError(f"not a RIFF/WAVE file: {path}")

    fmt_payload: bytes | None = None
    data_payload: bytes | None = None
    offset = 12
    while offset + 8 <= len(payload):
        chunk_id = payload[offset : offset + 4]
        chunk_size = struct.unpack_from("<I", payload, offset + 4)[0]
        chunk_start = offset + 8
        chunk_end = chunk_start + chunk_size
        if chunk_end > len(payload):
            raise ValueError(f"truncated {chunk_id!r} chunk: {path}")
        if chunk_id == b"fmt " and fmt_payload is None:
            fmt_payload = payload[chunk_start:chunk_end]
        elif chunk_id == b"data" and data_payload is None:
            data_payload = payload[chunk_start:chunk_end]
        offset = chunk_end + (chunk_size & 1)

    if fmt_payload is None or data_payload is None or len(fmt_payload) < 16:
        raise ValueError(f"missing fmt/data chunk: {path}")
    audio_format, channels, sample_rate, _, block_align, bits = struct.unpack_from(
        "<HHIIHH", fmt_payload, 0
    )
    if audio_format != 1 or channels not in (1, 2) or bits not in (16, 24):
        raise ValueError(
            f"unsupported PCM format={audio_format} channels={channels} bits={bits}: {path}"
        )
    sample_width = bits // 8
    expected_align = channels * sample_width
    if block_align != expected_align or len(data_payload) % block_align != 0:
        raise ValueError(f"invalid PCM block alignment: {path}")

    mono: list[int] = []
    for frame_offset in range(0, len(data_payload), block_align):
        channel_values: list[int] = []
        for channel in range(channels):
            sample_offset = frame_offset + channel * sample_width
            if sample_width == 2:
                value = struct.unpack_from("<h", data_payload, sample_offset)[0]
            else:
                value = int.from_bytes(
                    data_payload[sample_offset : sample_offset + 3],
                    byteorder="little",
                    signed=True,
                ) >> 8
            channel_values.append(value)
        mono.append(sum(channel_values) // len(channel_values))
    return PcmSource(tuple(mono), sample_rate)


def _resample_to_length(samples: tuple[int, ...] | list[int], length: int) -> list[int]:
    if not samples or length <= 0:
        return []
    if len(samples) == 1 or length == 1:
        return [int(samples[0])] * length
    denominator = length - 1
    source_span = len(samples) - 1
    output: list[int] = []
    for output_index in range(length):
        position_numerator = output_index * source_span
        source_index, fraction = divmod(position_numerator, denominator)
        next_index = min(source_index + 1, source_span)
        mixed = (
            int(samples[source_index]) * (denominator - fraction)
            + int(samples[next_index]) * fraction
        )
        output.append(mixed // denominator)
    return output


def _remove_dc(samples: list[int]) -> list[int]:
    if not samples:
        return []
    mean = sum(samples) // len(samples)
    return [sample - mean for sample in samples]


def _low_pass(samples: list[int], alpha_q15: int) -> list[int]:
    if not samples:
        return []
    state = samples[0]
    output: list[int] = []
    for sample in samples:
        state += ((sample - state) * alpha_q15) // Q15
        output.append(state)
    return output


def _scale(samples: list[int], gain_q15: int) -> list[int]:
    return [(sample * gain_q15) // Q15 for sample in samples]


def _fade(samples: list[int], fade_in: int = 0, fade_out: int = 0) -> list[int]:
    output = samples.copy()
    if fade_in > 1:
        limit = min(fade_in, len(output))
        for index in range(limit):
            output[index] = (output[index] * index) // (limit - 1)
    if fade_out > 1:
        limit = min(fade_out, len(output))
        for offset in range(limit):
            index = len(output) - limit + offset
            output[index] = (output[index] * (limit - 1 - offset)) // (limit - 1)
    return output


def _mix(left: list[int], right: list[int], left_q15: int, right_q15: int) -> list[int]:
    length = max(len(left), len(right))
    output: list[int] = []
    for index in range(length):
        left_value = left[index] if index < len(left) else 0
        right_value = right[index] if index < len(right) else 0
        value = (left_value * left_q15 + right_value * right_q15) // Q15
        output.append(max(-30_000, min(30_000, value)))
    return output


def _make_roll_loop(mining: PcmSource) -> list[int]:
    length = (TARGET_RATE * 3) // 4  # 0.75 s, matching the authored ROLL phase.
    texture = _resample_to_length(mining.samples, length)
    texture = _scale(_low_pass(_remove_dc(texture), 4_096), 21_299)
    # Make the wrap boundary continuous with a deterministic 80 ms reverse-head
    # crossfade. The final sample is byte-identical to the first sample.
    crossfade = (TARGET_RATE * 80) // 1_000
    for offset in range(crossfade):
        index = length - crossfade + offset
        weight = (offset * Q15) // (crossfade - 1)
        head_value = texture[crossfade - 1 - offset]
        texture[index] = (
            texture[index] * (Q15 - weight) + head_value * weight
        ) // Q15
    texture[-1] = texture[0]
    return texture


def _make_stamp(mining: PcmSource, chime: PcmSource) -> list[int]:
    length = (TARGET_RATE * 2) // 5  # 0.40 s.
    thud_length = (TARGET_RATE * 18) // 100
    thud = _resample_to_length(mining.samples, thud_length)
    thud = _fade(_scale(_low_pass(_remove_dc(thud), 5_120), 24_576), 110, thud_length)
    thud.extend([0] * (length - len(thud)))
    bell = _resample_to_length(chime.samples, length)
    bell = _fade(_scale(_low_pass(_remove_dc(bell), 16_384), 19_661), 110, 3_528)
    return _mix(thud, bell, 27_853, 24_576)


def _make_result_tail(round_gong: PcmSource) -> list[int]:
    source = list(round_gong.samples)
    peak = max(abs(sample) for sample in source)
    threshold = max(1, peak // 50)
    onset = next((index for index, sample in enumerate(source) if abs(sample) >= threshold), 0)
    start = max(0, onset - TARGET_RATE // 100)
    source = source[start : start + (TARGET_RATE * 9) // 10]
    length = (TARGET_RATE * 6) // 5  # 1.20 s, pitch-down by time expansion.
    tail = _resample_to_length(tuple(source), length)
    tail = _low_pass(_remove_dc(tail), 8_192)
    tail = _fade(_scale(tail, 22_938), 220, (TARGET_RATE * 2) // 5)
    return tail


def _canonical_wav(samples: list[int]) -> bytes:
    pcm = b"".join(struct.pack("<h", max(-32_768, min(32_767, value))) for value in samples)
    fmt = struct.pack("<HHIIHH", 1, 1, TARGET_RATE, TARGET_RATE * 2, 2, 16)
    body = b"fmt " + struct.pack("<I", len(fmt)) + fmt
    body += b"data" + struct.pack("<I", len(pcm)) + pcm
    return b"RIFF" + struct.pack("<I", len(body) + 4) + b"WAVE" + body


def _validate_canonical_wav(payload: bytes, label: str) -> None:
    if payload[:4] != b"RIFF" or payload[8:12] != b"WAVE":
        raise ValueError(f"{label}: missing RIFF/WAVE header")
    declared_size = struct.unpack_from("<I", payload, 4)[0] + 8
    if declared_size != len(payload):
        raise ValueError(f"{label}: RIFF size {declared_size} != actual {len(payload)}")
    chunk_ids: list[bytes] = []
    offset = 12
    while offset + 8 <= len(payload):
        chunk_id = payload[offset : offset + 4]
        chunk_size = struct.unpack_from("<I", payload, offset + 4)[0]
        chunk_ids.append(chunk_id)
        offset += 8 + chunk_size + (chunk_size & 1)
    if offset != len(payload) or chunk_ids != [b"fmt ", b"data"]:
        raise ValueError(f"{label}: non-canonical chunks {chunk_ids!r} or trailing bytes")


def _build_outputs(godot_root: Path) -> dict[Path, bytes]:
    sound_root = godot_root / "assets" / "sounds"
    mining = _read_pcm_mono(sound_root / "mining.wav")
    round_gong = _read_pcm_mono(sound_root / "roundgong.wav")
    chime = _read_pcm_mono(sound_root / "stage2_speed_defense_block_chime.wav")
    if {mining.sample_rate, round_gong.sample_rate, chime.sample_rate} != {TARGET_RATE}:
        raise ValueError("Guardian Enhancement sources must remain 44.1 kHz")
    output_root = sound_root / "lingpet"
    return {
        output_root / "guardian_enhance_roll_loop.wav": _canonical_wav(_make_roll_loop(mining)),
        output_root / "guardian_enhance_stamp.wav": _canonical_wav(_make_stamp(mining, chime)),
        output_root / "guardian_enhance_result_tail.wav": _canonical_wav(_make_result_tail(round_gong)),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the canonical derived WAV files")
    mode.add_argument("--check", action="store_true", help="verify committed WAVs byte-for-byte")
    args = parser.parse_args()

    godot_root = Path(__file__).resolve().parents[1]
    outputs = _build_outputs(godot_root)
    for path, expected in outputs.items():
        _validate_canonical_wav(expected, path.name)
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
        if not path.is_file():
            raise FileNotFoundError(path)
        actual = path.read_bytes()
        _validate_canonical_wav(actual, path.name)
        if actual != expected:
            raise ValueError(f"{path}: committed bytes do not match deterministic derivation")
        digest = hashlib.sha256(actual).hexdigest().upper()
        data_bytes = len(actual) - 44
        duration = data_bytes / (TARGET_RATE * 2)
        print(f"{path.relative_to(godot_root)} sha256={digest} duration={duration:.3f}s")
    print("guardian_enhance_audio_derivation: ok")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # deterministic CLI failure surface for CI and intake.
        print(f"guardian_enhance_audio_derivation: ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
