extends RefCounted

const INIT_ORDER := [
	"catalog",
	"audio_router",
	"gauge_feedback",
	"context_builder",
	"roll_editor_runtime",
	"equipment_index",
	"equipment_facade",
	"ownership_runtime",
	"auto_defense_runtime",
	"ai_assist_runtime",
	"dowsing_runtime",
	"perk_choice_runtime",
	"defense_gear_runtime",
	"capacity_gauge_runtime",
	"resource_bonus_runtime",
	"throw_bonus_runtime",
	"cooldown_gear_runtime",
	"progression_bonus_runtime",
	"venom_mist_runtime",
	"rainbow_fur_glove_runtime",
	"adversity_armor_runtime",
	"shrapnel_armor_runtime",
	"ragnarok_runtime",
	"poseidon_runtime",
	"soul_burst_runtime",
	"knee_pads_runtime",
	"stat_bonus_runtime",
	"horn_strawberry_mask_runtime",
	"horn_strawberry_mask_state",
	"horn_strawberry_eat_state",
	"horn_strawberry_field_state",
	"horn_strawberry_horn_charge_state",
	"horn_strawberry_bomb_state",
	"pause_gate",
	"update_gate",
	"update_runtime",
	"lifecycle_runtime",
	"owner_syncer",
	"pickup_bonus",
	"roll_query",
	"stage_immunity",
	"debug_management_menu",
	"debug_management_facade",
	"activation_effect_renderer",
	"activation_effect_runtime",
	"field_effect_visibility",
	"field_effect_renderer",
	"support_effect_renderer",
	"snapshot_builder",
	"acquisition_cinematic_runtime",
	"foul_whistle_runtime",
	"foul_whistle_state",
	"revival_runtime",
	"revival_state",
	"odins_eye_runtime",
	"odins_eye_state",
	"odins_eye_afterimage_state",
	"odins_eye_dark_swamp_state",
	"celestial_armor_runtime",
	"celestial_armor_state",
	"yangui_hoechun_runtime",
	"heavenly_cape_runtime",
	"hermes_shoes_runtime",
	"hermes_shoes_state",
	"baal_boots_runtime",
	"baal_boots_effect_renderer",
	"baal_boots_weather_state",
	"baal_boots_effect_state",
	"baal_boots_combat_state",
	"pandora_legacy_runtime",
	"pandora_legacy_choice_builder",
	"pandora_legacy_grant_router",
	"pandora_legacy_pool_builder",
	"pandora_legacy_selection_renderer",
	"pandora_legacy_selection_state",
]

const SCRIPT_PATHS := {
	"catalog": "res://scripts/items/mythic_item_catalog.gd",
	"audio_router": "res://scripts/items/mythic_item_audio_router.gd",
	"gauge_feedback": "res://scripts/items/mythic_item_gauge_feedback.gd",
	"context_builder": "res://scripts/items/mythic_item_context_builder.gd",
	"roll_editor_runtime": "res://scripts/items/mythic_item_roll_editor_runtime.gd",
	"equipment_index": "res://scripts/items/mythic_item_equipment_index.gd",
	"equipment_facade": "res://scripts/items/mythic_item_equipment_facade.gd",
	"ownership_runtime": "res://scripts/items/mythic_item_ownership_runtime.gd",
	"auto_defense_runtime": "res://scripts/items/mythic_item_auto_defense_runtime.gd",
	"ai_assist_runtime": "res://scripts/items/mythic_item_ai_assist_runtime.gd",
	"dowsing_runtime": "res://scripts/items/mythic_item_dowsing_runtime.gd",
	"perk_choice_runtime": "res://scripts/items/mythic_item_perk_choice_runtime.gd",
	"defense_gear_runtime": "res://scripts/items/mythic_item_defense_gear_runtime.gd",
	"capacity_gauge_runtime": "res://scripts/items/mythic_item_capacity_gauge_runtime.gd",
	"resource_bonus_runtime": "res://scripts/items/mythic_item_resource_bonus_runtime.gd",
	"throw_bonus_runtime": "res://scripts/items/mythic_item_throw_bonus_runtime.gd",
	"cooldown_gear_runtime": "res://scripts/items/mythic_item_cooldown_gear_runtime.gd",
	"progression_bonus_runtime": "res://scripts/items/mythic_item_progression_bonus_runtime.gd",
	"venom_mist_runtime": "res://scripts/items/mythic_item_venom_mist_runtime.gd",
	"rainbow_fur_glove_runtime": "res://scripts/items/mythic_item_rainbow_fur_glove_runtime.gd",
	"adversity_armor_runtime": "res://scripts/items/mythic_item_adversity_armor_runtime.gd",
	"shrapnel_armor_runtime": "res://scripts/items/mythic_item_shrapnel_armor_runtime.gd",
	"ragnarok_runtime": "res://scripts/items/mythic_item_ragnarok_runtime.gd",
	"poseidon_runtime": "res://scripts/items/mythic_item_poseidon_runtime.gd",
	"soul_burst_runtime": "res://scripts/items/mythic_item_soul_burst_runtime.gd",
	"knee_pads_runtime": "res://scripts/items/mythic_item_knee_pads_runtime.gd",
	"stat_bonus_runtime": "res://scripts/items/mythic_item_stat_bonus_runtime.gd",
	"horn_strawberry_mask_runtime": "res://scripts/items/mythic_item_horn_strawberry_mask_runtime.gd",
	"horn_strawberry_mask_state": "res://scripts/items/mythic_item_horn_strawberry_mask_state.gd",
	"horn_strawberry_eat_state": "res://scripts/items/horn_strawberry_eat_state.gd",
	"horn_strawberry_field_state": "res://scripts/items/horn_strawberry_field_state.gd",
	"horn_strawberry_horn_charge_state": "res://scripts/items/horn_strawberry_horn_charge_state.gd",
	"horn_strawberry_bomb_state": "res://scripts/items/horn_strawberry_bomb_state.gd",
	"pause_gate": "res://scripts/items/mythic_item_pause_gate.gd",
	"update_gate": "res://scripts/items/mythic_item_update_gate.gd",
	"update_runtime": "res://scripts/items/mythic_item_update_runtime.gd",
	"lifecycle_runtime": "res://scripts/items/mythic_item_lifecycle_runtime.gd",
	"owner_syncer": "res://scripts/items/mythic_item_owner_syncer.gd",
	"pickup_bonus": "res://scripts/items/mythic_item_pickup_bonus.gd",
	"roll_query": "res://scripts/items/mythic_item_roll_query.gd",
	"stage_immunity": "res://scripts/items/mythic_item_stage_immunity.gd",
	"debug_management_menu": "res://scripts/items/passive_mythic_item_debug_menu.gd",
	"debug_management_facade": "res://scripts/items/mythic_item_debug_management_facade.gd",
	"activation_effect_renderer": "res://scripts/items/mythic_item_activation_effect_renderer.gd",
	"activation_effect_runtime": "res://scripts/items/mythic_item_activation_effect_runtime.gd",
	"field_effect_visibility": "res://scripts/items/mythic_item_field_effect_visibility.gd",
	"field_effect_renderer": "res://scripts/items/mythic_item_field_effect_renderer.gd",
	"support_effect_renderer": "res://scripts/items/mythic_item_support_effect_renderer.gd",
	"snapshot_builder": "res://scripts/items/mythic_item_snapshot_builder.gd",
	"acquisition_cinematic_runtime": "res://scripts/items/mythic_item_acquisition_cinematic_runtime.gd",
	"foul_whistle_runtime": "res://scripts/items/mythic_item_foul_whistle_runtime.gd",
	"foul_whistle_state": "res://scripts/items/foul_whistle_state.gd",
	"revival_runtime": "res://scripts/items/mythic_item_revival_runtime.gd",
	"revival_state": "res://scripts/items/revival_state.gd",
	"odins_eye_runtime": "res://scripts/items/mythic_item_odins_eye_runtime.gd",
	"odins_eye_state": "res://scripts/items/odins_eye_state.gd",
	"odins_eye_afterimage_state": "res://scripts/items/odins_eye_afterimage_state.gd",
	"odins_eye_dark_swamp_state": "res://scripts/items/odins_eye_dark_swamp_state.gd",
	"celestial_armor_runtime": "res://scripts/items/mythic_item_celestial_armor_runtime.gd",
	"celestial_armor_state": "res://scripts/items/celestial_armor_state.gd",
	"yangui_hoechun_runtime": "res://scripts/items/mythic_item_yangui_hoechun_runtime.gd",
	"heavenly_cape_runtime": "res://scripts/items/mythic_item_heavenly_cape_runtime.gd",
	"hermes_shoes_runtime": "res://scripts/items/mythic_item_hermes_shoes_runtime.gd",
	"hermes_shoes_state": "res://scripts/items/hermes_shoes_state.gd",
	"baal_boots_runtime": "res://scripts/items/mythic_item_baal_boots_runtime.gd",
	"baal_boots_effect_renderer": "res://scripts/items/baal_boots_effect_renderer.gd",
	"baal_boots_weather_state": "res://scripts/items/baal_boots_weather_state.gd",
	"baal_boots_effect_state": "res://scripts/items/baal_boots_effect_state.gd",
	"baal_boots_combat_state": "res://scripts/items/baal_boots_combat_state.gd",
	"pandora_legacy_runtime": "res://scripts/items/mythic_item_pandora_legacy_runtime.gd",
	"pandora_legacy_choice_builder": "res://scripts/items/pandora_legacy_choice_builder.gd",
	"pandora_legacy_grant_router": "res://scripts/items/pandora_legacy_grant_router.gd",
	"pandora_legacy_pool_builder": "res://scripts/items/pandora_legacy_pool_builder.gd",
	"pandora_legacy_selection_renderer": "res://scripts/items/mythic_item_pandora_selection_renderer.gd",
	"pandora_legacy_selection_state": "res://scripts/items/pandora_legacy_selection_state.gd",
}


static func get_script_path(member_name: String) -> String:
	return str(SCRIPT_PATHS.get(member_name, ""))


static func create_helper(member_name: String) -> Object:
	var path := get_script_path(member_name)
	if path == "":
		return null
	var script: Variant = load(path)
	if script == null:
		return null
	return script.new()
